### ISSUE TITLE
Overlapping workspace switcher and task list items

### ISSUE THREAD

**Issue by danboid** [solus-project/budgie-desktop#522] opened 2016-08-02 10:26 UTC
If you have both the workspace switcher and the task list panel applets added to the panel and you have enough programs running, the task items start to appear below the workspace switcher and when you try clicking on a workspace that has a task below it, the task takes precedence so the switcher becomes unusable for the affected overlapping area.

I would expect the task items to start being squashed horizontally after a certain number are running and panel space starts running out, instead of sliding under the workspace switcher or any other panel applet. Note I'm referring to the 'Task list' applet and not the 'Icon task list' although maybe that has the same problem?

**Comment by fossfreedom** [comment] 2016-08-02 10:38
similar or the same as this - https://github.com/solus-project/budgie-desktop/issues/83

**Comment by ikeydoherty** [comment] 2016-08-02 10:57
Its a dupe of #83 ya

**Closed by ikeydoherty** 2016-08-02 10:57 UTC
