### ISSUE TITLE
Slight "Flicker effect" when you menu bar is not at the top

### ISSUE THREAD

**Issue by thauti** [solus-project/budgie-desktop#603] opened 2016-09-17 20:57 UTC
**Operating System**: Solus 1.2.0.5 (Unstable)
**Budgie version**: Budgie 10.2.7

When the menubar is not at the top of the screen (eg. at the bottom), when you open the apps menu or the volume slider, you have during few frames (1-3 frames) the element appears at the top of the screen.
I guess, that it's a problem, when you create the element, it assumes that your menu is at the top, and updates his position just after his creation. (and create the "flicker effect").

**Steps to reproduce the issue**

- Change the position of the menu bar (eg. at the Botton).
- Open the apps menu, or the volume slider

**Comment by ikeydoherty** [comment] 2016-09-17 21:02
This is a duplicate of #292, currently have no fix for this and would love some help with it if anyone has the time

**Closed by ikeydoherty** 2016-09-17 21:02 UTC
