### ISSUE TITLE
Budgie menu doesn't show / hide properly and doesn't catch keyboard focus

### ISSUE THREAD

**Issue by Bios-Marcel** [solus-project/budgie-desktop#1444] opened 2018-05-20 11:29 UTC
**Operating System**: Solus 3.9997
**Budgie version**: budgie-desktop v10.4-70-g15c960cc

**The issue encountered**

The `budgie menu` doesn't show up sometimes when pressing `Super`, after pressing multiple times it will show up and not catch the keyboard focus. The keyboard focus will remain in whatever application you have been before. The menu will also not be closable. 

**Steps to reproduce the issue**

I just have to press super in order to reproduce, i don't know how others can reproduce this. I have had this bug since i installed solus, therefore it is not due to modifications or so.

**Comment by Bios-Marcel** [comment] 2018-05-20 12:00
to workaround this bug i am doing this: https://asksolus.com/question/how-to-rebind-the-super-windows-key/

Since to me the budgie menu is nothing but a searchbar for applications.

**Comment by JoshStrobl** [comment] 2020-10-10 00:23
Duplicate of #1199

**Closed by JoshStrobl** 2020-10-10 00:23 UTC
