### ISSUE TITLE
Feature: Add support for meta+1 , meta +2 type shortcuts like plank to icon tasklist

### ISSUE THREAD

**Issue by prateekmedia** [solus-project/budgie-desktop#2076] opened 2020-12-12 06:14 UTC
### Current Budgie version

10.5.2

### Use-cases

It is used everytime and is on every other DE, it can be used to quickly switch from one app to another without interfering with mouse

It would also make more users use dock mode instead of plank as plank has this option but dock mode or normal mode doesnt

### Proposal

Add shortcuts support to icon tasks or budgie desktop itself
Meta 1 means first app in icon task list 
Meta 2 for second app in icon task list  and so on...
Meta 0 means open budgie menu,

If multiple icon tasks are their give preference to first one from top or one with dock mode

I dont think applets support keyboard shortcut natively as their  is no official budgie vala documentation for it.

**Comment by JoshStrobl** [comment] 2020-12-13 05:56
Duplicate of #1015. Use the search in the future.

**Closed by JoshStrobl** 2020-12-13 05:56 UTC
