### ISSUE TITLE
Allow for resizing of icons the bottom panel without resiszing the panel itself

### ISSUE THREAD

**Issue by LoureiroTiago00** [solus-project/budgie-desktop#2107] opened 2021-02-17 16:18 UTC
### Current Budgie version
budgie-desktop 10.5.2 (git-481e9bd25afaa4f35ae9db6fdde28d17ec29cbe9)

### Use-cases
Resizing of icons in the bottom panel independently from the panel itself. Icons in the task list are currently too small for my liking

**Comment by JoshStrobl** [comment] 2021-02-17 17:43
Duplicate of #701

**Closed by JoshStrobl** 2021-02-17 17:43 UTC
