### ISSUE TITLE
Delay when using Super key to open Budgie Menu

### ISSUE THREAD

**Issue by theray76** [solus-project/budgie-desktop#1390] opened 2018-04-28 13:39 UTC
Operating System: Solus 3.999
Budgie version: Budgie 10.4

**The issue encountered**

After the latest round of Solus updates, I started experiencing 1-9 second lag between pressing the super key and the Budgie menu opening. 

**Steps to reproduce the issue**

I confirmed the updates were the cause by rolling back using eopkg history -t. This fixed the problem, and when I ran the updates again, the problem re-appeared. Below is a list of updates that may have caused the issue:

```
    * file is upgraded from 5.32-13-1-x86_64 to 5.32-15-1-x86_64 with delta.
    * libpcre is upgraded from 8.41-16-1-x86_64 to 8.42-17-1-x86_64 with delta.
    * pam is upgraded from 1.1.6-12-1-x86_64 to 1.1.6-13-1-x86_64 with delta.
    * usysconf is upgraded from 0.5.1-18-1-x86_64 to 0.5.1-20-1-x86_64 with delta.
    * attica is upgraded from 5.44.0-12-1-x86_64 to 5.45.0-13-1-x86_64 with delta.
    * xmlsec1 1.2.25-1-1-x86_64 is installed.
    * libreoffice-common is upgraded from 6.0.3.2-64-1-x86_64 to 6.0.3.2-65-1-x86_64 with delta.
    * libreoffice-writer is upgraded from 6.0.3.2-64-1-x86_64 to 6.0.3.2-65-1-x86_64 with delta.
    * libreoffice-draw is upgraded from 6.0.3.2-64-1-x86_64 to 6.0.3.2-65-1-x86_64 with delta.
    * libreoffice-impress is upgraded from 6.0.3.2-64-1-x86_64 to 6.0.3.2-65-1-x86_64 with delta.
    * ki18n is upgraded from 5.44.0-14-1-x86_64 to 5.45.0-16-1-x86_64 with delta.
    * sonnet is upgraded from 5.44.0-16-1-x86_64 to 5.45.0-17-1-x86_64 with delta.
    * kcoreaddons is upgraded from 5.44.0-15-1-x86_64 to 5.45.0-17-1-x86_64 with delta.
    * kconfig is upgraded from 5.44.0-12-1-x86_64 to 5.45.0-14-1-x86_64 with delta.
    * kwidgetsaddons is upgraded from 5.44.0-13-1-x86_64 to 5.45.0-15-1-x86_64 with delta.
    * kitemviews is upgraded from 5.44.0-13-1-x86_64 to 5.45.0-15-1-x86_64 with delta.
    * karchive is upgraded from 5.44.0-13-1-x86_64 to 5.45.0-15-1-x86_64 with delta.
    * kguiaddons is upgraded from 5.44.0-13-1-x86_64 to 5.45.0-15-1-x86_64.
    * kauth is upgraded from 5.44.0-16-1-x86_64 to 5.45.0-18-1-x86_64 with delta.
    * kcodecs is upgraded from 5.44.0-13-1-x86_64 to 5.45.0-15-1-x86_64 with delta.
    * kconfigwidgets is upgraded from 5.44.0-13-1-x86_64 to 5.45.0-15-1-x86_64 with delta.
    * kiconthemes is upgraded from 5.44.0-12-1-x86_64 to 5.45.0-13-1-x86_64 with delta.
    * kwindowsystem is upgraded from 5.44.0-14-1-x86_64 to 5.45.0-16-1-x86_64 with delta.
    * kcompletion is upgraded from 5.44.0-14-1-x86_64 to 5.45.0-16-1-x86_64 with delta.
    * kdbusaddons is upgraded from 5.44.0-13-1-x86_64 to 5.45.0-14-1-x86_64 with delta.
    * kcrash is upgraded from 5.44.0-12-1-x86_64 to 5.45.0-13-1-x86_64 with delta.
    * kservice is upgraded from 5.44.0-17-1-x86_64 to 5.45.0-18-1-x86_64 with delta.
    * ktextwidgets is upgraded from 5.44.0-13-1-x86_64 to 5.45.0-14-1-x86_64 with delta.
    * kglobalaccel is upgraded from 5.44.0-12-1-x86_64 to 5.45.0-13-1-x86_64 with delta.
    * kxmlgui is upgraded from 5.44.0-14-1-x86_64 to 5.45.0-15-1-x86_64 with delta.
    * kjobwidgets is upgraded from 5.44.0-13-1-x86_64 to 5.45.0-14-1-x86_64 with delta.
    * knotifications is upgraded from 5.44.0-13-1-x86_64 to 5.45.0-14-1-x86_64 with delta.
    * kwallet is upgraded from 5.44.0-13-1-x86_64 to 5.45.0-14-1-x86_64 with delta.
    * solid is upgraded from 5.44.0-15-1-x86_64 to 5.45.0-16-1-x86_64 with delta.
    * kbookmarks is upgraded from 5.44.0-13-1-x86_64 to 5.45.0-14-1-x86_64 with delta.
    * kdoctools is upgraded from 5.44.0-13-1-x86_64 to 5.45.0-15-1-x86_64 with delta.
    * kio is upgraded from 5.44.0-19-1-x86_64 to 5.45.0-20-1-x86_64 with delta.
    * knewstuff is upgraded from 5.44.0-16-1-x86_64 to 5.45.0-17-1-x86_64 with delta.
    * frameworkintegration is upgraded from 5.44.0-11-1-x86_64 to 5.45.0-12-1-x86_64 with delta.
    * linux-steam-integration is upgraded from 0.7.2-26-1-x86_64 to 0.7.2-27-1-x86_64 with delta.
    * kpackage is upgraded from 5.44.0-12-1-x86_64 to 5.45.0-13-1-x86_64 with delta.
    * kwayland is upgraded from 5.44.0-10-1-x86_64 to 5.45.0-11-1-x86_64 with delta.
    * kdeclarative is upgraded from 5.44.0-15-1-x86_64 to 5.45.0-16-1-x86_64 with delta.
    * kcmutils is upgraded from 5.44.0-11-1-x86_64 to 5.45.0-12-1-x86_64 with delta.
    * adapta-gtk-theme is upgraded from 3.93.0.244-153-1-x86_64 to 3.93.0.262-156-1-x86_64 with delta.
    * libpcre-32bit is upgraded from 8.41-16-1-x86_64 to 8.42-17-1-x86_64 with delta.
    * linux-firmware is upgraded from 20180402-26-1-x86_64 to 20180416-27-1-x86_64 with delta.
    * solus-artwork is upgraded from 18-33-1-x86_64 to 20-35-1-x86_64 with delta.
    * libwebkit-gtk is upgraded from 2.18.6-42-1-x86_64 to 2.18.6-44-1-x86_64 with delta.
    * gnome-online-accounts is upgraded from 3.26.1-25-1-x86_64 to 3.26.1-26-1-x86_64 with delta.
    * knotifyconfig is upgraded from 5.44.0-12-1-x86_64 to 5.45.0-13-1-x86_64 with delta.
    * kfilemetadata is upgraded from 5.44.0-20-1-x86_64 to 5.45.0-21-1-x86_64 with delta.
    * youtube-dl is upgraded from 2018.03.10-91-1-x86_64 to 2018.04.16-92-1-x86_64 with delta.
    * libreoffice-calc is upgraded from 6.0.3.2-64-1-x86_64 to 6.0.3.2-65-1-x86_64 with delta.
    * libressl-shim is upgraded from 2.6.4-2-1-x86_64 to 2.7.2-3-1-x86_64.
    * libressl-shim-32bit is upgraded from 2.6.4-2-1-x86_64 to 2.7.2-3-1-x86_64.
    * snapd is upgraded from 2.30-21-1-x86_64 to 2.32.5-22-1-x86_64 with delta.
    * openjpeg is upgraded from 2.2.0-11-1-x86_64 to 2.3.0-12-1-x86_64.
    * pcre2 is upgraded from 10.30-5-1-x86_64 to 10.31-6-1-x86_64 with delta.
    * ghostscript is upgraded from 9.21-13-1-x86_64 to 9.21-14-1-x86_64 with delta.
    * evolution-data-server is upgraded from 3.26.6-33-1-x86_64 to 3.26.6-34-1-x86_64 with delta.
    * yelp is upgraded from 3.26.0-6-1-x86_64 to 3.26.0-7-1-x86_64 with delta.
    * gnucash is upgraded from 3.0-2-1-x86_64 to 3.0-3-1-x86_64 with delta.
    * pbr 4.0.2-5-1-x86_64 is installed.
    * breeze-icons is upgraded from 5.44.0-13-1-x86_64 to 5.45.0-14-1-x86_64 with delta.
    * kinit is upgraded from 5.44.0-14-1-x86_64 to 5.45.0-15-1-x86_64 with delta.
    * gnupg is upgraded from 2.2.5-16-1-x86_64 to 2.2.6-17-1-x86_64 with delta.
    * guake is upgraded from 3.0.4-6-1-x86_64 to 3.2.0-7-1-x86_64 with delta.
    * nano is upgraded from 2.9.5-96-1-x86_64 to 2.9.5-97-1-x86_64 with delta.
```

I've confirmed that rolling back nvidia packages alone did not fix the issue.

**Comment by fossfreedom** [comment] 2018-04-28 22:03
Think this should be reported on the Solus phabricator issue tracker

**Comment by 0scubasteve0** [comment] 2018-04-28 23:39
https://dev.solus-project.com/T6286

I was told to come here, lol.

**Comment by fossfreedom** [comment] 2018-04-28 23:50
Ah. In that case sure. Odd behaviour. I havent heard about a similar issue on any other distro. Hopefully someone can chip in here to help resolve.

**Comment by indierodo** [comment] 2020-03-27 19:56
I have found the same problem, but a long time has passed since the last comment. Please tell me if I should open a new issue.

## Description
Super Button does not open Budgie Menu in panel anymore after updating.

## Budgie version
budgie-desktop 10.5.1 (git-10b814fa62bf774ca48e182548d3c6687a852314)
Copyright © 2014-2019 Budgie Desktop Developers

## Operating system
Manjaro Linux

## Steps to reproduce the issue
Create a budgie menu in a panel, press Super key in the keyboard, 

## Actual result
Nothing happens

## Expected result
Open Budgie Menu

## Additional information
```
    $ grep -i upgraded /var/log/pacman.log | grep budgie
    [2020-03-27T01:57:20-0600] [ALPM] upgraded budgie-desktop (10.5.1-1 -> 10.5.1+12+g10b814fa-1)
```

**Comment by JoshStrobl** [comment] 2020-10-10 00:23
Duplicate of #1199

**Closed by JoshStrobl** 2020-10-10 00:23 UTC
