### ISSUE TITLE
Multi-users machine : shut down ⋅ switch user

### ISSUE THREAD

**Issue by Coeur-Noir** [solus-project/budgie-desktop#2118] opened 2021-04-01 21:51 UTC
### Current Budgie version
budgie-desktop 10.5.1
Ubuntu Budgie 20.04

### Use-cases
**1⋅** Using Budgie on a couple of machines - all having many user-sessions - I found the same « issue » on all : when shutting down the pc from current user / current desktop I am never warned if another session is also running, so that I may break someone else’s work.

If I shutdown from login screen - lightdm - here I have a warning if another session is running ( funnily it looks like Unity’s design )

**2⋅** Which leads to the mechanic for switching users. I mean switching **without disconnecting / stopping** current session.
First « natural » guess is to click on user indicator in panel.
But here no hint about switching user.
Actually you have to click on « Lock », wait for the lock screen to appear and there you’ll see the button for « change user ».
Click on it, you are back to login screen where you can chose another user.

That works but is a bit hidden.

### Proposal
**1⋅** a warning inside the shutdown dialog box « other user⋅s are logged on, are you sure to shutdown ? »

**2⋅** I’d say I’d expect one of these 2 « ways » _inside_ user indicator for switching without disconnecting current one :
⋅ a « change user » item above « lock » that’d straight lead to the login screen, or
⋅ a list of all users available where a click on a name would lead to the login screen with that user already selected, waiting for password ( or would lead straight into that session if already opened and not locked )

I assume these 2 ways are not « easy » to add, so as a third way maybe just rename « lock » into « lock | change user » as a hint ? Well that may be too long in some languages though… [ in french it would then read : verrouiller | changer d’utilisateur ]

### References
Here a mention about a _future user switching functionality_ https://github.com/solus-project/budgie-desktop/issues/1538

**Comment by JoshStrobl** [comment] 2021-04-08 23:59
Duplicate of #1024

**Closed by JoshStrobl** 2021-04-08 23:59 UTC
