### ISSUE TITLE
Applets sorting doesn't work correctly

### ISSUE THREAD

**Issue by Solarunit** [solus-project/budgie-desktop#1535] opened 2018-08-14 01:39 UTC
Solus 3.9999
budgie-desktop v10.4-85-g36667bcb

Applets sorting doesn't work correctly (see gif)

Impossible to move Raven Sidebar Control below User Indicator 

![panel](https://user-images.githubusercontent.com/20891064/44066798-f6b316fe-9f7a-11e8-8912-f8755e01db0f.gif)

But you can see that Raven Sidebar Control actually at the edge of the screen.

![Alt Text](https://ibin.co/4C71eSgupT7q.png)

**Comment by JoshStrobl** [comment] 2018-08-14 03:43
Duplicate of #1253

**Closed by JoshStrobl** 2018-08-14 03:43 UTC
