### ISSUE TITLE
Budgie panel - System tray icons not refreshing correctly

### ISSUE THREAD

**Issue by chax** [solus-project/budgie-desktop#1836] opened 2019-06-18 09:20 UTC
## Description

Budgie panel - System tray icons not refreshing correctly

## Budgie version

budgie-desktop 10.5 (git-8450ae384660c87bced67ded58c783be58a65a29)
Copyright © 2014-2019 Budgie Desktop Developers

## Operating system

Solus

## Steps to reproduce the issue

I don't yet know how to reproduce this, could be suspend/wake issue.
When i reproduce it again, i will try to record steps to reproduce and post them here.

## Actual result

![image](https://user-images.githubusercontent.com/632945/59669066-d335b380-91b9-11e9-8b83-9e33d8fedf1e.png)

## Expected result
![image](https://user-images.githubusercontent.com/632945/59669322-4b03de00-91ba-11e9-93a3-e67f6e4d8be8.png)
(after running "budgie-panel --replace & ")

**Comment by fossfreedom** [comment] 2019-06-22 08:33
This is a dupe of https://github.com/solus-project/budgie-desktop/issues/1249

**Closed** 2019-06-22 16:20 UTC
