### ISSUE TITLE
Old https://solus-project.com/ link on GitHub

### ISSUE THREAD

**Issue by MatthewScholefield** [solus-project/budgie-desktop#1946] opened 2020-03-08 04:05 UTC
Link on repo page should be changed to https://getsol.us/
![solus](https://user-images.githubusercontent.com/5875019/76156400-9b5ffa80-60bf-11ea-99cb-847076e1455b.png)

**Comment by JoshStrobl** [comment] 2020-03-08 15:59
Duplicate of #1849

**Closed by JoshStrobl** 2020-03-08 15:59 UTC

**Comment by MatthewScholefield** [comment] 2020-03-08 16:15
Ahh, whoops I skipped right over it.
