### ISSUE TITLE
Window height issue on dual monitor setup

### ISSUE THREAD

**Issue by michaeltintiuc** [solus-project/budgie-desktop#1732] opened 2019-01-23 17:01 UTC
When using a multi-monitor setup the 2nd monitor has a dead-zone where the panel is on the primary monitor.

Setup:
- 2 monitors of identical resolutions stacked vertically
- lower monitor has the panel (always visible) on the top edge
- upper monitor windows have a maximum height of (screen_height - panel_height) even though that screen doesn't have a panel

Interestingly enough this doesn't happen when the monitor layout is horizontal.

## Budgie version
10.5

## Operating system
Solus 3

**Comment by JoshStrobl** [comment] 2019-01-24 06:57
Duplicate of #1225

**Closed by JoshStrobl** 2019-01-24 06:57 UTC
