### ISSUE TITLE
Display issue after update to budgie-desktop-10.5.1-1

### ISSUE THREAD

**Issue by zw963** [solus-project/budgie-desktop#1936] opened 2020-02-09 17:11 UTC
## Description

Following is my top pannel settings.

![image](https://user-images.githubusercontent.com/549126/74106401-be22f000-4ba1-11ea-9847-ff65cc2dfa08.png)

When my mouse cursor hover on top panel it working as expect.

![image](https://user-images.githubusercontent.com/549126/74106405-c7ac5800-4ba1-11ea-8c32-a22e864c7d00.png)

But, when i cursor move out top pannel.

![image](https://user-images.githubusercontent.com/549126/74106422-eb6f9e00-4ba1-11ea-9ab6-32ebc6308758.png)

## Budgie version
 ╰─ $ budgie-desktop --version
budgie-desktop 10.5.1 (git-e6433d87974e735296e72cf5b9d2a25466d5fe7a)
Copyright © 2014-2019 Budgie Desktop Developers

## Operating system
Arch linux, if you think this is a issue about arch, i will report there.

## Additional information

It happen on the last "pcman -Syu".

**Comment by JoshStrobl** [comment] 2020-02-09 18:42
Duplicate of #1271

**Closed by JoshStrobl** 2020-02-09 18:42 UTC
