### ISSUE TITLE
Budgie dock not showing on mouse hover if size < 53

### ISSUE THREAD

**Issue by Nycticorax** [solus-project/budgie-desktop#1777] opened 2019-03-22 07:58 UTC
## Description
Issue: Let the dock be set on 'hide: Intelligent' or 'hide: Automatic' and 'size: 52' or below. Then hovering over the edge of the screen where the dock is supposed to be will not make it show up.
Expected: Dock should show up on mouse over no matter its size. The current minimal size to get a positive response to mouse hover is 53.

## Budgie version
10.5

## Operating system
Solus 4

## Steps to reproduce the issue
See description above.

## Actual result
Not showing up under size 53.

## Expected result
Showing up no matter the size.

**Comment by yursan9** [comment] 2019-05-05 11:00
Do you use dual monitor?

**Comment by Nycticorax** [comment] 2019-05-05 16:25
Nope!

**Comment by JoshStrobl** [comment] 2020-03-16 08:07
Unable to reproduce issue by:

1. Setting panel to Dock Mode
2. Adjusting size to 52 or below.
3. Setting automatically hide to Intelligent.

Note: If you set the dock to automatic, it will only hide the dock if you have the window tiled or maximized, at which point you can show it by hovering over the area.

Given I can't reproduce the issue, marking as invalid.

**Closed by JoshStrobl** 2020-03-16 08:07 UTC

**Comment by DutchPete** [comment] 2022-03-05 13:08
I have it set to "intelligent", size 54, but it does not hide at all.
