### ISSUE TITLE
Setting the audio output through raven does not work, works in the main settings panel

### ISSUE THREAD

**Issue by StanislavNikolov** [solus-project/budgie-desktop#1102] opened 2017-08-13 10:24 UTC
**Operating System**: installed Solus 2017.04.18.0, updated from software center
**Budgie version**: budgie-desktop v10.3.1-414-g7561deb1

**The issue encountered**
Changing the sound output device in raven does not work. Using the gnome control center's sound settings works. See the [video.](https://cukii.me/stjo/other/bugs/raven.webm)

**Steps to reproduce the issue**
Open raven, while connected to a external monitor with HDMI (maybe the bug appears with other devices too, can't test).
Click on the faded dot with the "HDMI/DisplayPort ..." label next to it.
It becomes white for a split second and then goes dark again.

**Comment by StanislavNikolov** [comment] 2017-08-13 10:27
[gnome-control-center](https://cukii.tk/stjo/ok.webm)

**Comment by nan0s7** [comment] 2017-08-14 04:58
I can confirm a similar bug where (I have 4 audio outputs right now) one option will be always "selected" - however, I can still choose which output I want so long as the one that's not on 100% of the time is the one I don't want to use. I've noticed this occurring with no particular cause besides up-time being in the few hours, and have changed the output device a few times.

**Comment by th3math3us** [comment] 2018-01-26 11:41
I have the same issue! The Raven Sidebar can't change the audio output
I'm using a Laptop plugged in a TV via HDMI, when I try to change the audio output in applet 'Raven Sidebar' the volume bar flashes but it keeps the same settings.
I have to change the output in the audio options everytime

**Comment by IgorWalkers** [comment] 2018-03-18 03:18
i am here just to confirm that the problem is still present

**Comment by YoyPa** [comment] 2018-04-18 15:16
I had the same problem but solved it (while tweaking kde plasma :D).
It was related to ```/usr/share/pulseaudio/alsa-mixer/profile-sets/default.conf```
I used that file to make a new profil containing both output (```analog-stereo``` and ```iec958-stereo``` for me):
```
[Profile output:analog-stereo+output:iec958-stereo+input:analog-stereo]
description = Both
output-mappings = analog-stereo iec958-stereo
input-mappings = analog-stereo
```
And then choose it (named Both) inside gnome settings/sound/output/profil (bottom of first tab).
I think you need to restart pulseaudio.
Profile will be different for each setup.

**Comment by Oatwalker** [comment] 2018-10-06 22:34
I'm also have this problem.  Using the latest version of Solus from latest ISO (September 20th release).

I also made a video.
https://streamable.com/gs5wv

**Comment by JoshStrobl** [comment] 2019-01-02 21:53
Should be resolved in git and current builds in Solus stable repo (not in the current ISO, however).

**Closed by JoshStrobl** 2019-01-02 21:53 UTC
