### ISSUE TITLE
gnome-screenshot (3.16.2) doesn't work from keyboard shortcut or Budgie run menu

### ISSUE THREAD

**Issue by geckolinux** [solus-project/budgie-desktop#305] opened 2016-01-03 15:30 UTC
Hi there,

I'm the guy testing Budgie on openSUSE Leap 42.1. Thanks a lot for packaging it!

I'm having trouble with gnome-screenshot (version 3.16.2). For some reason, it doesn't appear at all in the Budgie start menu. Its icon does appear when I type `gnome-screenshot` in the alt+F2 run menu, but it won't open from there. Also the PrtSc shortcut is correctly configured but doesn't work (doesn't create a screenshot in ~/Pictures and doesn't open the gnome-screenshot interface), and only produces a low "ding" sound.

The only way I could use gnome-screenshot was via the terminal.

I'm not sure if this is an openSUSE packaging difference, or if it's possibly a Gnome / GTK 3.16 issue? I'll attach the gnome-screenshot .desktop file in the next post.

Thanks for looking into this!

**Comment by geckolinux** [comment] 2016-01-03 15:31
`org.gnome.Screenshot.desktop`

----------------
```````````````````````````````````````````
[Desktop Entry]
X-SuSE-translate=true
Name=Screenshot
Comment=Save images of your screen or individual windows
Keywords=snapshot;capture;print;screenshot;
Keywords[an]=pantallazo;capturar;imprentar;captura de pantalla;
Keywords[ar]=لقطة;صورة;طباعة;
Keywords[as]=snapshot;capture;print;screenshot;
Keywords[be]=здымак экрана;запіс;друк;экран;
Keywords[bg]=снимка;екран;печат;snapshot;capture;print;screenshot;
Keywords[bn_IN]=স্ন্যাপশট;ক্যাপচার;প্রিন্ট;স্ক্রিনশট;
Keywords[bs]=snimi, uslikaj, ispiši, slikaj ekran;
Keywords[ca]=instantània;captura;imprimeix;captura;
Keywords[ca@valencia]=instantània;captura;imprimeix;captura;
Keywords[cs]=snímek;zachytit;otisk;obrazovka;
Keywords[da]=billede;øjebliksbillede;indfang;print;skærmbillede;
Keywords[de]=Schnappschuss;Aufnahme;Druck;Bildschirmfoto;
Keywords[el]=στιγμιότυπο;λήψη;εκτύπωση;στιγμιότυπο οθόνης;snapshot;capture;print;screenshot;
Keywords[eo]=ekkapti;ekrankopiilo;ekrankopio;ekranpresaĵo;kapti;presi;
Keywords[es]=pantallazo;capturar;imprimir;
Keywords[eu]=argazkia;kaptura;inprimatu;pantaila-argazkia;
Keywords[fa]=snapshot;capture;print;گرفتن;چاپ;عکس‌صفحه;
Keywords[fi]=snapshot;capture;print;screenshot;kuvakaappaus;kuvankaappaus;ruutukaappaus;kaappaa;tuloste;näyttökaappaus;
Keywords[fr]=cliché;capture;impression;capture d'écran;
Keywords[gd]=snapshot;capture;print;screenshot;glacadh;clò-bhualadh;glacadh-sgrìn;
Keywords[gl]=captura de pantalla;captura;imprimir;
Keywords[gu]=સ્નેપશોટ; કેપ્ચર; પ્રિન્ટ; સ્ક્રીનશોટ;
Keywords[he]=צילום;לכידה;מסך;הדפסה;הדפסה;תצלום;תמונה;
Keywords[hi]=snapshot;capture;print;screenshot;
Keywords[hu]=pillanatkép;rögzítés;nyomtatás;képernyőkép;
Keywords[id]=snapshot;tangkapan;cetak;cuplikan layar;
Keywords[is]=myndataka;skot;prent;skjámynd;
Keywords[it]=schermata;schermate;cattura;stampa;screenshot;snapshot;
Keywords[ja]=snapshot;capture;print;screenshot;スナップショット;キャプチャー;プリント;スクリーンショット;
Keywords[kk]=скриншот;баспа;ұстау;
Keywords[km]=រូបថត​អេក្រង់;ចាប់​យក;បោះពុម្ព;រូបថត​អេក្រង់;
Keywords[kn]=ಸ್ನ್ಯಾಪ್‌ಶಾಟ್;ಸೆರೆಹಿಡಿಯುವಿಕೆ;ಮುದ್ರಣ;ತೆರೆಚಿತ್ರ;
Keywords[ko]=snapshot;스냅샷;capture;화면;캡쳐;print;인쇄;screenshot;스크린샷;
Keywords[lt]=ekranvaizdis;nufotografuoti;spausdinti;momentinėkopija;
Keywords[lv]=uzņēmums;tvērums;šāviņš;tvert;ekrānattēls;
Keywords[mr]=स्नॅपशॉट;कॅपचर;प्रिंट;स्क्रीनशॉट;
Keywords[nb]=skjermbilde;opptak;utskrift;skjermdump;
Keywords[nl]=momentopname;vastleggen;afdrukken;schermafdruk;
Keywords[or]=ଆଶୁଚିତ୍ର;ଧାରଣ;ମୁଦ୍ରଣ;ପରଦା ପ୍ରତିଛବି;
Keywords[pa]=ਤਸਵੀਰ;ਸਨੈਪਸ਼ਾਟ;ਕੈਪਚਰ;ਪਰਿੰਟ;snapshot;capture;print;screenshot;ਸਕਰੀਨਸ਼ਾਟ;
Keywords[pl]=zrzut ekranu;migawka;przechwycenie;przechwyć;pobieranie;pobierz;druk;drukowanie;wydrukowanie;
Keywords[pt]=captura;ecrã;impressão;captura de ecrã;
Keywords[pt_BR]=captura de tela;captura;capturar;screenshot;
Keywords[ro]=snapshot;capture;print;screenshot;captură;
Keywords[ru]=снимок;захват;печать;скриншот;
Keywords[sk]=snímka;zachytenie;tlač;snímka obrazovky;
Keywords[sl]=zajemanje;zajeto;zajem;natisni;zaslonska slika;
Keywords[sr]=снимак;сними;штампај;снимак екрана;
Keywords[sr@latin]=snimak;snimi;štampaj;snimak ekrana;
Keywords[sv]=fånga;skärmbild;screenshot;
Keywords[ta]=snapshot;capture;print;screenshot;
Keywords[te]=snapshot;capture;print;screenshot;
Keywords[tg]=акс;экран;чоп;тасвир;
Keywords[th]=ภาพหน้าจอ;จับภาพ;พิมพ์;จับภาพหน้าจอ;
Keywords[tr]=enstantane;yakala;yazdır;ekran görüntüsü;
Keywords[uk]=знімок;захоплення;екран;надрукувати;
Keywords[vi]=snapshot;capture;print;screenshot;chụp;màn;hình;chup;man;hinh;in;
Keywords[zh_CN]=snapshot;capture;print;截图;抓屏;截屏;捕获;打印;
Keywords[zh_HK]=snapshot;capture;print;screenshot;螢幕擷圖;擷取;列印;
Keywords[zh_TW]=snapshot;capture;print;screenshot;螢幕擷圖;擷取;列印;
Exec=gnome-screenshot --interactive
Terminal=false
Type=Application
Icon=applets-screenshooter
StartupNotify=true
Categories=GTK;GNOME;Utility;X-GNOME-Utilities;X-SuSE-DesktopUtility;
OnlyShowIn=GNOME;
X-GNOME-Bugzilla-Bugzilla=GNOME
X-GNOME-Bugzilla-Product=gnome-utils
X-GNOME-Bugzilla-Component=screenshot
Actions=screen-shot;window-shot;
DBusActivatable=true

[Desktop Action screen-shot]
Name=Take a Screenshot of the Whole Screen
Exec=gnome-screenshot

[Desktop Action window-shot]
Name=Take a Screenshot of the Current Window
Exec=gnome-screenshot -w
`````````````````````````````````````````````````

**Comment by City-busz** [comment] 2016-01-06 01:32
This is a missing feature, org.gnome.Shell.Screenshot DBus interface is not implemented yet. (https://github.com/solus-project/budgie-desktop/issues/261)

**Comment by Justinzobel** [comment] 2016-01-06 22:33
Run from terminal gnome-screenshot -i to get the interface as a workaround until #261 is completed.

**Comment by ikeydoherty** [comment] 2016-01-24 12:37
Closing as a dupe of #261

**Closed by ikeydoherty** 2016-01-24 12:37 UTC

**Comment by Iqop** [comment] 2016-06-28 13:05
I did this in budgie-remix (unofficial ubuntu flavor with budgie desktop as standard)

1 - In terminal typed `sudo apt-get install xbindkeys` to install xbindkeys

2 - next run `xbindkeys --defaults >  ~/.xbindkeysrc`  to create a file xbinkeys config file

3 - In settings removed the printscreen shortcut on settings > keyboard > shortcuts

![captura de ecra de 2016-06-28 13-39-01](https://cloud.githubusercontent.com/assets/16672692/16415546/b641e7a2-3d35-11e6-9685-c6ea7af1923d.png)

4 -  In terminal typed `nano ~/.xbinkeysrc` and in the last line added: 

> "gnome-screenshot"
>          Mod2 + Print

Hope it helps
