### ISSUE TITLE
Raven panel doesn't have a fixed width

### ISSUE THREAD

**Issue by hfel** [solus-project/budgie-desktop#1468] opened 2018-06-03 16:25 UTC
Hello!

On my computer Raven panel's width changes depending on the length of the notification status text, which makes it feel inconsistent, especially when dismissing notifications as the width just jumps. It would be nice if it had a fixed width at the longest notification status text. It's not easily visible on the screenshots, but the jump is easily discernible when dismissing the notifications.

![raven-short](https://user-images.githubusercontent.com/16854594/40888689-1ef51caa-675b-11e8-8d39-421c3c136083.png)

![raven-long](https://user-images.githubusercontent.com/16854594/40888693-27b75790-675b-11e8-807a-ce97f7494a65.png)

**Comment by JoshStrobl** [comment] 2018-06-04 07:34
More-or-less a duplicate of #1187

**Closed by JoshStrobl** 2018-06-04 07:34 UTC
