### ISSUE TITLE
Budgie Panel on Both Monitors

### ISSUE THREAD

**Issue by itz63c** [solus-project/budgie-desktop#1827] opened 2019-05-27 22:05 UTC
### Current Budgie version 
10.5

### Use-cases
I really enjoy the feel and fluidity of budgie but i miss being able to clone the panel to both monitors like on GNOME3

**Comment by JoshStrobl** [comment] 2019-05-28 09:56
Duplicate of #436

**Closed by JoshStrobl** 2019-05-28 09:56 UTC
