### ISSUE TITLE
Clock applet moves horizontally when seconds are displayed

### ISSUE THREAD

**Issue by thefiercerabbit** [solus-project/budgie-desktop#1838] opened 2019-06-19 20:48 UTC
## Description
When seconds are displayed in the clock applet (right aligned and on the most right position of the panel) the applet moves horizontally (few pixels), almost every seconds. This also shifts every applet that is right aligned, but on the left of the clock applet.

## Budgie version
budgie-desktop 10.5 (git-38b69f05619f0b1a681276dc258929f2fcb7a750)

## Operating system
Linux manjaro 4.19.49-1-MANJARO #1 SMP PREEMPT Sun Jun 9 20:24:20 UTC 2019 x86_64 GNU/Linux

## Steps to reproduce the issue
Add a clock applet to an (horizontal) panel, and move the clock applet to the most right position. Show the seconds, and eventually add other apples, right aligned, on the left of the clock.

## Quick dirty but doable fix
Use a monospace font.

**Comment by JoshStrobl** [comment] 2019-06-20 08:04
Duplicate of #1527

**Closed by JoshStrobl** 2019-06-20 08:04 UTC
