### ISSUE TITLE
The input method (IBus) does not appear in the Keyboard Layout Indicator

### ISSUE THREAD

**Issue by quycao** [solus-project/budgie-desktop#1823] opened 2019-05-17 11:11 UTC
## Description

I updated budgie-desktop 10.5 and see the Keyboard Layout Indicator don't show input method of IBus (in my case is ibus-unikey). Note that I can use Super + Space to change Input Method and use it nomally, it just don't show in Keyboard Layout Indicator.

- Region & Language setting
![image](https://user-images.githubusercontent.com/20070323/57923332-3aff9280-78cc-11e9-9864-49b44e909f60.png)

- Keyboard Layout indicator (only xkb - US, UK appear, ibus - Unikey don't appear)
![image](https://user-images.githubusercontent.com/20070323/57924891-9895de00-78d0-11e9-996a-50482c651993.png)

## Budgie version

admin@solus /usr $ budgie-desktop --version
budgie-desktop 10.5 (git-48d1bc4bf4bf9ba9e88860e9526f147e415cb8be)
Copyright © 2014-2019 Budgie Desktop Developers

## Operating system

admin@solus /usr $ uname -a
Linux solus 5.0.12-115.current #1 SMP PREEMPT Sun May 5 17:42:46 UTC 2019 x86_64 GNU/Linux

## Steps to reproduce the issue

I follow this document: https://getsol.us/articles/configuration/configuring-keyboard-layout/en/

1. Install ibus-unikey and run it

2. Add keyboard layout - Vietnamese (Unikey)
![image](https://user-images.githubusercontent.com/20070323/57923332-3aff9280-78cc-11e9-9864-49b44e909f60.png)

3. Just look in Keyboard Layout Indicator to check

## Actual result

![image](https://user-images.githubusercontent.com/20070323/57924870-8b78ef00-78d0-11e9-8e15-7767ff954516.png)

## Expected result
Below is expected for IBus hangul (Korean), it should be same for IBus-Unikey in my issue
![image](https://user-images.githubusercontent.com/20070323/57924945-c3803200-78d0-11e9-8d4a-0b298ad4a085.png)

## Additional information
Related issue: https://github.com/solus-project/budgie-desktop/issues/664

Below is some information of my environment

admin@solus /usr $ gsettings get org.gnome.desktop.input-sources sources
[('xkb', 'us'), ('ibus', 'Unikey'), ('xkb', 'gb')]

admin@solus /usr $ ibus list-engine
language: Dutch
  xkb:be::nld - Belgian
language: Hungarian
  xkb:hu::hun - Hungarian
language: Polish
  xkb:pl:dvorak:pol - Polish (Dvorak)
  xkb:pl:qwertz:pol - Polish (qwertz)
  xkb:pl::pol - Polish
language: Latvian
  xkb:lv:apostrophe:lav - Latvian (apostrophe variant)
language: Estonian
  xkb:ee::est - Estonian
language: Finnish
  xkb:fi::fin - Finnish
language: Serbian
  xkb:rs::srp - Serbian
language: English
  xkb:us:intl:eng - English (US, international with dead keys)
  xkb:gb:extd:eng - English (UK, extended WinKeys)
  xkb:ca:eng:eng - English (Canada)
  xkb:us:altgr-intl:eng - English (international AltGr dead keys)
  xkb:us:colemak:eng - English (Colemak)
  xkb:us:dvorak:eng - English (Dvorak)
  xkb:us::eng - English (US)
  xkb:gb:dvorak:eng - English (UK, Dvorak)
language: Czech
  xkb:cz:qwerty:cze - Czech (qwerty)
  xkb:cz::cze - Czech
language: Turkish
  xkb:tr::tur - Turkish
language: Slovenian
  xkb:si::slv - Slovenian
language: Italian
  xkb:it::ita - Italian
language: Arabic
  xkb:ara::ara - Arabic
language: Spanish
  xkb:latam::spa - Spanish (Latin American)
  xkb:es::spa - Spanish
language: Bulgarian
  xkb:bg::bul - Bulgarian
  xkb:bg:phonetic:bul - Bulgarian (traditional phonetic)
language: Catalan
  xkb:es:cat:cat - Catalan (Spain, with middle-dot L)
language: Lithuanian
  xkb:lt::lit - Lithuanian
language: Slovak
  xkb:sk:qwerty:slo - Slovak (qwerty)
  xkb:sk::slo - Slovak
language: Swedish
  xkb:se:svdvorak:swe - Swedish (Svdvorak)
  xkb:se:dvorak:swe - Swedish (Dvorak)
  xkb:se::swe - Swedish
language: Norwegian
  xkb:no:dvorak:nor - Norwegian (Dvorak)
  xkb:no::nor - Norwegian
language: Danish
  xkb:dk::dan - Danish
language: Ukrainian
  xkb:ua::ukr - Ukrainian
language: French
  xkb:fr:oss:fra - French (alternative)
  xkb:fr:bepo:fra - French (Bepo, ergonomic, Dvorak way)
  xkb:ch:fr:fra - French (Switzerland)
  xkb:fr:dvorak:fra - French (Dvorak)
  xkb:ca::fra - French (Canada)
  xkb:fr::fra - French
  xkb:be::fra - Belgian
language: Greek, Modern (1453-)
  xkb:gr::gre - Greek
language: Russian
  xkb:ru::rus - Russian
  xkb:ru:phonetic:rus - Russian (phonetic)
language: Mongolian
  xkb:mn::mon - Mongolian
language: Croatian
  xkb:hr::hr - Croatian
language: Romanian
  xkb:ro::rum - Romanian
language: Portuguese
  xkb:br:dvorak:por - Portuguese (Brazil, Dvorak)
  xkb:pt::por - Portuguese
  xkb:br::por - Portuguese (Brazil)
language: Malay (macrolanguage)
  xkb:my::msa - Malay (Jawi)
language: German
  xkb:de:nodeadkeys:ger - German (eliminate dead keys)
  xkb:de::ger - German
  xkb:be::ger - Belgian
  xkb:de:neo:ger - German (Neo 2)
  xkb:de:dvorak:ger - German (Dvorak)
  xkb:ch::ger - German (Switzerland)
language: Japanese
  xkb:jp::jpn - Japanese
language: Uzbek
  xkb:uz:cyrillic:uzb - Uzbek Cyrillic
  xkb:uz:latin:uzb - Uzbek Latin
  xkb:uz::uzb - Uzbek
language: Vietnamese
  Unikey - Unikey
language: Hebrew
  xkb:il::heb - Hebrew

admin@solus /usr $ ibus engine
xkb:us::eng

admin@solus /usr $ budgie-desktop --version
budgie-desktop 10.5 (git-48d1bc4bf4bf9ba9e88860e9526f147e415cb8be)
Copyright © 2014-2019 Budgie Desktop Developers

admin@solus /usr $ uname -a
Linux solus 5.0.12-115.current #1 SMP PREEMPT Sun May 5 17:42:46 UTC 2019 x86_64 GNU/Linux

**Comment by fossfreedom** [comment] 2019-06-22 08:35
This is a duplicate of https://github.com/solus-project/budgie-desktop/issues/1785

**Closed** 2020-10-09 13:37 UTC
