### ISSUE TITLE
Budgie menu freezes when search buffer is overfilled.

### ISSUE THREAD

**Issue by blackomegax** [solus-project/budgie-desktop#1105] opened 2017-08-17 00:59 UTC
**Operating System**: Solus 3

When filling the search bar in menu with excess data, menu hard freezes and requires reboot.

 ...

**Steps to reproduce the issue**
copy aaaaaaaaaaaaaaaaaaaaaaaa to clipboard
launch menu
hold ctrl-v down and let paste loop until freeze.

 ...

**Comment by blackomegax** [comment] 2017-08-17 01:00
Preferred fix:
Buffer limit at ~256 char input should fix

**Comment by JoshStrobl** [comment] 2020-10-09 10:30
Closing, unable to reproduce issue.

**Closed by JoshStrobl** 2020-10-09 10:30 UTC
