### ISSUE TITLE
Ravenscar notification titles are truncated to one line in an awkward way

### ISSUE THREAD

**Issue by Jkillelea** [solus-project/budgie-desktop#1502] opened 2018-07-13 17:36 UTC
**Operating System**: Antergos (Arch) Linux

**Budgie version**: Budgie v10.4.-34-gd6f3519f

**The issue encountered**

Notification titles can be awkwardly truncated by removing the first N letters such that they fit on one line. The first letters cannot be viewed by attempting to interact with the notification. One would expect the last letters to be truncated, not the first.

**Steps to reproduce the issue**

Have a notification appear that is over the character limit. The image below should say something like "Scheduled backup delay..." and show the full text when the notification is clicked on or "Scheduled backup \<newline\> delayed".

![notification](https://user-images.githubusercontent.com/5292786/42705556-8b8389f0-8688-11e8-8646-4a79e6f02d58.png)

**Comment by JoshStrobl** [comment] 2018-07-16 22:48
Duplicate of #1154

**Closed by JoshStrobl** 2018-07-16 22:48 UTC
