### ISSUE TITLE
Pressing "window" key should reveal hidden top panel.

### ISSUE THREAD

**Issue by amcmills** [solus-project/budgie-desktop#1833] opened 2019-06-08 13:57 UTC
### Use-cases
It's handy to be able to check time without having to move mouse cursor to top edge of screen.

**Comment by desigit** [comment] 2019-06-09 18:00
Yes, second that, been looking for that feature, or, preferably, a "budgie-panel --toggle/show/hide" command line option that will reveal/hide the panel, and which you can bind to a hotkey. 

As a temporary very ugly hack, you can link a keyboard hotkey with an activatepanel.sh script that moves the mouse cursor to the top right (or wherever your panel is), and moves it a few pixels down when it's already in the top left:

`#!bin/bash
MOUSEY=$(xdotool getmouselocation | awk '{print $2}')
if [ $MOUSEY = "y:0" ]; then
    xdotool mousemove_relative 0 100
else
    xdotool mousemove 3000 0
fi;`

**Comment by JacekJagosz** [comment] 2019-06-14 12:10
Also it is really helpful when you have a fullscreen app or game, and you want to minimize it or switch to to other app.
This is a feature I really miss from Windows

**Comment by desigit** [comment] 2019-06-14 15:10
One other alternative, which is less hacky (but also doesn't work with fullscreen apps, I think), is to use the hotkey that opens / toggles the notifications / Raven sidebar (or you can rebind those hotkeys in dconf). In my system this also reveals the autohide panel.

**Comment by JoshStrobl** [comment] 2020-10-09 16:15
Duplicate of #1670

**Closed by JoshStrobl** 2020-10-09 16:15 UTC
