### ISSUE TITLE
"Save as" screen is obscured by top bar

### ISSUE THREAD

**Issue by Bruce-McL** [solus-project/budgie-desktop#1899] opened 2019-11-11 19:38 UTC
This happens when:
Hide top bar is set to automatic or intelligent.
Top bar size set to 54.
Attach Modal Dialogs to Windows is off, as are all other Windows options.

Quit and reopen text editor.
Make text editor full screen.
Select "Save as"
The top of the save as sheet will be underneath the top bar. Typing a filename and pressing "Save" will be impossible.

Solus Budgie, current version.

**Comment by JoshStrobl** [comment] 2019-11-12 12:23
Duplicate of #869

**Closed by JoshStrobl** 2019-11-12 12:23 UTC
