### ISSUE TITLE
windows button olny open dropdown menu but it doesn't close it

### ISSUE THREAD

**Issue by DracotMolver** [solus-project/budgie-desktop#423] opened 2016-04-23 15:48 UTC
When I press down the window button, it's open the menu dropdown. But when I press it down again, it doesn't close the menu, I can only do it clicking out side of the menu or just pressing down window+the bar space.

**Comment by theSoenke** [comment] 2016-04-23 15:52
Don't know whether it's related but pressing the superkey sometimes also does not close the menu

**Comment by DracotMolver** [comment] 2016-04-23 16:09
I have the same behavior, closing the menu, just doing window + any key.

**Comment by ikeydoherty** [comment] 2016-04-24 06:46
Works here. Please provide more information on your setup.

**Comment by ikeydoherty** [comment] 2016-04-24 06:47
@ both of you

**Comment by theSoenke** [comment] 2016-04-24 14:42
I'm using budgie v10.2.5 on arch. Also tested it on my notebook and was not able to reproduce it there

**Comment by DracotMolver** [comment] 2016-04-24 20:08
Sorry guys. Well I'm using fedora 23, I installed budgie-desktop-10.2.5-2.1.

**Comment by ikeydoherty** [comment] 2016-05-24 06:03
I believe this to be fixed in git. (I'm spamming the buhjesus out of my windows key and it works)
When the next release comes out, if this is still an issue, please re-open :)

**Closed by ikeydoherty** 2016-05-24 06:03 UTC

**Comment by euoar** [comment] 2017-01-30 12:54
I'm having this issue now. Could this be reopened? And also the budgie menu won't open with windows key unless no other application is started...

**Comment by fossfreedom** [comment] 2017-01-30 14:09
@euoar probably better to create a new issue - this was closed against an earlier version of budgie - your issue is probably either distro specific or a later version of budgie.
