### ISSUE TITLE
Panel doesn't resize with icons

### ISSUE THREAD

**Issue by hfel** [solus-project/budgie-desktop#1398] opened 2018-04-30 18:18 UTC
**Operating System**: Solus 3.9995
**Budgie version**: Budgie v10.4-55-g995e85e5

**The issue encountered**

The panel doesn't resize together with the icons below a certain size. When increasing the icon size above 50, the panel size _does_ increase accordingly however.
![panel](https://user-images.githubusercontent.com/16854594/39443005-819b3406-4cb3-11e8-816e-b0d32d48cc6a.png)

**Steps to reproduce the issue**

Changing the panel size from Budgie Settings.

**Comment by JoshStrobl** [comment] 2018-09-27 07:51
Duplicate of #701

**Closed by JoshStrobl** 2018-09-27 07:51 UTC
