### ISSUE TITLE
hangouts not minimizing on-click

### ISSUE THREAD

**Issue by bsucker98** [solus-project/budgie-desktop#1492] opened 2018-07-02 13:18 UTC
**Operating System**: Solus 3
**Budgie version**: budgie-desktop v10.4-85

**The issue encountered**

hangouts (chrome app) not minimizing on-click on the icon, but restoring on-click works fine. 
other chrome apps behave properly.

**Steps to reproduce the issue**

open hangouts then click-on the icon

**Comment by JoshStrobl** [comment] 2018-07-03 02:58
Duplicate of #1425

**Closed by JoshStrobl** 2018-07-03 02:58 UTC
