### ISSUE TITLE
Task List overflows onto other panel applets with many windows open

### ISSUE THREAD

**Issue by tjgordon** [solus-project/budgie-desktop#485] opened 2016-06-29 21:13 UTC
The Task List panel applet does not decrease the size of window buttons to prevent overflow onto other applets:

![screenshot_2016-06-29_13-38-06](https://cloud.githubusercontent.com/assets/7094859/16468809/89181e9a-3e02-11e6-82a9-c3e05404582c.png)

This makes the notification area and the window button harder to read and access. 

Compare this behavior to XFCE's equivalent Window Buttons applet, which does decrease the window button size:

![screenshot_2016-06-29_14-01-17](https://cloud.githubusercontent.com/assets/7094859/16468807/85d00a2c-3e02-11e6-9490-c05ddae50b07.png)

Budgie Desktop 10.2.5-2.1 on Fedora 24.

**Comment by ikeydoherty** [comment] 2016-06-29 21:32
Duplicate of #83

**Closed by ikeydoherty** 2016-06-29 21:32 UTC
