### ISSUE TITLE
Bottom Panel Icons Mess

### ISSUE THREAD

**Issue by thumos333** [solus-project/budgie-desktop#1842] opened 2019-06-26 19:19 UTC
Hello,

After one of the recent updates, some of the bottom panel icons overlap with others. Please see the screenshot. I tried shuffling them back and forth but to no avail.

I am using Budgie 10.5-198 on Solus 4.0, fully updated.

Thanks.

![Screenshot from 2019-06-26 22:11:00](https://user-images.githubusercontent.com/29035180/60208225-688f1280-9860-11e9-88ba-30bdc4c564d2.png)

**Comment by KevinOberle** [comment] 2019-08-22 04:36
Specifically this only applies to the icons in the system tray applet. Here's another screenshot.
![Screenshot from 2019-08-21 22-34-16](https://user-images.githubusercontent.com/16871613/63486239-ea1baf00-c463-11e9-9f36-658b38e10ede.png)

**Comment by fossfreedom** [comment] 2019-08-22 08:57
looks to be a duplicate of this issue https://github.com/solus-project/budgie-desktop/issues/1296

**Closed** 2019-08-22 12:26 UTC
