### ISSUE TITLE
Scale Panel Icons

### ISSUE THREAD

**Issue by hersh-verthun** [solus-project/budgie-desktop#1853] opened 2019-07-22 12:04 UTC
### Current Budgie version

10.5

### Use-cases
Improve usability and appearance of the Budgie-Panel.

### Proposal
Space between the icons in the notification-tray should increase / decrease with the panel size.
The icons in the notification-tray should scale with the panel size. You can notice how they are disproportionate in the screenshot below, where I scaled the panel to 64.

Also look at the elementary-os panel screenshot further below for comparison.

![Screenshot from 2019-07-22 17:29:37](https://user-images.githubusercontent.com/22866232/61631289-9fade380-aca7-11e9-8b44-6ed61db8a7b4.png)

![](https://pre00.deviantart.net/6c6f/th/pre/f/2017/232/8/1/my_remix_04___icon_theme_for_elementary_os_by_wefunkster-dbi3l4q.png)

**Comment by JoshStrobl** [comment] 2019-07-22 13:52
Duplicate of #896

**Closed by JoshStrobl** 2019-07-22 13:52 UTC
