### ISSUE TITLE
Repeted Entries In Menu

### ISSUE THREAD

**Issue by sahilarora3117** [solus-project/budgie-desktop#1577] opened 2018-09-24 07:26 UTC
**Operating System**: Solus 3.9999
**Budgie version**: v10.4-85-g36667bcb

**The issue encountered**
Application like Telegram and Steam makes multiple menu entries.

**Steps to reproduce the issue**
While installing form the default repositories, this issue persist

![screenshot from 2018-09-24 12-52-22](https://user-images.githubusercontent.com/20626166/45940876-2c8cff80-bff9-11e8-8648-ff281543dfae.png)
.

**Comment by JoshStrobl** [comment] 2018-09-24 14:11
Duplicate of #1327

**Closed by JoshStrobl** 2018-09-24 14:11 UTC
