### ISSUE TITLE
Nautilus or raven wont launch from Budgie pannel

### ISSUE THREAD

**Issue by joshontech** [solus-project/budgie-desktop#1890] opened 2019-10-20 16:00 UTC
## Description
 When clicking on the icons on budgie panel for nautilus or raven neither will come up. I also cannot do anything from the power menu on the panel as well. Only way I could find to resolve is to open terminal and restart the system. Nautilus also works from terminal if opened that way

## Budgie version
budgie-desktop 10.5.1

## Operating system
Solus 4 

## Steps to reproduce the issue
 It happens once and a while but have not found out what exactly causes the issue. Once the issue is apparent there is no way to correct other than rebooting.

**Comment by JoshStrobl** [comment] 2019-10-31 09:23
Since I'm not able to reproduce this, could I get a dconf dump of your Budgie Desktop settings so I can see if it is an issue with a specific configuration?

**Process:**

`dconf dump /com/solus-project/ > budgie-settings.ini` then drag & drop the ini file here (don't copy paste the contents).

Thanks!

**Comment by cet1** [comment] 2019-10-31 12:05
I do not have the problem since I uninstalled the virtualbox guest additions.


[budgie-settings.txt](https://github.com/solus-project/budgie-desktop/files/3793638/budgie-settings.txt)

**Comment by cet1** [comment] 2019-10-31 12:35
Just before uninstalling  virtualbox guest additions and getting rid of the bug  I was only able to use the PC by doing this command: nohup budgie-panel --replace&  
Today in the  Home section I found this nohup.out file  Maybe this can be of help.
[nohup.txt](https://github.com/solus-project/budgie-desktop/files/3793749/nohup.txt)

**Comment by joshontech** [comment] 2019-11-01 23:44
I am not using it in a VM. I don't have access to the laptop at this time to get a dconf bump yet but as soon as I can I will. I had another budgie user on the telegram group confirm the same issue as I am having at least so it's not just my setup.

**Comment by ivicakuk** [comment] 2019-11-02 18:40
i have same problem
[budgie-settings.txt](https://github.com/solus-project/budgie-desktop/files/3800829/budgie-settings.txt)
[nohup.txt](https://github.com/solus-project/budgie-desktop/files/3800831/nohup.txt)

**Comment by Bruce-McL** [comment] 2019-11-02 21:22
I'm experiencing the same problem.

[budgie-settings.txt](https://github.com/solus-project/budgie-desktop/files/3800951/budgie-settings.txt)

**Comment by joshontech** [comment] 2019-11-04 05:59
Hope this helps I am still having the issue. I can open nautilus from terminal even though I cannot launch from budgie panel.

[budgie-settings.txt](https://github.com/solus-project/budgie-desktop/files/3802781/budgie-settings.txt)

**Comment by JoshStrobl** [comment] 2019-11-04 06:46
For those having issues specifically with Nautilus, try checking if it is an issue with tracker timeouts by nuking `.cache/tracker` and restarting.

**Comment by joshontech** [comment] 2019-11-04 19:40
Tracker was an issue on Solus Gnome for me when I had files over 1gb in size in my downloads folder. I do not have any files that large in any folder on my laptop running budgie and when Tracker was killing my system the entire computer froze not just the budgie panel. To clarify the budgie panel is not freezing. I can click on anything on the panel and the click is recognized but once the click is recognized nothing further happens other than the animation of clicking. Raven notifications wont pop out of the right side and the power options popup comes up but when clicking on restart, shutdown, or anything in that menu nothing other than the animation of clicking happens.

I hope this is helping. Thanks Josh!

**Comment by nathanpainchaud** [comment] 2019-11-05 22:19
I experience the same problems that @joshontech mentions. Rebooting always fixes the issue, but only temporarily (the problem happens once or twice a day on average). I can also fix the issue without rebooting by running `nohup budgie-panel --replace&`, but in that case the panel will behave a bit funny until a proper reboot (e.g. I have the panel on auto-hide, and the system tray will only appear every other time I make the panel pop up...). I've attached the dump of the settings in case it helps in any way.

Thanks for the great support!

[budgie-settings.txt](https://github.com/solus-project/budgie-desktop/files/3811529/budgie-settings.txt)

**Comment by JoshStrobl** [comment] 2019-11-06 05:20
Hey there, for whatever reason my dconf command was not dumping specific applet settings, could people the`txt` files provided by running `conf dump /com/solus-project/budgie-panel/instance/ > budgie-applet-instances.txt`. The intent of this is so I can create a similar user configuration as someone affected by this issue.

Thanks for the nohup.txt files as well (which btw, you don't need nohup to restart budgie-panel, you can just do `budgie-panel --replace &!` from a Terminal then do `Ctrl+D` to detach from that process), I'm seeing some Wnck-Criticals but those shouldn't be fatal to Budgie. I'll see about cleaning up some of those hash table contains glib "critical" assertion errors in the meantime and look into adding some debugging so Solus users can help provide some further details.

**Comment by joshontech** [comment] 2019-11-06 17:40
I am going to install Ubuntu budgie 19.10 I want to see if this issue is happening on budgie there as well. I am also going to install Solus Budgie on gnome boxes and see if the issue persists.

**Comment by JoshStrobl** [comment] 2019-11-08 06:53
Seeming some issues locally around clutter (used in Mutter, which Budgie WM uses for its Window Manager), namely around event queuing, that was preventing popovers from working or keyboard events from getting passed into windows:

```
Nov 08 08:45:56 goliath budgie-wm[2013]: _clutter_stage_queue_event: assertion 'CLUTTER_IS_STAGE (stage)' failed
Nov 08 08:45:56 goliath budgie-wm[2013]: _clutter_stage_queue_event: assertion 'CLUTTER_IS_STAGE (stage)' failed
Nov 08 08:45:56 goliath budgie-wm[2013]: _clutter_stage_queue_event: assertion 'CLUTTER_IS_STAGE (stage)' failed
Nov 08 08:45:56 goliath budgie-wm[2013]: _clutter_stage_queue_event: assertion 'CLUTTER_IS_STAGE (stage)' failed
Nov 08 08:45:56 goliath budgie-wm[2013]: _clutter_stage_queue_event: assertion 'CLUTTER_IS_STAGE (stage)' failed
Nov 08 08:45:56 goliath budgie-wm[2013]: _clutter_stage_queue_event: assertion 'CLUTTER_IS_STAGE (stage)' failed
Nov 08 08:45:56 goliath budgie-wm[2013]: _clutter_stage_queue_event: assertion 'CLUTTER_IS_STAGE (stage)' failed
Nov 08 08:45:56 goliath budgie-wm[2013]: _clutter_stage_queue_event: assertion 'CLUTTER_IS_STAGE (stage)' failed
Nov 08 08:45:56 goliath budgie-wm[2013]: _clutter_stage_queue_event: assertion 'CLUTTER_IS_STAGE (stage)' failed
Nov 08 08:45:56 goliath budgie-wm[2013]: _clutter_stage_queue_event: assertion 'CLUTTER_IS_STAGE (stage)' failed
Nov 08 08:45:56 goliath budgie-wm[2013]: _clutter_stage_queue_event: assertion 'CLUTTER_IS_STAGE (stage)' failed
Nov 08 08:45:56 goliath budgie-wm[2013]: _clutter_stage_queue_event: assertion 'CLUTTER_IS_STAGE (stage)' failed
Nov 08 08:45:56 goliath budgie-wm[2013]: _clutter_stage_queue_event: assertion 'CLUTTER_IS_STAGE (stage)' failed
```

And lo' beyond, this was [fixed upstream](https://gitlab.gnome.org/GNOME/mutter/issues/750) in Mutter. Going to be syncing Solus' mutter patch with git and getting that in for today's sync, so please let me know after you receive those updates, have updated, etc. whether the issue continues to progress.

**Comment by ivicakuk** [comment] 2019-11-08 17:42
I was 5 days with no issue today it happened to me again.I saw today for me it happen when doing something in the background(youtube) and it goes into sleep mode.I'll make an update now.

**Comment by Bruce-McL** [comment] 2019-11-09 21:54
Installed the Solus Budgie updates on Friday, November 8.
Shut down my computer, started it up.
Experienced the Budgie Panel problem about 8 hours later.

[budgie-applet-instances.txt](https://github.com/solus-project/budgie-desktop/files/3827774/budgie-applet-instances.txt)

**Comment by nathanpainchaud** [comment] 2019-11-11 22:47
On my end, I haven't experienced any issues since last Friday's (November 8) sync. I didn't use my laptop as much during the weekend, but on I haven't had any problem on Monday either. In the past weeks, I would encounter the problem at least once a day (often twice). So it seems the Mutter patch did something on my end. I'll update if I encounter the problem again during the week.

**Comment by SolarLune** [comment] 2019-11-13 04:13
Hello, I am also having issues with the Budgie panel under Solus. Raven isn't opening from the right-hand button, icons are duplicating, and icons are disappearing and reappearing (see [this post](https://discuss.getsol.us/d/2949-applications-cannot-launch-from-panel/19) by Solarmass for what it looks like).

Here's my dump: [budgie-settings.txt](https://github.com/solus-project/budgie-desktop/files/3839389/budgie-settings.txt)

**Comment by Bruce-McL** [comment] 2019-11-16 18:28
Following up on a forum post by TaBe:

https://discuss.getsol.us/d/2949-applications-cannot-launch-from-panel/42

TaBe suggests two possible causes of this bug.

1. Icon Task List - I removed the Icon Task List from my Budgie Panel four days ago. Since then I have not had any freezing problems with Budgie Panel. Before the change I was having one or two incidents per day. I installed Plank to replace the functionality of Icon Task List.

Is anybody else experiencing this problem without running Icon Task List?

2. Workplace Switcher - I have always run Solus Budgie with one workplace and without Workplace Switcher present in Budgie Panel. As I said above, I experienced Budgie Panel freezing regularly before I removed Icon Task List.

While Plank gets the job done, I prefer Icon Task List. I am switching from Plank back to Icon Task List today.

**Comment by bsucker98** [comment] 2019-12-07 15:06
I'm too having the issue & interestingly while writing this, the issue is persisting. The worse thing is that even the Power menu doesn't work(the applet works, but clicking an option doesn't) sometimes & have to kill the session via terminal. Also I couldn't even open **Budgie Desktop Settings** which isn't in icon task list when the issue persist. I tried few other apps which aren't in icon task list and they worked. When the issue persist applets take time to respond, sometimes doesn't even work. Raven mostly doesn't work at all.

**Comment by bsucker98** [comment] 2019-12-10 11:08
I'm sceptical weather to open a new issue since it feels like this related to this issue....

UPDATE: This time nautilus won't open even via the terminal...it throws an error 
`nautilus: error while loading shared libraries: libicuuc.so.63: cannot open shared object file: No such file or directory`

Also I couldn't open several other apps as well unless via terminal(gedit, gnome-settings, calendar and most of the system apps including libreoffice)

**Comment by JoshStrobl** [comment] 2019-12-10 11:51
@bsucker98 Your issue is because of an incomplete upgrade of your local system, nothing to do with Budgie. As such, removed comment.

**Comment by ivicakuk** [comment] 2019-12-12 16:09
With nuking  .cache/tracker and all updates  I'm 30 days without a problem.

**Comment by Bruce-McL** [comment] 2019-12-20 04:22
It's been at least two weeks without a problem on my system.

**Comment by bsucker98** [comment] 2020-01-14 18:06
30 days without a problem :)...maybe it's the partial upgrade

**Comment by JoshStrobl** [comment] 2020-01-14 18:07
Going to go ahead and close this issue given the last few comments. Sounds indeed like it was an issue with partial system upgrades or various other non-Budgie-related software (e.g. Mutter, Tracker or Nautilus) being problematic.

**Closed by JoshStrobl** 2020-01-14 18:07 UTC
Labels: bug
