### ISSUE TITLE
Application-centric (grouped windows) task switching (like Plank, macOS, GNOME/Ubuntu)

### ISSUE THREAD

**Issue by RedBearAK** [solus-project/budgie-desktop#2126] opened 2021-04-16 09:36 UTC
### Current Budgie version
budgie-desktop 10.5.1

### Use-cases
I come from nearly two decades of macOS usage, after a decade of Windows/Linux. In macOS when switching between applications with Alt+Tab, you see only a single icon for each "application" regardless of how many windows are open within that "application", and every open window within that application is brought to the front when you switch to that application. After first finding this very strange, I soon realized that it was a very orderly way to manage task switching. The Alt+` (Alt+Grave) shortcut allows rapid switching of windows within a single application. This already exists in Budgie. 

GNOME by default has the same style of application-centric task switching, with Alt+Grave used to target only a single window if desired. Ubuntu Desktop by default uses window-centric task switching, but can be easily changed to application-centric by changing the keyboard shortcut for "Switch application" to Alt+Tab and disabling the shortcut for "Switch window". This changes the behavior of the Alt+Tab switcher to work like unmodified GNOME and macOS. 

### Proposal
GNOME already does it by default. Ubuntu can do it, as noted above. Plank Dock also behaves the same way. When you click on an icon on Plank, it brings forward all open windows (within that workspace) associated with that application icon, as a group. 

Suggested: Copy the Plank or GNOME functionality into the Budgie Alt+Tab switcher to implement application-centric task switching. 

### References
Run a distro with an unmodified version of GNOME such as Fedora 34 Beta GNOME. Open exactly two applications, such as the file manager and Firefox. Open several new windows in each application. Press Alt+Tab and see that the task switcher pop-up dialog only shows two icons, and will treat each set of application windows as a linked group when switching. 

This is not the same thing as simply grouping application windows into a single icon on the panel. This is about treating all windows of the same application (within the same workspace) as a linked group of windows when task switching with the Alt+Tab method.

**Comment by JoshStrobl** [comment] 2021-04-16 13:24
Duplicate of #1633. Use the search please.

**Closed by JoshStrobl** 2021-04-16 13:24 UTC

**Comment by RedBearAK** [comment] 2021-04-16 19:35
@JoshStrobl 

I examined issue #1633 several times before submitting my request. I do not believe you are correct that this is a duplicate. That issue appears to only be talking about the grouping of icons in the task switcher. This is more extensive than that.
