### ISSUE TITLE
Spotify freezes panel

### ISSUE THREAD

**Issue by theSoenke** [solus-project/budgie-desktop#344] opened 2016-02-23 20:56 UTC
When i launch Spotify it freezes the budgie panel. Also raven does not work anymore. It takes a few minutes until budgie becomes usable again. 
I'm using arch with the latest budgie 10.2.3

**Comment by streambinder** [comment] 2016-02-24 14:53
Can confirm.

**Comment by xolan** [comment] 2016-03-11 08:47
Same issue here. Also using Arch Linux.

```
> uname -a
Linux xolbook 4.4.3-1-ARCH #1 SMP PREEMPT Fri Feb 26 15:09:29 CET 2016 x86_64 GNU/Linux

> pacman -Q spotify budgie-desktop  
spotify 1.0.23.93-2
budgie-desktop 10.2.4-1
```

**Comment by saligrama** [comment] 2016-03-14 14:47
Same issue here with Arch Linux.

    % uname -a
    Linux mandelbrot 4.3.6-1-ck #1 SMP PREEMPT Fri Feb 19 20:05:29 EST 2016 x86_64 GNU/Linux
    % pacman -Q spotify budgie-desktop
    spotify 1.0.23.93-2
    budgie-desktop 10.2.4-1

**Comment by saligrama** [comment] 2016-03-20 14:11
Still having the same issue here with Arch. Latest `budgie-desktop 10.2.4-3` from AUR. However, it doesn't crash the desktop anymore; it just freezes until Spotify is closed and then I can use it normally.

**Comment by GabMus** [comment] 2016-04-01 15:10
Can confirm, using Arch, when Spotify is opened the panel completely freezes, when I close Spotify and wait a few seconds the panel responds again.
`~> uname -a
Linux Trinity-Zero 4.4.5-1-ARCH #1 SMP PREEMPT Thu Mar 10 07:38:19 CET 2016 x86_64 GNU/Linux
~> pacman -Q spotify budgie-desktop 
spotify 1.0.26.125-1
budgie-desktop 10.2.4-3`

**Comment by ikeydoherty** [comment] 2016-04-02 15:10
OK so this is a duplicate of #325 - closing *this* one but we'll deal with it in the other bug, working on it now

**Closed by ikeydoherty** 2016-04-02 15:10 UTC
