### ISSUE TITLE
Duplicative Steam menu entries and "Internet" categories on Solus

### ISSUE THREAD

**Issue by sirredbeard** [solus-project/budgie-desktop#1437] opened 2018-05-16 04:02 UTC
**Operating System**: Solus 3.9996
**Budgie version**:  10.4-70-g15c960cc

**The issue encountered**

After installing the Steam 1.0.0.54 package from the Solus repo two icons appear in the Budgie Menu, one called "Steam" and one called "Steam Linux Integration".

Is also creates a duplicate "Internet" category in which the two icons appear.

Telegram 1.2.17-85 also appears in the duplicate "Internet" category"

**Steps to reproduce the issue**

Install Steam 1.0.0.54 package on Solus 3.9996 with Budgie 10.4-70-g15c960cc.

![screenshot from 2018-05-15 23-56-04](https://user-images.githubusercontent.com/33820650/40095924-6cf9dd28-589c-11e8-8a9b-e1891cb1f00a.png)

![screenshot from 2018-05-16 00-06-55](https://user-images.githubusercontent.com/33820650/40096313-56a2ee78-589e-11e8-8581-899f79723095.png)

On the other hand, this may not be distinct to Budgie. This may in face be a solus-sc bug. This is MATE: 

![screenshot from 2018-05-16 00-14-11](https://user-images.githubusercontent.com/33820650/40096365-87027f16-589e-11e8-8b73-6b9ea03d39d3.png)

**Comment by sirredbeard** [comment] 2018-05-16 04:22
Cross-filed with Solus [bug reporter](https://dev.solus-project.com/T6401).

**Comment by Staudey** [comment] 2018-05-17 10:16
Interesting. Those icons only appear once for me. Same for the Internet category. But then again I installed them a long time ago. Maybe something changed, or I actually deleted the extra entries back in the day.

**Comment by JoshStrobl** [comment] 2018-05-24 23:29
Duplicate of #1327

**Closed by JoshStrobl** 2018-05-24 23:29 UTC
