### ISSUE TITLE
Screenshot button support

### ISSUE THREAD

**Issue by TheAifam5** [solus-project/budgie-desktop#510] opened 2016-07-25 07:59 UTC
PrtScn button doesn't work right now.

**Comment by fossfreedom** [comment] 2016-07-25 08:01
This is on the TODO list - https://github.com/solus-project/budgie-desktop/blob/master/TODO.md

**Comment by ikeydoherty** [comment] 2016-07-25 08:13
It's also a duplicate of #261

**Closed by ikeydoherty** 2016-07-25 08:13 UTC
