### ISSUE TITLE
Close, minimize, maximize buttons dissapear from some maximized windows when left layout is set

### ISSUE THREAD

**Issue by goghard** [solus-project/budgie-desktop#1641] opened 2018-12-06 21:19 UTC
**Operating System**: Solus 3.9999
**Budgie version**: 10.4-85-g36667bcb

**The issue encountered**:  Close, minimize, and maximize buttons disappear when I maximize windows that use Gnome Header Bar, after setting "Left button layout" in Budgie Desktop Settings.

**Steps to reproduce the issue**:
1. Select "Left button layout" in Budgie Desktop Settings
2. Maximize a window with Gnome Header Bar (e.g. Nautilus)
  

 ...

**Comment by JoshStrobl** [comment] 2018-12-06 22:10
Duplicate of #1531

**Closed by JoshStrobl** 2018-12-06 22:10 UTC

**Comment by goghard** [comment] 2018-12-06 22:37
@JoshStrobl Thanks for taking care of this so quickly. I would say that this is not the same problem described in #1531 though. That one is about customized button layouts that are not being saved, and this one is about buttons that disappear. 

This is a screenshot of Nautilus’ buttons, when the Left layout is selected:
![image](https://user-images.githubusercontent.com/5067371/49615920-08488a00-f97d-11e8-9279-6da4c4fae26a.png)

And this is what happens when the window is maximized:
![image](https://user-images.githubusercontent.com/5067371/49616033-65444000-f97d-11e8-8f67-174055f88c6c.png)

As you can see, there are no more windows buttons in the corner.

**Comment by JoshStrobl** [comment] 2018-12-07 00:31
It still is the same issue. The layout doesn't correctly apply, especially to windows which use CSD rather than server-side decorations.
