### ISSUE TITLE
 Budgie keyboard switcher applet issue between English (US) and Vietnamese (VI)

### ISSUE THREAD

**Issue by dinhnamhihi** [solus-project/budgie-desktop#1850] opened 2019-07-11 09:00 UTC
## Description
I have seen my bug similar to the PT (Portuguese) and this bug already fixed in latest update from Solus repository, but it don't work for VI (Vietnamese), i can change the input method by press Keyboard Shortcut Super + Space but nothing change in Keyboard Layout Applet, it show English (US) all the time. Of course I have already installed Ibus - Unikey package from repository and add it to Input Sources in Region and Language Setting, also add it in Ibus Preferences.
I don't know why this bug were fixed in PT (Portuguese) Language but not for VI (Vietnamese). So I hope Solus Developers will fix it as soon as possible in the upcoming update, I just installed Solus 4 yesterday alongside with Windows 10 and I really want Solus is my main OS for stable to use in the long term, I love the way Solus make the OS so simple, beautiful, elegance, fast, lightweight and personalize. Thank you very much to Solus Project for contributing to the world a good OS.
p/s: Sorry for my bad English

## Budgie version
budgie-desktop 10.5

## Operating system
 Solus 4

## Steps to reproduce the issue
Configure Ibus Preferences similar to Region and Language in Setting, plus enable 'Use system keyboard layout' in Advanced - Ibus Preferences, restart and the bug still appear

## Actual result
The bug not fix, Keyboard Layout Applet only show US all the time, not show VI. Can switch between 2 input method by keyboard shortcut but not by Keyboard Layout Applet Switcher
![1562775250-125921-img-20190710-231343](https://user-images.githubusercontent.com/52778932/61037141-aeb5ab80-a3f4-11e9-8dcf-4d75df0d127d.jpeg)
![1562775360-836093-img-20190710-231301](https://user-images.githubusercontent.com/52778932/61037142-af4e4200-a3f4-11e9-9232-4645684b3c04.jpeg)
![1562775446-123943-img-20190710-230715](https://user-images.githubusercontent.com/52778932/61037145-afe6d880-a3f4-11e9-9dd7-5d35761d417f.jpeg)
![Screenshot from 2019-07-11 15-36-41](https://user-images.githubusercontent.com/52778932/61037146-afe6d880-a3f4-11e9-915c-d3faeca245d4.png)

**Comment by JoshStrobl** [comment] 2019-07-11 13:24
Duplicate of #1823

**Closed by JoshStrobl** 2019-07-11 13:24 UTC
