### ISSUE TITLE
thumb drive eject notifications not popping up "can be removed"

### ISSUE THREAD

**Issue by splace** [solus-project/budgie-desktop#2101] opened 2021-02-02 02:16 UTC
## Budgie version
budgie-desktop 10.5.2

## Operating system
solus 3

## Steps to reproduce the issue
eject thumb drive

## Actual result
pop-up for "do not unplug"

## Expected result
pop-up "do not unplug"
followed by "can be removed"

## Additional information
notification was made just didn't pop-up.

![Screenshot from 2021-02-02 02:06:10](https://user-images.githubusercontent.com/1234848/106542495-d7802300-64fb-11eb-81f6-358e7dbb6f6a.png)

**Comment by splace** [comment] 2021-02-02 02:41
i think this has been for about a month

i kept thinking i had just missed the pop-up, but now have watched carefully several times. i could make a video of it.

**Comment by JoshStrobl** [comment] 2021-04-12 15:02
This is the result of us currently having the `device.removed` notification as a "spam" category and that gets filtered. I'll remove the device related notification filtering though, they serve little value and originally were added when I was implementing the notification grouping and wanting to try to filter network connect / disconnects from being put in Raven. This is in its own way a duplicate of #1192, just that I forgot to close that issue when I originally implementing Notification Grouping, and not filtering it now will result in those notifications being shown so.

**Closed** 2021-04-12 15:03 UTC
