### ISSUE TITLE
Raven audio overamplification to 150% conflicts with the volume up option

### ISSUE THREAD

**Issue by sntdevco** [solus-project/budgie-desktop#1727] opened 2019-01-21 05:09 UTC
Raven audio overamplification to 150% conflicts with the volume up option on keypress.

**Operating System**: Ubuntu Budgie 18.04.1
**Budgie version**: 10.4
**Linux kernel version**: 4.15.0-43-generic

### How to reproduce
Add the raven indicator to some place in the top panel. Now open Budgie desktop settings from the Budgie menu and add click on raven and enable the volume to be increased over 100%. Now use the hardware keys (F7 for down and F8 for up in my case) to increase the volume and the overamplification setting is ignored. Also for any other audio volume based applet in the top panel, the same issue occurs.
Instead of making it a default choice (as in Cosmic Cuttlefish aka Ubuntu 18.10) there should be an option to enable it **system-wide**

Regards,
Sayan

Similar to #1667 #957

**Comment by JoshStrobl** [comment] 2019-01-21 08:00
Duplicate of #1679. I'm currently satisfied with the implementation of the volume overdrive functionality.

**Closed by JoshStrobl** 2019-01-21 08:00 UTC
