### ISSUE TITLE
Budgie Main Menu Duplicates (One Item so far)

### ISSUE THREAD

**Issue by Sethox** [solus-project/budgie-desktop#1500] opened 2018-07-08 07:45 UTC
**Operating System**: Latest Solus (linux-current)
**Budgie version**: Latest Budgie (budgie-desktop v10.4-85-g36667bcb)

**The issue encountered**
I recently installed Notepadqq and I noticed the **All section** takes from every section/categories but when I search for an item/application I get just one hit of this item/application
 ...

**The presented issue**
![All section](https://i.imgur.com/iaIuHo5.png)
![Accessories](https://i.imgur.com/qgNgeDu.png)
![Programming](https://i.imgur.com/HcPyKyb.png)

**Comment/opinion to a solution**
A solution could be that the all section searches for an item/application, if item found then do not pick up item with same name after the first hit.

**Comment by bsucker98** [comment] 2018-07-08 12:43
same here, with _Steam_ & _Linux Steam Integration_ apps
& I'm not sure is this a bug, I get two icons for telegram, one called **Telegram**(this shows `telegram client` on hover) and the other **Telegram Desktop**(this shows `official desktop application for the telegram messaging service` on hover)

**Comment by JoshStrobl** [comment] 2018-07-18 12:51
Duplicate of #1327

**Closed by JoshStrobl** 2018-07-18 12:51 UTC
