### ISSUE TITLE
System Tray icons not correctly displayed at size 37 and above (e.g. Skype icon)

### ISSUE THREAD

**Issue by pappkamerad** [solus-project/budgie-desktop#1556] opened 2018-09-03 10:17 UTC
**Operating System**: Solus 3.9999
**Budgie version**: 10.4-85-g36667bcb (version in Software Center: 10.4-170, ...why different?)

The Skype icon (and maybe others) in the system tray (panel) are not displayed correctly at size >=37:
![image](https://user-images.githubusercontent.com/684932/44981300-6fb3ff80-af72-11e8-9be9-eb8bf297ab0b.png)

This is on a 2560x1440 display at 100% scale

It is happening since a couple of weeks.

**Comment by JoshStrobl** [comment] 2018-09-03 17:55
Duplicate of #1361

**Closed by JoshStrobl** 2018-09-03 17:55 UTC
