### ISSUE TITLE
rhythmbox menu is not accessible under budgie ubuntu

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#281] opened 2015-12-31 16:43 UTC
When running budgie under Ubuntu Rhythmbox menus are not accessible - through the application-menu which should be displayed in the top-bar.

Might be a common theme for all older GTK3 apps that use menus rather than a CSD.

![Imgur](http://i.imgur.com/PwQPcQr.png)

Screenshot shows me using alternate-toolbar - but similar screenshot of standard rhythmbox also doesnt have the application menu button.

In alternate-toolbar I use the following to decide whether to display the application-menu button (same logic in rhythmbox) - looks like budgie is accidentally not respecting one of the Gtk.Settings values? - I guess you are leaving gtk_shell_shows_app_menu to be True when it should be False since budgie doesnt use GTK app menus (or doesnt at the moment):

<pre>
default = Gtk.Settings.get_default()
if ( not default.props.gtk_shell_shows_app_menu) or  default.props.gtk_shell_shows_menubar:
                display_type = "standard menu"
else:
                display_type = "CSD header bar"
</pre>

**Comment by marek287** [comment] 2015-12-31 19:21
I think these are same issuses:
https://github.com/tiliado/nuvolaplayer/issues/193#issuecomment-168235858

**Comment by ikeydoherty** [comment] 2015-12-31 19:58
Yea I commented over there now to address the claim we're lying. It's going to be addressed, and this is a duplicate of #261

**Closed by ikeydoherty** 2015-12-31 19:58 UTC
