### ISSUE TITLE
Wifi icon has lots of padding/spacing from other icons on panel

### ISSUE THREAD

**Issue by twodogsdave** [solus-project/budgie-desktop#1574] opened 2018-09-22 22:19 UTC
**Operating System**: Solus 3.9999 (the new Solus refresh ISO)
**Budgie version**: budgie-desktop v10.4-85-g36667bcb

**The issue encountered**
Normal desktop with default budgie panel settings and wifi icon by the clock has a lot more spacing than the other icons and the wifi icon sits out on its own.
 ...

**Steps to reproduce the issue**
Look at budgie panel after logged in.

 ...

**Comment by JoshStrobl** [comment] 2018-09-24 03:48
Closing as duplicate of #610, it sits out on its own because it's an xembex tray icon item, so it uses the system tray, it's not a native applet.

**Closed by JoshStrobl** 2018-09-24 03:48 UTC
