### ISSUE TITLE
Question/Suggestion regarding tray icons

### ISSUE THREAD

**Issue by null-von-sushi** [solus-project/budgie-desktop#1517] opened 2018-07-31 21:22 UTC
**Operating System**: e.g. Antergos (Arch based)
**Budgie version**: budgie-desktop v10.4-34-gd6f3519f

**The issue encountered**
The network manager applet is provided by a separate package and is a generic tray icon. Would it be possible to get a seperate network manager panel item, or alternatively a way to blacklist certain programs from the 'system tray'? The reasons are aesthetic. Tray icons are mostly deprecated and only really serve a use to keep messaging or music applications running in the background. Generally, they are hard to theme (and might even ignore the current icon theme) and have a different size to the normal budgie panel icons. It would be nice to be able to remote the system tray but still have access to networking settings, or at least limit the amount of icons which are cluttering the panel.
 ...

**Steps to reproduce the issue**
N/A?

 ...

**Comment by JoshStrobl** [comment] 2018-07-31 22:00
Closing as duplicate of #610.

**Closed by JoshStrobl** 2018-07-31 22:00 UTC
