### ISSUE TITLE
Budgie-wm artifact issue. Please help me :(

### ISSUE THREAD

**Issue by inzar98** [solus-project/budgie-desktop#1627] opened 2018-11-22 17:04 UTC
**Operating System**: Ubuntu Budgie 18.10 (Tried with manjaro too. Its same..)
**Budgie version**: Budgie 10.4

**The issue encountered**

I got weird artifact issue with budgie-wm animations. When I openned manu and clicked anther window, menu disappers but shadow is stayed with me :rofl: 

https://imgur.com/a/OjCS7lM

**Steps to reproduce the issue**

Only activated animation of bugdie-wm...

**Comment by JoshStrobl** [comment] 2018-11-23 15:44
Unable to reproduce under Solus. I'm going to consider this a symptom of the newer Mutter until I see otherwise.

**Comment by inzar98** [comment] 2018-11-23 16:12
Im waiting for the solution thanks 🙏

**Comment by Alexander88207** [comment] 2018-11-23 16:59
@inzar98 #1622

**Comment by inzar98** [comment] 2018-11-23 17:59
> @inzar98 #1622

Animations are everythink for me bro...

**Comment by inzar98** [comment] 2018-11-23 19:56
> > > @inzar98 #1622
> > 
> > 
> > Animations are everythink for me bro...
> 
> 18.04.1 or 18.10?

18.10

**Comment by maxmbed** [comment] 2018-12-06 21:51
Do you still have this issue if you disable the animation through Budgie Desktop Settings ?

**Comment by Alexander88207** [comment] 2018-12-06 21:56
yeah thats the walkaround

**Comment by pierrinator** [comment] 2018-12-27 16:08
Same problem for me on a fresh install of Arch Linux. Disabling animations fix the bug, but it's kinda annoying.

**Comment by JockeTF** [comment] 2018-12-27 19:10
Yes, definitely looks like a "new Mutter" issue.

**Comment by thomxo** [comment] 2019-01-04 20:45
Same problem here, Manjaro Budgie Latest Updates installed, that really bugs me but disabling animations is a nice workaround, at least I found this issue after days of search for anybody else with this problem.

**Comment by aclapes** [comment] 2019-01-16 18:33
Exact same problem here with Budgie desktop on Manjaro 18.0.1.
Gnome & mutter versions 3.30.2
Budgie-desktop v10.4-123-gf2dbc215
Graphics board Intel® UHD Graphics 620

Hopefully this is fixed anytime soon, I love the desktop with its clean/simple animations.

**Comment by antonvalletas** [comment] 2019-03-21 13:19
Exact same proble in Budgie Manjaro. 
Gnome and Mutter 3.30.2
Budgie Desktop v10.4

I will check if this is fixed with the new version of mutter and budgie in the next stable update. However what I am noticing is that this doesn't happen with all animations. For example, it will happen on animations from the application menu and the volume up down popups, but it will not happen with the animations from any of the applets such as night light, caffeine...

**Comment by fossfreedom** [comment] 2019-03-23 13:11
FYI - Ubuntu 18.04 is proposing to uplift mutter 3.28 to-do some fixes.  Among the fixes that was being proposed I found a specific commit that mutter upstream made that causes this artefact issue.
If anyone has any ideas what this commit does and suggest a potential fix for budgie's animation that is invoking the issue then please shout out.

https://bugs.launchpad.net/ubuntu/+source/mutter/+bug/1811900/comments/8

**Comment by dreamcat4** [comment] 2019-03-23 16:33
@garnacho if you have the time and could please respond, for this downstream project. In terms of reducing artifacting / window drawing problem(s). When one window is overlapped onto another.

When perusing the other linked fixes here:

https://bugzilla.gnome.org/show_bug.cgi?id=782344

It seems that many of your improvements (and thank you for that!) have been performance optimizations.

Well in fact we also happen to have another bug, in regards to very high CPU usage, (when there is a lot of drawing happening). Which is over here:

https://github.com/solus-project/budgie-desktop/issues/1379

So again, if something is immediately obvious, the maybe you can tell us something new downstream. That we have missed!

Thank you.

**Comment by fossfreedom** [comment] 2019-04-01 08:57
A bit of an FYI - have raised this now upstream https://gitlab.gnome.org/GNOME/mutter/issues/536

A few replies there to scratch our heads over.

**Comment by fossfreedom** [comment] 2019-04-09 09:44
ok ... baby steps.  So forcing a complete relayout of the the bit that is doing the animation seems to resolve artifacts appearing on the screen - the animation though remains a bit weird though.

Anyway - food for thought for anyone who is interested in tinkering in this area:

adding `actor.queue_relayout()` at line https://github.com/solus-project/budgie-desktop/blob/master/src/wm/wm.vala#L647 i.e. so it reads

``` 
 actor.queue_relayout()
 actor.remove_all_transitions();
```

**Comment by tista500** [comment] 2019-04-09 23:11
@fossfreedom,

Looks good to me (Disco, Mutter 3.32.0-1ubuntu2). :)
I've checked Budgie-menu, Notification-window, Brightness OSD, Volume OSD, Run-dialog, and Alt-tab-switcher at least...

Regards.

**Comment by ThePiGuy0** [comment] 2019-04-14 11:52
@fossfreedom 

I'd love to give your fix a go - is there a particular branch I need to build budgie from (I just tried it using the main branch but I believe that is still aimed at 3.28 mutter)

**Comment by ThePiGuy0** [comment] 2019-04-14 14:39
@fossfreedom 

As an update, I used the mutter330reduxII branch from the Ubuntu Budgie fork of this repo (having merged the master branch up to date with this first) and built both with and without the "actor.queue_relayout();" line. (on a fresh ubuntu 19.04 base)

I can now verify that as with @tista500 this seems to solve any artifacting that I can see (admittedly my test was in virtualbox so I didn't do a full extensive test). Also to my eyes the animations looked good (better than most in virtuabox)

**Closed** 2019-04-23 11:00 UTC
