### ISSUE TITLE
Budgie desktop 10.1 missing polkit auth and nm-applet

### ISSUE THREAD

**Issue by lexuv** [solus-project/budgie-desktop#271] opened 2015-12-30 22:49 UTC
Budgie desktop 10.1 missing polkit auth (rights elevation) (for example, Time and date settings or Pamac installation) doesn't work. Network manager applet is absent as well. How to get all that stuff working?

**Comment by ikeydoherty** [comment] 2015-12-30 23:01
Duplicate of #261 

Install network-manager-applet and Budgie will autostart it. Native implementations will come in time.

**Closed by ikeydoherty** 2015-12-30 23:01 UTC

**Comment by feskyde** [comment] 2015-12-31 01:26
For polkit auth, install `polkit-gnome` (an optional dependency for Pamac)

**Comment by lexuv** [comment] 2016-01-01 18:02
It's been installed with gnome, but doesn't appear in the tray panel.

2015-12-31 1:01 GMT+02:00 Ikey Doherty <notifications@github.com>:

**Comment by ikeydoherty** [comment] 2016-01-01 18:29
That was added in 10.2, please update to 10.2.1
