### ISSUE TITLE
Icon Tasklist doesn't remove icons when you close apps

### ISSUE THREAD

**Issue by chax** [solus-project/budgie-desktop#1665] opened 2018-12-12 20:27 UTC
**Operating System**: e.g. Solus 3.9999
**Budgie version**: i.e. Budgie 10.5-179

**The issue encountered**
This is the issue with Icon Task List Applet on Budgie panel. It happens when you have Window grouping setting turned off. When you close the app, icon stays in tray.

**Steps to reproduce the issue**

- Add Icon Task list to your panel
- Disable Window grouping setting
- Pin some application to panel (i.e. Chrome or VSCode)
- Open at least two windows for that app (you can also try with more)
- Close one of the windows - the icon will stay in Icon Task List
- Close all windows - all icons will stay even though their windows are closed (even if you kill all instances through System Monitor)
- Click on any of the leftover icons - new window will open
- Unpin app from panel using the star button in popover - that one icon will be removed but the rest of the icons will stay even though their instances are closed - you can do that for each remaining icons until the last one is gone from panel
- Enable Window grouping setting - all icons will be combined into one icon (as expected), it will also remove icons for closed windows
- Disable Window grouping setting - it will again show icon per window but only for opened windows

**Bonus**
If you click on '+' button in popover menu and the app only supports one instance (i.e. Software Center), Icon will start to blink in the panel, but nothing other than that will happen. After some time, the blinking will stop.

**Comment by JoshStrobl** [comment] 2018-12-12 21:50
Thanks for the detailed issue and steps to reproduce, it's appreciated! I'll see about getting this fixed in some upcoming commits. I had some various issues I've fixed in git and in rel 179 for closing for apps when grouping is enabled, I'll make sure those same changes apply when grouping is disabled as well.

**Comment by chax** [comment] 2018-12-12 21:53
No, thank you for the great work on Budgie and Solus. I really appreciate it.

**Closed** 2018-12-13 00:56 UTC
Labels: bug

**Comment by JoshStrobl** [comment] 2018-12-13 00:59
Going to be pushing out a new package release (rel 180) in next 30min or so with latest commit. Would appreciate if you could validate my fix :slightly_smiling_face:

**Comment by chax** [comment] 2018-12-13 07:11
Yep, works now. But i noticed when i disable Window grouping that button in popover 'Close All Windows' closes only that one window. When i enable Window grouping that button works as expected.

**Comment by JoshStrobl** [comment] 2018-12-13 07:31
Yes, that's because only one window is registered to the popover. There's no real feasible way for us to have it close all windows across all unique button instances when grouping is disabled, unfortunately, and I'm not entirely sure that would be the expected behavior 🤷‍♂️

**Comment by chax** [comment] 2018-12-13 07:53
Then it's good, thanks for taking care of this so quickly.
