### ISSUE TITLE
FR: support switching among windows with the Super key + 0..9

### ISSUE THREAD

**Issue by dandv** [solus-project/budgie-desktop#1649] opened 2018-12-08 21:30 UTC
# Feature request

Switch among the visible windows of running applications using <kbd>Super</kbd>+<kbd>1</kbd>/<kbd>2</kbd>/<kbd>3</kbd>/.../<kbd>9</kbd>. The 0..9 order is the order in which the application icons appear in the task bar. For extra points, if application N is not running when Super+N is invoked, launch it.

## Reasoning

This is especially handy if you often switch among the same few apps, e.g. a browser, a file manager and an editor, but also have other apps open, so Alt+Tabbing to the desired window would take more time.<sup>1</sup>

That keyboard shortcut saves me probably 5 seconds per minute on the average, so ~40 minutes a day, and it's supported by Windows and a few Linux DEs as well. Adding custom keyboard shortcuts for given apps doesn't work, because pressing the shortcut will launch a new instance of the app.<sup>2</sup>

<sup>1. The DE will order the most frequently used windows first, but you have to first look and see how many times you have to press Alt+Tab; while with Super+1 or Super+2, you always know which shortcut goes to one app or the other.</sup>

<sup>2. Some apps have an option to allow only one instance, but this is the exception rather than the rule, and even in that case, there will be a noticeable flicker of launching the new instance and seeing it exiting immediately.</sup>

## Prior/related work

* https://askubuntu.com/questions/813262/which-desktop-environments-allow-switching-among-windows-with-supernumbers/813575
* https://discourse.ubuntubudgie.org/t/super-number-keyboard-shortcut/1040
* https://askubuntu.com/questions/246886/how-do-i-open-the-application-launcher-on-kde-with-just-the-meta-windows-key/246953#comment1230911_246886
* https://github.com/linuxmint/Cinnamon/issues/5561
* #1199

**Comment by JoshStrobl** [comment] 2018-12-09 10:16
Duplicate of #1076

**Closed by JoshStrobl** 2018-12-09 10:16 UTC
