### ISSUE TITLE
audio output: unable to select any device after active device removed.

### ISSUE THREAD

**Issue by splace** [solus-project/budgie-desktop#1653] opened 2018-12-09 02:21 UTC
solus 3.9999
gnome 3.28.2
budgie-desktop v10.4-85-g36667bcb

**The issue encountered**
when removing audio device

**Steps to reproduce the issue**
add new sound device, switch to it, remove it, select any available device, nothing happens.
(hack to bypass: re-add the device, switch away from it, then remove)

also

raven sound bar showing all devices selected all the time, and so unable to use. (did work on original installation)

possibly related to  #1102

**Comment by JoshStrobl** [comment] 2018-12-10 17:43
Duplicate of #1057

**Closed by JoshStrobl** 2018-12-10 17:43 UTC

**Comment by splace** [comment] 2018-12-10 18:02
this should be reopened as it is when using 'sound source' not 'raven',  which #1057 seems to be specifically about.
