### ISSUE TITLE
budgie launcher icon

### ISSUE THREAD

**Issue by darkomarko42** [solus-project/budgie-desktop#2080] opened 2020-12-19 12:45 UTC
## Description

budgie menu launcher icon doesnt fit with budgie icon task list.
the budgie launcher icon is bigger than the other icons whatever i change the size.

## Budgie version

10.5.1

## Operating system

Manjaro 20.2

**Comment by JoshStrobl** [comment] 2021-04-12 15:07
Duplicate of other issues related to icon tasklist button sizing.

**Closed by JoshStrobl** 2021-04-12 15:07 UTC
