### ISSUE TITLE
Feature Request: custom command support for runner.

### ISSUE THREAD

**Issue by rilian-la-te** [solus-project/budgie-desktop#557] opened 2016-09-05 13:54 UTC
I like budgie-desktop, and I like its runner. But for now it is impossible to launch custom command via it. If you want, I can extend runner for supporting custom commands.

**Comment by JoshStrobl** [comment] 2016-09-09 11:04
@ikeydoherty This is a duplicate of #265

**Comment by ikeydoherty** [comment] 2016-09-09 11:05
Is indeed, closing as such. Thanks

**Closed by ikeydoherty** 2016-09-09 11:05 UTC
