### ISSUE TITLE
Bad volume slider text inside Raven

### ISSUE THREAD

**Issue by TheSimple** [solus-project/budgie-desktop#1698] opened 2019-01-05 05:58 UTC
**Operating System**: Solus 3.9999 
**Budgie version**: Budgie 10.5-186  

**NOTE**: The system is up to date as of today.

**The issue encountered**
The speaker volume slider inside the raven bar has this weird volume percentage indicators (see attachment). It shows as follows "100% 100%" all the time, even when I change the volume slider. BTW this not a major issue, but it still looks somewhat annoying AND makes the almost complete Budgie Desktop look uncomplete. 

 ...

**Steps to reproduce the issue**
Open the raven bar from the Budgie Panel (the icon on the rightmost) AND see the text right below the volume slider.

 ...

**Screenshot**
![screenshot from 2019-01-05 11 24 17](https://user-images.githubusercontent.com/29624671/50720935-f9203d80-10dc-11e9-989e-d5bfa62d13a9.png)

**Comment by JoshStrobl** [comment] 2019-01-05 06:02
Duplicate of #1604. I would suggest you use a supported theme such as Adapta or Plata.

**Closed by JoshStrobl** 2019-01-05 06:02 UTC
