### ISSUE TITLE
Adding Raven settings button to end of new panel results with visual glitch of icon being shown at the start of the panel

### ISSUE THREAD

**Issue by yarpus** [solus-project/budgie-desktop#615] opened 2016-09-21 18:40 UTC
**Operating System**:Solus 1.2.0.5 64-bit
**Budgie version**: 10.2.7

**The issue encountered**
When customizing Budgie panel, I saw visual glitch that caused icon for opening Raven panel end up being detached from the button. Button was clickable in point a, icon was badly displayed over Budgie Menu's icon.

![screenshot from 2016-09-21 19-55-35](https://cloud.githubusercontent.com/assets/17219684/18724141/a225248e-803b-11e6-8fdb-40d9b23cf7f9.png)

**Steps to reproduce the issue**
1.     Add new panel
2.     Add 1-2 different elements (I added Budgie Menu, Application indicator & taskbar)
3.     Add Raven configuration button
4.     Move it to the end of panel

**Comment by yarpus** [comment] 2016-09-21 23:44
Extra note: it was all happening when panel was at the bottom.

**Comment by yarpus** [comment] 2016-09-22 21:09
Partially duplicate of: #574 
Still, issue is tied to Raven controls being the last button on the list and will happen after you move button.

**Comment by ikeydoherty** [comment] 2016-10-07 00:51
Closing as dupe of #574 - and I have a fix ready

**Closed by ikeydoherty** 2016-10-07 00:51 UTC
