### ISSUE TITLE
Super-Tab Issue when other remapping tools are used

### ISSUE THREAD

**Issue by rbreaves** [solus-project/budgie-desktop#1971] opened 2020-05-13 01:00 UTC
## Description
When I use a tool like xkeysnail to remap Super-Tab to use Alt or Ctrl + Tab or another key other than Tab the launcher glitches out. It'll appear for a moment and then disappear as though the new modifier has only been emitted - but 'xbindkeys -mk' very clearly receives the proper keybinds and I know the modifier key is being held even when remapped (when the DE is no longer bound to the combo for App Switching).

Other DE's I have tested with do not exhibit this behavior, whether it is Gnome, KDE, or XFCE.

## Budgie version
Latest version with Solus 4.1

## Operating system
Solus 4.1

## Steps to reproduce the issue
1. Install xkeysnail
2. run config to remap

Detailed steps
1. Go to https://github.com/mooz/xkeysnail or my version https://github.com/rbreaves/xkeysnail
2. Install dependencies

```
sudo eopkg install gcc
sudo eopkg install -c system.devel
```

3. Clone repo

```
git clone --depth 1 https://github.com/rbreaves/xkeysnail.git
# or
git clone --depth 1 https://github.com/mooz/xkeysnail.git
cd xkeysnail
sudo pip3 install --upgrade .
```

4. Save config.py file

```
# -*- coding: utf-8 -*-

import re
from xkeysnail.transform import *

define_keymap(None,{
    # Cmd Tab - App Switching Default
    K("Super-Tab"): pass_through_key, # Simply ignores that actual Super-Tab key - can be commented out though
    K("Super-Shift-Tab"): pass_through_key, 
    K("C-Tab"): K("Super-Tab"),
    K("C-Shift-Tab"): K("Super-Shift-Tab"),
})

```

5. run xkeysnail

```
sudo xkeysnail ./config.py
```

You can reset the hotkey if you want in the keyboard shortcut menu area.

## Actual result
App switcher's window appears briefly, only switches between 2 apps.

## Expected result
Window should remain open for as long as the key is held and switch between all apps.

## Additional information
Once this issue is worked out I will be updating my own project to fully support both Solus and Ubuntu Budgie. Also my older xkb method for remapping also fails to work, somewhat surprised and not. The reason why I use xkeysnail now is that xkeysnail was compatible with KDE due to its lower level udev remapping of the keys.

**Comment by rbreaves** [comment] 2020-05-13 01:13
Pretty sure this line/commit here is the source of the problem. I am not sure what it needs to be checking against instead just yet, but it isn't that. We need to be checking for whether or not the mapped modifier key has really been released or not in a different way so that if keys have been remapped via xkb or another tool it'll detect that and not hide the app switcher incorrectly.

https://github.com/solus-project/budgie-desktop/pull/1668/commits/cab1989c46a04386b9e6baf061663a1de4fcef67#diff-c79f71d13acc41b33b0319dc19236858

**Comment by friday** [comment] 2020-06-25 19:59
I kept the issue open, but not the PR, since that needed feedback I knew I wasn't going to get and work I wasn't willing to put in given the state of Solus in Arch back then. I hope yours get merged though.

**Comment by rbreaves** [comment] 2020-06-26 01:25
Well I’ve also submitted the same fix to fossfreedom on his Ubuntu-Budgie fork, but he’ll either wait awhile, till their next release or merge it if it makes into master here.

The ubuntu-budgie branch has a number of fixes that’d probably make sense for this master branch, but there’s a resistance to things like fixes for better global menu extension support.

**Comment by JoshStrobl** [comment] 2020-07-10 18:17
Re-opening as commit was reverted due to it breaking alt+tab dialog closing for some folks.

**Comment by rbreaves** [comment] 2020-07-10 19:28
> Re-opening as commit was reverted due to it breaking alt+tab dialog closing for some folks.

Thanks for letting me know and that's disappointing. I will spin up my VM and see if I can't replicate this behavior.

**Comment by JoshStrobl** [comment] 2020-07-10 19:31
@rbreaves Yea I couldn't reproduce it locally either, I'm hoping @serebit and others can chime in and maybe provide their keyboard layout and provide their modifier data from `xev`. But I had to revert it immediately so folks on Solus wouldn't have a broken alt+tab experience (I had already gotten multiple reports within the span of about 10 minutes, so my priority was reverting).

**Comment by rbreaves** [comment] 2020-07-10 19:40
I see, and yea - I am unable to duplicate it in my VM here. And yea maybe it is a language thing, but I am surprised their modifiers wouldn't have been picked up just fine by the modifier mask, I guess another option would be to be explicit about Alt, Super or Ctrl being released vs the modifier mask.

Maybe there's a thing going on with other language formats the prevent the keyboard from reaching a mask value of 0 or 2. Not sure if I tested it with a full size keyboard with numlock on and off.. that might be something to look at.

**Comment by serebit** [comment] 2020-07-10 21:35
Hi! I'm using a standard US QWERTY keyboard layout. I'd be happy to provide modifier data if someone tells me how to do it :p

**Comment by rbreaves** [comment] 2020-07-11 00:09
Yea, I believe it is the numlock key that mucked it up. I apologize about that, it has a value of 6 that should be checked for otherwise the alt-tab dialog stays open. I am unaware of any other keys that that the ability to stay in a locked position, although shiftlock probably is something I need to try and account for as well.

**Comment by rbreaves** [comment] 2020-07-11 02:33
I am pretty certain it was just an issue from numlock. I have reverted back to the old hardcoded method as I feel like that is safer in light of possible held key issues.

What I really needed was support for the Control key because my Kinto project remaps the right Control key back to Alt-Tab (which is the 1st left modifier key to the space bar) & the Left Control key stays as the normal Ctrl-Tab combo.

The latest patch I submitted does allow for just that and nothing more - but it does allow for control Control + combos as well (even though people are not likely to need or want to use the actual Ctrl-Tab combo because it would conflict with many apps in a typical scenario).

**Comment by friday** [comment] 2020-07-11 07:11
I'm using Command-Tab. Many Mac refugees are doing that.

**Comment by rbreaves** [comment] 2020-07-11 16:30
Ok, I’ll disable my Kinto app & make sure the Cmd/Super key is working on its own - if it’s mapped. Pretty sure it already does as Mod1 (Alt) & Mod4 (Super/Cmd) were already hardcoded. I just added Control to the possible mix.

**Comment by JoshStrobl** [comment] 2020-10-13 21:44
I believe folks like @serebit that have been testing the git builds have **not** been experiencing issues with the latest commit by @rbreaves, so I'm going to consider this resolved. Thanks again for the follow-up @rbreaves.

**Closed by JoshStrobl** 2020-10-13 21:44 UTC
