### ISSUE TITLE
Strange behavior of icon group with multiple Libreoffice files

### ISSUE THREAD

**Issue by samuelcecilio** [solus-project/budgie-desktop#1477] opened 2018-06-12 16:35 UTC
**Version:** budgie-desktop v10.4-85-g36667bcb

**Issue**

A picture is worth a thousand words.

![peek 12-06-2018 13-17](https://user-images.githubusercontent.com/30150045/41303742-7fb1433a-6e44-11e8-9102-4b7e7aec0833.gif)

**Steps to reproduce the issue**

- Open two Libreoffice Writer files
- Open a Libreoffice Calc file
- Close Libreoffice Calc

 ...

**Comment by JoshStrobl** [comment] 2018-06-13 17:20
Duplicate of #1405

**Closed by JoshStrobl** 2018-06-13 17:20 UTC
