### ISSUE TITLE
Right click on window titles doesn't work

### ISSUE THREAD

**Issue by dgaw** [solus-project/budgie-desktop#1457] opened 2018-05-25 06:05 UTC
**Operating System**: Solus 3.9997
**Budgie version**: budgie-desktop v10.4-70-g15c960cc

**The issue encountered**

Right-clicking on the window title bar does not reveal a menu. Previously it worked sometimes (probably related to #751).

**Steps to reproduce the issue**

1. Open gnome-terminal
2. Right-click on the window title bar

**Comment by JoshStrobl** [comment] 2018-05-25 06:26
Duplicate of #1116

**Closed by JoshStrobl** 2018-05-25 06:26 UTC
