### ISSUE TITLE
Keyboard shortcuts does not work in Budgie Menu

### ISSUE THREAD

**Issue by IgorWalkers** [solus-project/budgie-desktop#1357] opened 2018-03-19 22:35 UTC
**Operating System:** Manjaro Linux 17.1.6
**Budgie version:** v10.4-8-gff09a510

**The issue encountered**
When Budgie Menu applet is open none of the keyboard shortcuts is working. I tried to change keyboard layouts while searching for app.

**Steps to reproduce the issue**
Just open Budgie Menu applet.

**Comment by IgorWalkers** [comment] 2018-03-20 23:37
I am pretty sure my issue is duplicate of #1306 but it`s closed but not fixed.

**Comment by JoshStrobl** [comment] 2018-05-24 23:54
Duplicate of #420.

**Closed by JoshStrobl** 2018-05-24 23:54 UTC
