### ISSUE TITLE
Dual battery icon in menubar

### ISSUE THREAD

**Issue by JeromeDesseaux** [solus-project/budgie-desktop#1487] opened 2018-06-25 17:12 UTC
System up to date for every single package 

Hi everyone,

This isn't really "a bug". In fact, I have a Thinkpad T430s with dual batteries. One located inside the computer (the main one) and another one instead of the CD bay (called Ultrabay with Thinkpads). This is causing TWO battery icons in the top bar. There should be just one, displaying the average battery left knowing the charge of both two, right? 

I know this is specific.. But if you can tell me how to contribute I'd be glad to do it or helping you in any form! 

Thnkas for this project and "live long and prosper"!

**Comment by JoshStrobl** [comment] 2018-06-25 17:23
Duplicate of #737

**Closed by JoshStrobl** 2018-06-25 17:23 UTC
