### ISSUE TITLE
Blanking screen regularly  breaks Night Light

### ISSUE THREAD

**Issue by r3r57** [solus-project/budgie-desktop#1505] opened 2018-07-16 03:00 UTC
**Operating System**: Solus 3.9999 (everything updated)
**Budgie version**: Budgie v10.4-85-g36667bcb

Most times when using the *Night Light* feature and the screen blanks, the transition to black breaks *Night Light*. When waking the screen and looking at the settings, *Night Light* seems to be still enabled but doesn't work. To make it work properly again you have to wait a few seconds or disable and enable it again manually.
It's similar to [#1027](https://github.com/solus-project/budgie-desktop/issues/1027) but without suspending.

This is not a breaking bug, but it's rather annoying when working at night.

**Steps to reproduce the issue**
1. Enable *Night Light*.
2. Set *Blank Screen* to *X* minutes and wait for screen to blank.
3. *Night Light* is now disabled but the settings say it's still enabled.
5. Wait or disable and enable *Night Light* again to make it work again.

**Comment by JoshStrobl** [comment] 2018-07-16 22:45
Duplicate of #1284. Would be an upstream Mutter issue most likely.

**Closed by JoshStrobl** 2018-07-16 22:45 UTC
