### ISSUE TITLE
Custom button layout, reverted to defaults automatically.

### ISSUE THREAD

**Issue by RasmusKallas** [solus-project/budgie-desktop#1531] opened 2018-08-12 12:45 UTC
**Operating System**: Ubuntu Cosmic Cuttlefish (development branch) (Ubuntu budgie 18.10)
**Budgie version**: Budgie 10.4

**The issue encountered**
When trying to customize the button layout on windows it gets reverted back to default.
[More details.](https://askubuntu.com/questions/1064637/title-bar-buttons-on-both-sides/1064640)
 ...

**Steps to reproduce the issue**
run `gsettings set com.solus-project.budgie-wm button-layout close,minimize,maximize:minimize,maximize,close`
reboot
run `gsettings get com.solus-project.budgie-wm button-layout`
The setting has changed to the default.

 ...

**Comment by fossfreedom** [comment] 2018-08-12 14:45
This is probably due to the proposed mutter PR that has not been merged yet.

I will have a look at this

**Comment by fossfreedom** [comment] 2018-08-15 21:26
Can you double check that setting left/right buttons via budgie-settings works correctly i.e. that the settings are retained between sessions.

**Comment by RasmusKallas** [comment] 2018-08-18 13:37
[After running `gsettings set com.solus-project.budgie-wm button-layout close,minimize,maximize:minimize,maximize,close`](https://i.imgur.com/BLp1kES.png)

[After reboot.](https://i.imgur.com/P7cSIUP.pngl)

**Comment by fossfreedom** [comment] 2018-08-18 13:44
I need you to use the GUI not the gsettings variant (which I don't know why you are using anyway.)

**Comment by RasmusKallas** [comment] 2018-08-18 18:01
Confirmed with GUI only, same result.

**Comment by fossfreedom** [comment] 2018-08-18 18:16
Are you fully up to date?

   sudo apt update && sudo apt dist-upgrade

**Comment by RasmusKallas** [comment] 2018-08-18 18:33
Yes, retested it also, after trying to update.

**Comment by Coeur-Noir** [comment] 2018-08-29 02:52
« which I don't know why you are using anyway »
It seems @RasmusKallas wants wm-buttons on both ends ?

First maybe that's impossible to have the same button twice ?

Second, on UBudgie 18.04 playing with button-layout in gsettings / dconfeditor has immediate effect on NON-csd windows ( Firefox, Gimp… ) but not on csd ( nautilus, dconf-editor… )

Example : removing minimize button does not seem possible ( immediatly at least ) in csd windows.

Maybe a limitation on csd side ? Or a purposed limitation to keep consistency between csd and non csd windows ?

**Comment by Vistaus** [comment] 2018-09-08 15:28
I can reproduce this on a clean install of Solus Budgie, so it's not Ubuntu-specific.

**Closed** 2018-12-31 05:41 UTC
Labels: bug
