### ISSUE TITLE
Ubuntu-Budgie 18.04 End-Side Applet Configuration Issues

### ISSUE THREAD

**Issue by Silcore** [solus-project/budgie-desktop#1588] opened 2018-10-07 17:41 UTC
This issue references #1058 which was closed on July 21st 2017. On Ubuntu-Budgie (using Budgie 10.4), the end-side of the applet panel does not retain positioning set through the _Budgie Desktop Settings_ application. It also does not allow end-side applets to be moved back downward on the configuration list.

**Replication Procedures**:
  * _System_: Ubuntu-Budgie 18.04, Budgie 10.4
  * Run command `nohup budgie-panel --reset --replace&` for full panel reset
  * Open _Budgie Desktop Settings_
  * Attempt to move _Raven Sidebar Control_ up

By following these procedures you will see that _Raven Sidebar Control_ (and other such applets) cannot be moved back down on the configuration list after having been moved up. By looking at the manner the configuration menu behaves, it seems as though the applets are assumed to be at the furthest right position (thus disabling the down-shift button) when they are actually not.

Further system specifications available [here](http://i.imgur.com/JF8hR8X.png). Screenshot of Budgie Settings blocking applet movement available [here](http://i.imgur.com/s96xga8.png). Screenshot of Budgie Settings not reflecting actual panel applet configuration available [here](http://i.imgur.com/jwgrnsf.png). Note that the order should be `Separator > User Indicator > Spacer > Raven` while the visible order is `Raven > Spacer > Separator > User Indicator`. It is also worth noting that the _User Indicator_ is at the furthest down position that can be toggled with the down-arrow button, suggesting the configuration panel believes this to be the lowest point on the list.

_Originally posted by @Silcore in https://github.com/solus-project/budgie-desktop/issues/1058#issuecomment-427671052_

**Comment by JoshStrobl** [comment] 2018-10-08 20:21
Duplicate of #1253

**Closed by JoshStrobl** 2018-10-08 20:21 UTC
