### ISSUE TITLE
Intelligent/automatically hidden bottom panel doesn't reappear

### ISSUE THREAD

**Issue by romankp** [solus-project/budgie-desktop#2016] opened 2020-08-03 00:00 UTC
When "Automatically hide" setting is changed to Intelligent or Automatic for a panel "Bottom" positioned panel and it auto-hides, it does not reappear when the mouse is moved to the very bottom of the screen, as if the panel hit-box does not recognize the mouse cursor position.

## Budgie version
budgie-desktop 10.5.1 (git-42201c183fccd7d65f143f8f6bb70bcf3bcaffd8)

## Operating system
Solus 4.1

## Steps to reproduce the issue
Make a bottom positioned desktop panel with the `Automatically hide` setting set to either `Intelligent` or `Automatic`. Open an application in full screen mode. Run mouse cursor along the bottom of the screen.

## Actual result
The bottom panel does not slide up or reappear.

## Expected result
The panel reappears when the mouse cursor enters hit box at the bottom of the screen.

## Additional information
I'm on a laptop with a high dpi screen at 3000x2000. `Size` is set to 31. 

Moving the panel to position "Top" causes it to act as expected, with it reappearing when moving the cursor to the very top of the screen.

**Comment by JoshStrobl** [comment] 2020-08-03 00:39
Duplicate of #1160

**Closed by JoshStrobl** 2020-08-03 00:39 UTC
