### ISSUE TITLE
Chrome apps share windows with Chrome

### ISSUE THREAD

**Issue by FelschR** [solus-project/budgie-desktop#1678] opened 2018-12-23 01:58 UTC
**Operating System**: e.g. Solus 3.9999
**Budgie version**: 10.5 (git-8a710056664f860224d4260b566d248948866a90)

**The issue encountered**
When using installed apps in Chrome (in the case of PWAs at least, not sure about Chrome apps) the window management is still the same as if it were just multiple Chrome windows and not separate apps.
![budgie-chrome-apps](https://user-images.githubusercontent.com/3314323/50380134-32c56300-065e-11e9-9b80-4e74998dc80c.png)

**Steps to reproduce the issue**

Go to an "installable" PWA in Chrome and install it (e.g. Android Messages for web or Telegram Web).
Now open the PWA and see how Budgie handles navigation with multiple windows.

**Comment by JoshStrobl** [comment] 2018-12-24 01:55
Duplicate of #1425

**Closed by JoshStrobl** 2018-12-24 01:55 UTC
