### ISSUE TITLE
Icon does not appear in the system tray (Ubuntu only)

### ISSUE THREAD

**Issue by fu-sen** [solus-project/budgie-desktop#425] opened 2016-04-26 14:57 UTC
For "Fcitx" that have been adopted as a standard Asia user input method,
the icon does not appear in the systray.
This occurs has confirmed that it is a case of only Ubuntu.
This problem has been confirmed with its own build and budgie-remix https://budgie-remix.org/ .
Debian (example SparkyLinux) and the Arch (example Manjaro) This will be displayed properly.

Apps problem on non-Fcitx might have occurred.

**Comment by ikeydoherty** [comment] 2016-04-26 15:08
Going to need confirmation on whether Ubuntu patches this to use AppIndicator or not.

@fossfreedom thoughts?

**Comment by fu-sen** [comment] 2016-04-26 15:11
I think this bug is told also in budgie-remix community.
I'm going to help at any time operation test in the future.

**Comment by ikeydoherty** [comment] 2016-04-26 15:18
OK but that's not what I asked :)

**Comment by ikeydoherty** [comment] 2016-04-26 15:18
Also I saw the G+ post.

**Comment by fossfreedom** [comment] 2016-04-26 15:26
I'm not famililar with fcitx (only speak one language -  "bad english"!) so can only judge what is in the changelogs

http://bazaar.launchpad.net/~ubuntu-branches/ubuntu/wily/fcitx/wily/view/head:/debian/changelog

and

http://changelogs.ubuntu.com/changelogs/pool/main/f/fcitx/fcitx_4.2.9.1-1ubuntu1/changelog

This is almost vanilla from Debian - so no patches for the app indicator.

There are lots of fcitx packages - I don't really know what you have to install to get fctix working

http://packages.ubuntu.com/search?keywords=fcitx&searchon=names&suite=xenial&section=all

**Comment by fu-sen** [comment] 2016-04-27 04:59
This method is effective even 16.04 LTS:

https://blogs.fsfe.org/stefan.a/2014/09/23/set-up-fcitx-chinese-and-japanese-language-input-ubuntu-14-04/

Ubuntu flavor automatically related packages fcitx When users install the Ubuntu flavor in the usual Chinese, Korean and Japanese is installed. (enable the download of the upgrade)

**Comment by fu-sen** [comment] 2016-04-27 05:07
I tried to switch the input method to IBus. (IBus was the standard input method of the Ubuntu flavor to 15.04)
Also displayed in the system tray in the IBus has not been obtained.

I'm feeling the possibility that there is this problem in other than the input method application.
For example, Dropbox ...

**Comment by fu-sen** [comment] 2016-04-27 05:12
I tried Dropbox, but also the icon was not displayed.
systray does not appear to be fully functional.

**Comment by fossfreedom** [comment] 2016-04-27 06:05
Budgie desktop does not support app indicators. We are looking for talented people to take the code for the existing app indicator code and add the simple budgie wrapper to show app indicators like Dropbox

**Comment by fossfreedom** [comment] 2016-04-27 06:09
After uninstalling ibus and installing fcitx as per that article Ctrl+space seems to display a small window at the bottom of the screen for a short amount of time.
Some times I see a keyboard icon in the system tray but it seems to disappear very quickly

**Comment by fu-sen** [comment] 2016-04-27 11:24
Perhaps it fcitx has completed startup successfully. fcitx will display a few seconds input method under (for example Mozc) when launching.

**Comment by ikeydoherty** [comment] 2016-07-23 12:00
Closing as duplicate of #286

**Closed by ikeydoherty** 2016-07-23 12:00 UTC
