### ISSUE TITLE
Window Borders remain after closing em

### ISSUE THREAD

**Issue by luukatyuo** [solus-project/budgie-desktop#1795] opened 2019-04-16 15:02 UTC
## Description

Whenever i close Budgies Launcher-Window the borders remain, sometimes they vanish by itself or when i click another window or move one over the remaining "parts". This also happens for other "down popping windows" from my top panel.

## Budgie version

budgie-desktop 10.5 (pamac says 10.5-1)

## Operating system, etc.

DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=18.0.4
Kernel 5.0.5-1
GPU:      
Intel HD Graphics 5500

## Steps to reproduce the issue

I dont know, happens since my install with 10.4 Budgie

## Actual result

![Screenshot from 2019-04-16 16-37-51](https://user-images.githubusercontent.com/49687833/56220600-fe404180-6068-11e9-9e1b-aab224df3092.png)

## Additional information
Also tried to chance Widgets-Theme and turning off Animations in budgie settings - no chance.
Any ideas how to fix? Any Workaround?

**Comment by ThePiGuy0** [comment] 2019-04-17 14:16
The issue is with mutter 3.30/3.32 (and is detailed here https://github.com/solus-project/budgie-desktop/issues/1627)

@fossfreedom did suggest a patch that (in my case) did remove the issue but I haven't heard any more about that since

**Comment by JoshStrobl** [comment] 2019-04-23 10:45
Able to reproduce. Will get it fixed in git.

**Closed** 2019-04-23 11:00 UTC
