### ISSUE TITLE
solus-project.com linked from repository home page, server not found

### ISSUE THREAD

**Issue by grahamperrin** [solus-project/budgie-desktop#2151] opened 2021-06-29 05:42 UTC
https://github.com/solus-project/budgie-desktop 

* refers to https://solus-project.com/ – server not found
* should (I assume) refer to https://getsol.us/

![image](https://user-images.githubusercontent.com/192271/123743056-928ecb80-d8a4-11eb-8087-1e3450088d41.png)

![image](https://user-images.githubusercontent.com/192271/123743414-22347a00-d8a5-11eb-9133-5272b36cef5e.png)

```text
% drill -V 5 solus-project.com
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 0
;; flags: rd ; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; solus-project.com.   IN      A

;; ANSWER SECTION:

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 0 msec
;; WHEN: Tue Jun 29 06:39:28 2021
;; MSG SIZE  rcvd: 0
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 56198
;; flags: qr rd ra ; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0 
;; QUESTION SECTION:
;; solus-project.com.   IN      A

;; ANSWER SECTION:

;; AUTHORITY SECTION:
solus-project.com.      544     IN      SOA     dns1.registrar-servers.com. hostmaster.registrar-servers.com. 1573501634 43200 3600 604800 3601

;; ADDITIONAL SECTION:

;; Query time: 1 msec
;; SERVER: 192.168.1.1
;; WHEN: Tue Jun 29 06:39:28 2021
;; MSG SIZE  rcvd: 105
% uname
FreeBSD
% 
```

**Comment by guillotjulien** [comment] 2021-06-29 05:44
Duplicate of https://github.com/solus-project/budgie-desktop/issues/1806. Unfortunately it cannot be changed.

**Comment by grahamperrin** [comment] 2021-06-29 05:44
Srange, I sought a duplicate before posting. Apologies for the noise.

**Closed** 2021-06-29 05:45 UTC
