### ISSUE TITLE
Dragging files to taskbar not opening (maximising) minimised applications

### ISSUE THREAD

**Issue by ayanb1991** [solus-project/budgie-desktop#1217] opened 2017-10-26 09:36 UTC
**Operating System :** Ubuntu Budgie 17.10
**Budgie version:** budgie-desktop 10.4

**The issue encountered**
Dragging files to minimised application icon in the taskbar not opening  (maximising) the app.

**Steps to reproduce the issue**
1.Open Gedit
2.Minimise it to taskbar (Icon Task List) section
3.Drag a .txt files to the gedit App Icon in "Icon Task List" section " and the file will neither maximise gedit or open it in gedit.

**Comment by jmgomezpoveda** [comment] 2018-05-02 15:06
This is a common behaviour in most DE and OS. Being used to it myself, I find its absence a usability issue. I hope the team is able to implement this feature.

**Comment by triorr** [comment] 2019-02-08 01:28
This is doable by adding a 'on_drag_motion' function to 'IconButton.vala' file the only problem is it will break  the icons reordering capability . Maybe if someone  smarter than me take a look at it . I think this is highly doable.

**Comment by triorr** [comment] 2019-02-08 01:43
Duplicate of #697

**Closed** 2019-02-08 15:51 UTC
