### ISSUE TITLE
Change default behavior of the music applet in Raven to be expanded

### ISSUE THREAD

**Issue by tristan957** [solus-project/budgie-desktop#561] opened 2016-09-06 04:54 UTC
Currently for me at least, the default behavior of the music applet in Raven is collapsed. I think the default behavior should be changed to expanded. Thoughts. I can only speak for this happening with Spotify because I don't have local music to try this with.

**Comment by mussel** [comment] 2016-10-02 23:37
I did some digging on this and I think the problem is that Raven sets the expanded state of the mpris client based on the can_quit property of the Player, in this case Spotify. (See lines 85 & 86: https://github.com/solus-project/budgie-desktop/blob/master/raven/mpris/MprisGui.vala#L86)

To default mpris clients to start expanded, we just need to change line 86:
```vala
player_revealer.expanded = true;
```

However, there is also another problem that I noticed. The expanded state of the Spotify music applet and its HeaderExpander button do not match. 
![selection_001](https://cloud.githubusercontent.com/assets/1262461/19024543/18a7ea94-88dc-11e6-8972-4009bbace80b.png)
Even though the applets are collapsed in the screenshot above, their buttons are in a "expanded" state. This happens because changes to the expanded state of HeaderWidget are not propagated to the HeaderExpander button. So, in the aforementioned line (MprisGui.vala#L86) when we set the applet to be not expanded the button will remain with its default state: expanded.

So I made two patches to address these issues:
https://gist.github.com/mussel/44d744cb9220733abd0fb23fda9bc52b
and
https://gist.github.com/mussel/fa6940ca5852d80cbde79f65196ddc49


What do you think @ikeydoherty ?

**Comment by tristan957** [comment] 2016-10-03 17:01
Wow. Nice problem solving man.

**Comment by ikeydoherty** [comment] 2016-10-18 04:16
Merged! Thanks @mussel <3

**Closed by ikeydoherty** 2016-10-18 04:16 UTC

**Comment by tristan957** [comment] 2016-10-18 04:51
Nice job!

**Comment by mussel** [comment] 2016-10-18 08:31
No prob @ikeydoherty ;)
But the PR you merged had only the first patch for the mismatch bug. I did not include the second one because I didn't know if you agreed with all Raven Mpris clients starting expended.
I'll create a new PR with that patch.

**Comment by ikeydoherty** [comment] 2016-10-18 16:16
Will happily merge
