### ISSUE TITLE
Budgie - Panel - System Tray Applet - Icon Overlap on boot

### ISSUE THREAD

**Issue by Umlatt** [solus-project/budgie-desktop#1927] opened 2020-01-21 07:20 UTC
## Description
When booting into Solus (Budgie), as standard apps are started, app icons or overlayed on one another with artifacting in the panel (system tray applet - bottom).

Work around is to go to settings and move the panel to another edge of the screen and back.
However, some of the started apps are no longer visible (moving the system tray applet to middle and back shows that there are gaps where the running apps should be).

## Budgie version

budgie-desktop 10.5.1
Copyright © 2014-2019 Budgie Desktop Developers
*This issue has existed for several months now (system is updated after friday update release cycle).
## Operating system

Solus 4.0 - Fortitude

## Steps to reproduce the issue

Boot into Solus

## Actual result

Post boot (no actions taken)
![Screenshot from 2020-01-21 09:02:19](https://user-images.githubusercontent.com/44724035/72783269-aef9f380-3c2e-11ea-8f99-b40c11bda5d9.png)
Workaround - Move panel to different edge of screen and return to original.
![Screenshot from 2020-01-21 09:06:19](https://user-images.githubusercontent.com/44724035/72783276-b15c4d80-3c2e-11ea-90d3-375f70b7099a.png)
Test - Move task manager applet from end to middle back to end (shows allocated space for app icons, but no icons).
![Screenshot from 2020-01-21 09:15:16](https://user-images.githubusercontent.com/44724035/72783280-b3261100-3c2e-11ea-9a5e-12cab5cfe85f.png)

## Expected result
Will attempt to get a healthy boot and will add later, if possible.

**Comment by Umlatt** [comment] 2020-01-21 07:29
It seems that the second test (had not attempted before creating the ticket) may have actually forced the system tray applet to reconfigure itself.
Having rebooted several times since creating the ticket (since moving the task manager applet between regions in the panel), the issue appears to be resolved.

This system has been running for nearly 2 years now, so it may have been a non-optimal upgrade that caused the issue.

I will update the bug report, if the issue returns.

**Comment by JoshStrobl** [comment] 2020-01-21 10:41
Duplicate of #1249

**Closed by JoshStrobl** 2020-01-21 10:41 UTC
