### ISSUE TITLE
Please update all links from solus-project.com to getsol.us

### ISSUE THREAD

**Issue by Neustradamus** [solus-project/budgie-desktop#2154] opened 2021-07-15 18:50 UTC
Please update all links from solus-project.com to getsol.us

And use only one organization instead of 2:
- https://github.com/solus-project
- https://github.com/getsolus

**Comment by guillotjulien** [comment] 2021-07-15 18:59
Duplicate of https://github.com/solus-project/budgie-desktop/issues/1806. Unfortunately it cannot be changed.

**Comment by Neustradamus** [comment] 2021-07-15 21:25
https://twitter.com/neustradamus/status/1415782903326334980

**Comment by guillotjulien** [comment] 2021-07-15 21:46
I think you understood wrong here. First this organization only manage Budgie code, second DataDrake is still very active on Solus (ferryd, libeopkg, ypkg, etc), third no one in their right mind would give administrative access to an organization to someone pinging them randomly on twitter...

**Comment by Neustradamus** [comment] 2021-07-15 22:33
@guillotjulien: Please read 1806, the problem is that only this person has ownership on the organization.
It is for this that all people can not edit the organization.
I have requested rights to change it because no people has requested since several years.
I am here to solve team problem which exist since several years.

When you can see, there is no commit since 2018 in the organization: https://github.com/search?q=org%3Asolus-project+DataDrake&type=commits

**Comment by Neustradamus** [comment] 2021-07-15 22:42
First, @DataDrake is not showed in people list.
- https://github.com/orgs/solus-project/people
- https://github.com/orgs/getsolus/people

I see some commits in the second organization:
- https://github.com/search?q=org%3Agetsolus+DataDrake&type=commits

I think it is time to harmonize all in only one organization.
And edit all repo descriptions with the good link, etc.

Note: The transfer from one organization to another one adds a redirection (no lost).

In the bad organization which become empty (all will be in the good organization), add in description : "Go to the good place".

**Comment by EbonJaeger** [comment] 2021-07-15 22:51
@Neustradamus you have missed where it is not possible because the person who holds solus-project (which is not DataDrake, by the way) never did so or gave anyone else access to do so. And then they left the project. Further, it has been stated by @JoshStrobl that Budgie 11 will be in a new repository, so this is all moot regardless.

To reiterate:
1) No one with Solus has the ability to change repository descriptions or links in the solus-project organization.
2) In the future, the Budgie repo will no longer be in the old solus-project organization.

**Comment by Neustradamus** [comment] 2021-07-15 23:47
Ah sorry, I did not read well!
- https://github.com/solus-project/budgie-desktop/issues/1806#issuecomment-487542729

If there is no owner in the current organization, the current leader can contact @github directly here:
- https://support.github.com/contact/account, here I think
- https://github.community/

@steveward is a good GitHub staff member, maybe he can help the project.

**Comment by EbonJaeger** [comment] 2021-07-15 23:52
Josh and DataDrake have been down this road before, and unfortunately it went nowhere. It is what it is, I'm afraid.

**Closed** 2021-07-16 01:48 UTC

**Comment by JoshStrobl** [comment] 2021-07-16 01:51
>I have requested rights to change it because no people has requested since several years.

This is not something I have consented to, as the main contributor to the repo. I have already been in discussions with GitHub on the matter and there is nothing they can do that would not be in violation of their policies.

Do not engage in actions on our behalf.
