### ISSUE TITLE
Application Windows hiding under top budgie panel

### ISSUE THREAD

**Issue by snugglej** [solus-project/budgie-desktop#869] opened 2017-04-20 01:59 UTC
Operating system: Budgie-remix (Ubuntu Budgie 17.04)
**Budgie version**: i.e. Budgie 10.2.9-3ubuntu4

budgie-desktop --version output: budgie-desktop 10.2.9
Copyright © 2014-2016 Ikey Doherty, Solus Project

I have some applications (chromium and vivaldi) who use different window styling than the standard gtk theme. When I am in a non-maximized window and I move the window around it will pop under the top budgie panel and I will be unable to move it back or access the buttons (minimize, full screen, close) unless I adjust the size of the panel. If you have a larger panel it can hide even more of the top of the application window. This will also happen if I'm going from maximized to the "normal" window size [but not always]

I have made my top panel smaller to compensate so I don't have it happen as frequently. 

![screenshot from 2017-04-19 20 55 41](https://cloud.githubusercontent.com/assets/17776110/25209783/ce57a458-2542-11e7-937f-c65bb6bc2621.png)

 ...

**Steps to reproduce the issue**
1. Open an application such as chormium
2. Make sure you are not maximized and move the window up to the top budgie panel
3. Wait for it to snap and then continue moving it up
4. The window will be under the top budgie panel and if you release the mouse you will not be able to move it back from under there without shrinking the top panel.
 ...

**Comment by persy** [comment] 2017-08-06 09:15
I have a similar issue, setting the panel to the bottom, with maximized windows and with all types of application (Nautilus, Firefox..)

![immagine](https://user-images.githubusercontent.com/5536427/29001968-82b9ca1c-7a97-11e7-9262-4efce29b71e9.png)

![immagine](https://user-images.githubusercontent.com/5536427/29001995-41b3ccf6-7a98-11e7-9d4b-e0ff4b65ba4a.png)

![immagine](https://user-images.githubusercontent.com/5536427/29002005-7df3cd88-7a98-11e7-824e-93cd1731541f.png)

**Comment by Kabouik** [comment] 2017-08-19 23:06
I have a similar issue with Budgie 10.4 and all windows. When maximized, they expand over the whole screen area, instead of being constrained by the top panel, resulting in window titles being hidden underneath the panel. **The issue goes away if I disable my secondary monitor.**

Not sure this is relevant, but it might: the secondary monitor is oriented in portrait and its top edge of is higher than the top edge of the primary monitor (*i.e.*, the minimal y coordinate is lower than on secondary monitor than on primary monitor).

**Comment by Spirotot** [comment] 2017-11-08 22:34
Also experiencing this issue.... I have 3 monitors, and if any of them are positioned so that any portion of them is "below" the primary monitor (the one with the Budgie panel), windows will hide behind the Budgie panel, even when maximized.

**Comment by rgoliveira** [comment] 2017-11-09 16:40
+1

![image](https://user-images.githubusercontent.com/1731173/32617332-dfc8fc00-c55b-11e7-8101-241dec06628a.png)

**Comment by leopck** [comment] 2017-11-23 22:35
+1

Connecting 3 displays would occasionally cause this issue for me as well.

**Comment by markopolo123** [comment] 2017-12-13 11:41
I have two screens attached via display port to my laptop. Maximised windows go under the panel, no matter where the panel is. 

![screenshot showing problem](https://user-images.githubusercontent.com/698889/33937219-821b4388-dffa-11e7-8b5b-e4206a65e820.png)

**Comment by gonzalezroda** [comment] 2017-12-19 18:49
+1
I have the same problem using dual monitors and only happens when the panel is on top, everything works fine when is on the bottom.

**Comment by SneWs** [comment] 2018-01-12 22:07
+1 - Same issue here but when the panel is docked to bottom. However, when aligning my two monitors under Display setup to the bottom edge everything works as expected. I suspect that this is due to my main monitor being 1080 in height and the secondary being 1280.

**Comment by kaaylim** [comment] 2018-01-17 23:25
+1 Same issue.  And I only use one monitor.
Top panel or left panels need to be at least 55 in size. If less, the panels cover the windows more and more as I decrease the size of the panel.

**Comment by Ryu-CZ** [comment] 2018-02-26 11:43
+1 same issue. 
Windows i hidden behind panel when  _virtual screen space_ border is not aligned with panel position

With _virtual screen space_ I mean actual in memory image created as rectangular bounding box of joined monitors:
![virtualspace](https://user-images.githubusercontent.com/12214459/36668704-6eb2a6fa-1af2-11e8-8383-675cce8549ef.png)
.


* **Problematic setting example:**
![screenshot from 2018-02-26 12-25-52](https://user-images.githubusercontent.com/12214459/36668032-3dfd71ae-1af0-11e8-9c3d-749d56fa55b9.png)

* **HotFix** until panel is fixed: Align panel with border of _virtual screen space_. Example for BOTTOM PANEL on LEFT monitor.
![screenshot from 2018-02-26 12-35-25](https://user-images.githubusercontent.com/12214459/36668450-a441298c-1af1-11e8-815e-031209e5ec35.png)

**Comment by guillefar** [comment] 2018-03-16 11:38
Not sure if it is the same bug, but I have a similar problem, the programs (Firefox for example), maximize all the way and not just until the bottom panel. However, it the rest of monitor the aligning work as expected (not leaving any space for the panel they don't have)

**Comment by GrindamN** [comment] 2018-03-18 10:35
Try to remove raven sidebar applet. Is the problem still happening after that?

**Comment by guillefar** [comment] 2018-03-19 15:44
@GrindamN You mean the one that shows an arrow icon? If that is the case, yes, I removed it and it is still happening (didn't restart budgie though, should I?).

**Comment by GrindamN** [comment] 2018-03-19 15:52
Try to restart it. If it doesn't work, try to reset it. Worked for me for some strange reason.

**Comment by guillefar** [comment] 2018-03-19 17:25
@GrindamN Didn't work for me. Run 

`budgie-panel --reset --replace&`

But still having the same issue

**Comment by Kabouik** [comment] 2018-03-20 14:45
This is probably a duplicate of #844 by the way (and there could be others). Not sure which of both threads has the most details on the issue at the moment.

**Comment by guillefar** [comment] 2018-03-21 17:01
Just discovered that Budgie is leaving the space for the panel in my screen 2 (see image attached), not in the 3, as it should. 
![budgie_panel_problem](https://user-images.githubusercontent.com/1972792/37724782-cf402230-2d31-11e8-9fe6-639e6ebc86ee.png)

**Comment by gjoris** [comment] 2018-04-29 19:01
I have this issue too, though, I found a workaround on my laptop. Working on Ubuntu 18.04 Budgie, I noticed when I resize my top panel to 50 pixels in size fixes this issue. At that point, all windows start respecting the boundaries of the top panel. The screen on my laptop has a resolution of 1920x1080. The top panel is now larger than I'd like it to be, but it's perfectly usable like this. From size 50 on, the behaviour remains stable and as expected. 

I noticed this first when just playing around with the size when I stuck the panel to the right. On the right and at the bottom, the panel "disappeared" into the edges of my screen. Perhaps the position of the panel has some issue on lower sizes of the panel?

Anyone else can confirm?

**Comment by letsbetogether** [comment] 2018-05-07 06:58
@gjoris The workaround does not work for me (18.04, left monitor a bit lower than the right one). 

I'd like to have the bar to be at the boundary of either one of the other monitors but that is making my windows clip on the other monitor. I used to be able to have the bar on the left monitor, at the middle of right border, and all windows act normally on 17.10, however.

The problem does not appear if the bar is at the outer edges of the combined workspace (top/bottom or far side of either monitor).

**Comment by happycod3r** [comment] 2018-07-30 23:50
+1
same issue with dual monitor and panel on the bottom

**Comment by Falconw** [comment] 2018-08-26 20:55
A temp fix is to align all monitors to the top edge of each other and not mid or bottom.

This fixed it for me for now.  It seems that ubuntu cast the largest monitor size on all other smaller size monitors, thus, it doesn't recognize the actual space allocated for the Top panel.

Cheers.

**Comment by mattogodoy** [comment] 2018-08-29 11:01
@Falconw you are right! I guess you found the reason.

I now have my monitors missaligned though... Let's hope for a fix soon.

**Comment by ToppestOfDogs** [comment] 2018-11-02 05:12
This is still a problem. I can't align my monitors because they're not lined up in real life, so my cursor would go all over the place if I did that
![screenshot from 2018-11-02 01-07-40](https://user-images.githubusercontent.com/17092742/47895003-5a593580-de3c-11e8-891c-195bad00805f.png)

**Comment by TheRealAgentK** [comment] 2018-11-21 07:50
I can confirm @Falconw's workaround fixes the immediate problem, but it not a proper solution to the issue. Really annoying to essentially not be able to align the virtual screens with physical layout.

**Comment by spiritstr** [comment] 2018-11-22 19:03
The workaround works for top panel, using a bottom panel would be the inverse, but if you're using bottom panel and the monitors are aling on top, nautilus and other softwares can still be overlaped by the panel, if you're aling them based on the bottom position, icons on desktop would go above your screen.

**Comment by XSmile2008** [comment] 2018-12-16 19:56
I have the same issue. I've set upped my laptop screen to be bottom primary screen and external monitor to be on top of laptop screen. How when I maximize windows on each monitor, I've got some empty space line on my external monitor and windows on builtin monitor goes under my top budgie panel. Any ideas or workarounds how to solve this?
![screenshot from 2018-12-16 21-50-00](https://user-images.githubusercontent.com/5782908/50058186-592a6080-017d-11e9-85c1-dfd7bd7f39ee.png)

**Comment by megamorf** [comment] 2018-12-25 23:20
I'm also affected by this and unfortunately the suggested solutions haven't worked for me :-1:

**Comment by jvacek** [comment] 2019-01-11 15:12
Hey, I've been fiddling around with this too and I think my issue was coming from the top panel's height not being set right, so I've put it to a high number and then shrank it down until the panel stopped shrinking. I could set the height to a really small number and it wouldn't change the size, so I'm assuming this wasn't working for the display but was working for the windows "offset" from the top. Hope this might help some.

**Comment by smckend** [comment] 2019-01-21 10:43
+1 haven't been able to fix things up with the suggestions. 

budgie-desktop version 10.5

![screenshot-top-panel-issue](https://user-images.githubusercontent.com/13231875/51469464-af3c8600-1d71-11e9-8633-7daaf52abce7.jpg)

**Comment by Xenchrarr** [comment] 2019-01-25 09:20
+1 I have the same issue. Changing the top bar size does nothing.

**Comment by dave-c-vt** [comment] 2019-03-01 00:54
bump... started happening as soon as a second monitor was attached. No fix found yet.

**Comment by gerstepe** [comment] 2019-03-23 00:23
+1 having the same issue with second monitor placed higher in display arrangement.

**Comment by JoshStrobl** [comment] 2019-03-23 10:20
Locking this issue, please stop bumping it. It will not be addressed until Budgie 11.

**Closed** 2019-12-18 11:57 UTC
