### ISSUE TITLE
Budgie desktop crashed when trying to move Budgie search using Meta key

### ISSUE THREAD

**Issue by prateekmedia** [solus-project/budgie-desktop#2079] opened 2020-12-19 10:28 UTC
## Description
When trying to move the budgie search(The one that pops up after Alt+F2) using meta key , it crashes the budgie desktop, although the budgie search is not movable or free like that of kde one but still this should not be the behaviour of it.

## Expected result
It should move to a location or simply doesn't crash the whole desktop

## Operating system
Solus 4.1 with Budgie 10.5.2

```
budgie-wm[24423]: meta_window_is_focusable: assertion '!window->unmanaging' failed
budgie-wm[24423]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
budgie-wm[24423]: meta_window_is_focusable: assertion '!window->unmanaging' failed
budgie-wm.desktop[24423]: **
budgie-wm.desktop[24423]: mutter:ERROR:../src/core/window.c:5505:meta_window_get_workspaces: code should not be reached
audit[24423]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=3 subj==unconfined pid=24423 comm="budgie-wm" exe="/usr/bin/budgie-wm" sig=6 res=1
budgie-wm.desktop[24423]: Bail out! mutter:ERROR:../src/core/window.c:5505:meta_window_get_workspaces: code should not be reached
gnome-session[24238]: gnome-session-binary[24238]: WARNING: Application 'budgie-wm.desktop' killed by signal 6
gnome-session-binary[24238]: WARNING: Application 'budgie-wm.desktop' killed by signal 6
```

_Logs and Confirmation by @EbonJaeger in https://github.com/solus-project/budgie-desktop/issues/2079#issuecomment-748501322_

**Comment by EbonJaeger** [comment] 2020-12-19 15:01
I can't get it to crash for me. How exactly are you trying to move it?

**Comment by prateekmedia** [comment] 2020-12-19 15:03
> I can't get it to crash for me. How exactly are you trying to move it?

Okay if you don't like to move it just press meta key and immediately click on the Alt+F2 search bar(Whatever it is called), the click should be immediate else it may open budgie-menu

**Comment by prateekmedia** [comment] 2020-12-19 15:29
@EbonJaeger Any Updates?

**Comment by EbonJaeger** [comment] 2020-12-19 17:25
Confirmed crash when holding the meta key and dragging the window twice. The instant kill and logout is making getting more useful details (such as a backtrace) tricky. I see this in the journal from when the crash occurs:
```
Dec 19 12:10:34 emaddock-laptop-solus budgie-wm[24423]: meta_window_is_focusable: assertion '!window->unmanaging' failed
Dec 19 12:10:34 emaddock-laptop-solus budgie-wm[24423]: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
Dec 19 12:10:34 emaddock-laptop-solus budgie-wm[24423]: meta_window_is_focusable: assertion '!window->unmanaging' failed
Dec 19 12:10:34 emaddock-laptop-solus budgie-wm.desktop[24423]: **
Dec 19 12:10:34 emaddock-laptop-solus budgie-wm.desktop[24423]: mutter:ERROR:../src/core/window.c:5505:meta_window_get_workspaces: code should not be reached
Dec 19 12:10:34 emaddock-laptop-solus audit[24423]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=3 subj==unconfined pid=24423 comm="budgie-wm" exe="/usr/bin/budgie-wm" sig=6 res=1
Dec 19 12:10:34 emaddock-laptop-solus budgie-wm.desktop[24423]: Bail out! mutter:ERROR:../src/core/window.c:5505:meta_window_get_workspaces: code should not be reached
Dec 19 12:10:34 emaddock-laptop-solus gnome-session[24238]: gnome-session-binary[24238]: WARNING: Application 'budgie-wm.desktop' killed by signal 6
Dec 19 12:10:34 emaddock-laptop-solus gnome-session-binary[24238]: WARNING: Application 'budgie-wm.desktop' killed by signal 6
```

**Comment by JoshStrobl** [comment] 2021-04-12 15:16
Not able to reproduce this when using Budgie Desktop under the GNOME 40 Stack with Mutter 40. Regardless, this would be a mutter issue and not necessarily specific to Budgie. Going to close it, welcome to have folks try to reproduce it again when GNOME 40 stack hits unstable.

**Closed by JoshStrobl** 2021-04-12 15:16 UTC
