### ISSUE TITLE
With "Task list" Opening a lot of windows will push other applets off the screen

### ISSUE THREAD

**Issue by Sa-ghosts** [solus-project/budgie-desktop#1888] opened 2019-10-14 17:31 UTC
## Description

if you add "Task list" to the panel and open a lot of windows it will push other applets off the screen

Other applets (like system tray, notifications, status indicators ...etc)

## Budgie version

budgie-desktop 10.5.1

## Operating system

Solus 4, up to date (14/10/2019)

## Steps to reproduce the issue

1) add the "Task list" applet to the panel
2) open lots of windows

## Actual result

Other applets will get pushed off the screen.
![Screenshot from 2019-10-14 20-28-40](https://user-images.githubusercontent.com/35840250/66770836-3e219d80-eec1-11e9-8f57-8ba8c2d1b7be.png)

## Expected result
"Task list" windows will get smaller and would not change other applets position.

**Comment by JoshStrobl** [comment] 2019-10-14 17:33
Duplicate of #83, please use search functionality.

**Closed by JoshStrobl** 2019-10-14 17:33 UTC
