### ISSUE TITLE
Icon-only Task List: some icons "flashes" when mouse keeps over them

### ISSUE THREAD

**Issue by ghost** [solus-project/budgie-desktop#318] opened 2016-01-14 10:00 UTC
- Better explained here:

https://www.youtube.com/watch?v=Gda865461-M

- Note that also window name is not shown

- This not occurs with normal Task List or using GTK3 applications

- The applications that I've tested and has this issue are all GTK2 and Qt5:
 - Firefox
 - Atom
 - Chrome
 - HexChat
 - LibreOffice
 - SimpleScreenRecorder

- For one reason, Telegram Desktop has not any problem

**Comment by ikeydoherty** [comment] 2016-01-24 12:33
This should be fixed in latest git if you wanna confirm

**Comment by JoshStrobl** [comment] 2016-04-08 22:13
Not resolved as of master.

**Comment by ikeydoherty** [comment] 2016-10-26 03:51
Certainly fixed now right?

**Comment by JoshStrobl** [comment] 2016-10-26 04:56
Yea can't reproduce it at this point.

**Comment by ikeydoherty** [comment] 2016-10-26 05:00
Ta

**Closed by ikeydoherty** 2016-10-26 05:00 UTC
