### ISSUE TITLE
Arch Linux: CSD applications doesn't have all window buttons

### ISSUE THREAD

**Issue by feskyde** [solus-project/budgie-desktop#328] opened 2016-01-25 06:29 UTC
![captura de pantalla de 2016-01-25 03-26-08](https://cloud.githubusercontent.com/assets/12128317/12543944/9226b86c-c313-11e5-9f31-0101ddb74bcb.png)

I just fixed it with `gsettings set org.gnome.desktop.wm.preferences button-layout 'appmenu:minimize,maximize,close'` (from the GNOME Flashback site)

**Comment by ikeydoherty** [comment] 2016-01-25 13:46
Dupe of #261

**Closed by ikeydoherty** 2016-01-25 13:46 UTC
