### ISSUE TITLE
No way to choose a non latin input method

### ISSUE THREAD

**Issue by jobucaldas** [solus-project/budgie-desktop#1986] opened 2020-06-02 15:09 UTC
## Description
There's no way to choose a input source that uses a non latin alphabet.

## Budgie version
budgie-desktop 10.5.1

## Operating system
Solus 4.1

## Steps to reproduce the issue
Install ibus-mozc, ibus-libpinyin or ibus-hangul and add either one to the input sources on the gnome settings.

![input](https://user-images.githubusercontent.com/37675609/83536015-17a08900-a4c9-11ea-8b7f-59436a0b2621.png)

## Actual result
It's not possible to change to those input methods, neither with the applet nor with the set keyboard shortcut, removing all latin input methods changes the layout to en_US.

![selector](https://user-images.githubusercontent.com/37675609/83536058-2424e180-a4c9-11ea-816f-abda70759dd4.png)

## Expected result
The applet shows these input methods and using it or the set keyboard shortcut changes to the selected method, removing latin input methods changes your current layout to the next layout currently added.

## Additional information
After running
```
ibus exit
ibus-daemon &
```
it's possible to use other input methods through the ibus appindicator, although it's still needed to add the layouts to ibus separately and the keyboard applet still doesn't show any non latin input method.

![fix](https://user-images.githubusercontent.com/37675609/83536164-40288300-a4c9-11ea-9f15-58f371023a8e.png)

**Comment by fossfreedom** [comment] 2020-06-07 13:41
This is a duplicate of https://github.com/solus-project/budgie-desktop/issues/269

**Closed** 2020-10-09 16:11 UTC
