### ISSUE TITLE
Menu is not fully visible on 4k screen

### ISSUE THREAD

**Issue by maxlorenz** [solus-project/budgie-desktop#1233] opened 2017-10-31 13:59 UTC
![screenshot from 2017-10-31 14-54-31](https://user-images.githubusercontent.com/2054706/32227387-902ba876-be4b-11e7-8caa-b705673e7fc7.png)

**Operating System**: Solus 3.26.1
**Budgie version**: Budgie 10.4

**The issue encountered**

See screenshot. Only the top left quarter of the start menu is visible.

**Steps to reproduce the issue**

Standard Solus install, plugged in to 4k monitor, opened menu. Tried again after restart

**Comment by JoshStrobl** [comment] 2020-10-09 12:20
Unable to reproduce with my 4K monitor with latest Budgie, closing.

**Closed by JoshStrobl** 2020-10-09 12:20 UTC
