### ISSUE TITLE
Multiple displays arrangement

### ISSUE THREAD

**Issue by jabaa** [solus-project/budgie-desktop#1950] opened 2020-03-22 17:43 UTC
## Description
I'm using two displays with different resolution and geometries. I'm not able to arrange the display so that all icons are shown on the desktop and the windows are not overlapped by the panel

## Budgie version
Budgie Desktop 10.4+git20171031.10.g9f71bb8-1.2ubuntu1.2

## Operating system
Ubuntu Budgie 18.04 bionic

## Steps to reproduce the issue
1. Arrange two diplays: left display 17'' 1920x1080, right display 32'' 2560x1440
2. Set left display as primary display
3. Align top edges of the displays and maximize a window on left display. Window is overlapped by panel
4. Align bottom edges of display and organize desktop icons by names. Desktop icons are moved out of range.

## Actual result
![DesktopTopAlign](https://user-images.githubusercontent.com/6706626/77256087-49e16f00-6c6c-11ea-88d3-cf93fc2f4c19.png)
![WindowTopAlign](https://user-images.githubusercontent.com/6706626/77256089-4e0d8c80-6c6c-11ea-9916-c17de92fe60a.png)

The browser is overlapped by the panel if the displays are aligned at the bottom edge. You can't see the bread crumbs at the bottom of firefox. But the icons can be automatically aligned by names.

![DesktopBottomAlign](https://user-images.githubusercontent.com/6706626/77256093-51a11380-6c6c-11ea-8f13-a603ce3fed77.png)
![WindowBottomAlign](https://user-images.githubusercontent.com/6706626/77256098-549c0400-6c6c-11ea-8ce1-24c421b7b395.png)

The browser is not overlapped by the panel if the displays are aligned at the top edge but the icons are moved out of display view when automatically aligned by names.

Even the date and time widget on the desktop moves depending on the alignment.

## Expected result
All icons can be automatically aligned on the desktop and the windows aren't overlapped by the panel. The margin/padding of the panel is only applied if the displays are aligned at the bottom edge. The date and time widget should not change the position.

**Comment by jabaa** [comment] 2020-03-22 17:49
I can workaround the problem by movin the panel to the top and align the displays at the top edge.

**Comment by JoshStrobl** [comment] 2020-03-25 01:54
Duplicate of #1099 and #1625

**Closed by JoshStrobl** 2020-03-25 01:54 UTC
