### ISSUE TITLE
Budgie Menu, Panel & WiFi Issues, After Resume

### ISSUE THREAD

**Issue by m5kR10bHxS** [solus-project/budgie-desktop#1893] opened 2019-10-29 19:27 UTC
## Description
Various applications and widgets are inoperative, after the machine has a period of inactivity. The wifi is also inoperative, when the problem persents itself. 

## Budgie version
10.5.1

## Operating system
Solus 4

## Steps to reproduce the issue
Boot the machine and walk away. 

## Additional information
Starting approximately two weeks ago, one of my laptops started having issues with the Budgie menu and the panel after the machine automatically suspends a few times. Upon resume, some programs will launch from the menu and some will not. It always seems to be the same programs which will either launch, or not launch. Ditto for the three, or four launchers that I have on the panel, as well as several panel widgets.

I find that only a reboot, or issuing:

`$ nohup budgie-panel --replace&`

will reestablish menu, launcher and wifi functionality. Note, that I may need to issue this command 2-5 times, before functionality is restored. Some widgets, such as the wifi widget will disappear all together and not return, even after the desktop is restarted. My wifi connection, itself, will generally be inoperative, until I restart the desktop. Sometimes the wifi widget, Steam, icon, Hexchat icons in the System Tray will periodically appear, but if I place the cursor over top of them, they will disappear again. The Notification bell icon randomly will be blue, or white, regardless of whether there is a notification pending, or not. Also when the problem is present, it may take 2-3 clicks, before the raven panel will open.

During the course of diag, I disabled suspend and the problem still persists. The problem happens randomly, after resuming from hibernate, sleep, or merely after a period of inactivity.
This machine is a ThinkPad T420. Last week I updated my ThinkPad T440p and it is now exhibiting the same problem.

Here is some related traffic from the Solus forum:
https://discuss.getsol.us/d/2949-applications-cannot-launch-from-panel/2
https://discuss.getsol.us/d/2850-shutdown-applet-raven-sidebar-unresponsive-after-wake/2

This bug report sounds similar:
https://github.com/solus-project/budgie-desktop/issues/1890

Here is an interesting excerpt from the journal, which I copied after the last incident. I haven’t verified it 100%, but the following error messages repeat throughout my log and appear to coincide with the problem:
Oct 27 03:02:03 galileo systemd-sleep[16658]: Failed to connect to non-global ctrl_ifname: (nil) error: No such file or directory
Oct 27 03:02:03 galileo [16659]: /usr/lib64/systemd/system-sleep/wpa_supplicant.sh failed with exit status 255.

Log extract:
Oct 27 03:02:03 galileo NetworkManager[586]: <info> [1572163323.6455] manager: sleep: sleep requested (sleeping: no enabled: yes)
Oct 27 03:02:03 galileo NetworkManager[586]: <info> [1572163323.6456] manager: NetworkManager state is now ASLEEP
Oct 27 03:02:03 galileo systemd[1]: Reached target Sleep.
Oct 27 03:02:03 galileo systemd[1]: Starting Suspend...
Oct 27 03:02:03 galileo systemd-sleep[16658]: Failed to connect to non-global ctrl_ifname: (nil) error: No such file or directory
Oct 27 03:02:03 galileo [16659]: /usr/lib64/systemd/system-sleep/wpa_supplicant.sh failed with exit status 255.
Oct 27 03:02:03 galileo systemd-sleep[16658]: Suspending system...
Oct 27 03:02:03 galileo kernel: PM: suspend entry (deep)
Oct 27 08:27:04 galileo kernel: Filesystems sync: 0.010 seconds
Oct 27 08:27:04 galileo kernel: Freezing user space processes ... (elapsed 0.002 seconds) done.
Oct 27 08:27:04 galileo kernel: OOM killer disabled.
Oct 27 08:27:04 galileo kernel: Freezing remaining freezable tasks ... (elapsed 0.001 seconds) done.
Oct 27 08:27:04 galileo kernel: printk: Suspending console(s) (use no_console_suspend to debug)
Oct 27 08:27:04 galileo kernel: wlp1s0: deauthenticating from 80:2a:a8:98:0c:37 by local choice (Reason: 3=DEAUTH_LEAVING)
Oct 27 08:27:04 galileo kernel: sd 0:0:0:0: [sda] Synchronizing SCSI cache
Oct 27 08:27:04 galileo kernel: sd 0:0:0:0: [sda] Stopping disk
Oct 27 08:27:04 galileo kernel: e1000e: EEE TX LPI TIMER: 00000011
Oct 27 08:27:04 galileo kernel: ACPI: EC: interrupt blocked
Oct 27 08:27:04 galileo kernel: ACPI: Preparing to enter system sleep state S3
Oct 27 08:27:04 galileo kernel: ACPI: EC: event blocked
Oct 27 08:27:04 galileo kernel: ACPI: EC: EC stopped
Oct 27 08:27:04 galileo kernel: PM: Saving platform NVS memory
Oct 27 08:27:04 galileo kernel: Disabling non-boot CPUs ...
Oct 27 08:27:04 galileo kernel: smpboot: CPU 1 is now offline
Oct 27 08:27:04 galileo kernel: smpboot: CPU 2 is now offline
Oct 27 08:27:04 galileo kernel: smpboot: CPU 3 is now offline
Oct 27 08:27:04 galileo kernel: ACPI: Low-level resume complete
Oct 27 08:27:04 galileo kernel: ACPI: EC: EC started
Oct 27 08:27:04 galileo kernel: PM: Restoring platform NVS memory
Oct 27 08:27:04 galileo kernel: Enabling non-boot CPUs ...
Oct 27 08:27:04 galileo kernel: x86: Booting SMP configuration:
Oct 27 08:27:04 galileo kernel: smpboot: Booting Node 0 Processor 1 APIC 0x1
Oct 27 08:27:04 galileo kernel: CPU1 is up

I also have a Dell Inspiron laptop running Majaro / Budgie. The Budgie version is also 10.5.1. This machine has not been used for several weeks, so I updated it this morning and have I been monitoring it since. So far, it does not exhibit the problem.

**Comment by JoshStrobl** [comment] 2019-10-30 12:26
Duplicate of #1890, would appreciate you posting details there.

**Closed by JoshStrobl** 2019-10-30 12:26 UTC
