### ISSUE TITLE
[regression] panel icons missing underlines indicators, icons too low?

### ISSUE THREAD

**Issue by splace** [solus-project/budgie-desktop#1753] opened 2019-02-18 17:31 UTC
## Description
bottom panel has icon underline indicators missing. icons seem too low and push underline off screen?

## Budgie version
budgie-desktop 10.5 (git-f62524110961cbbaf6e947b8edcd5d0773e74e32)
started with last update 2 days ago

## Operating system
 Solus 3

## Steps to reproduce the issue
start up with display scale 200% (my default)

## Additional information
seems icons are too low, if size reset, by going to panel and adjusting size then returning to same setting (in this case 32.) fixes until next restart.

**Comment by LulzFTW** [comment] 2019-02-20 22:04
If you make an empty top panel with size 32, then add an Icon Task List applet, does the panel appear to expand vertically?

Does the same happen when adding a Budgie Menu applet to an empty top panel?

**Comment by splace** [comment] 2019-02-20 23:35
in neither case did the panel size change. (the numeric size value or the actual screen size.)

just to be clear, the icon offset occurs only at startup, if i just 'touch' the size, set it to its existing size, or even making the size smaller, reveals the underlines.

**Comment by splace** [comment] 2019-02-20 23:40
in neither case did the panel size change. (the numeric size value or the actual screen size.)

just to be clear, the icon offset occurs only at startup, if i just 'touch' the size, set it to its existing size, or even making the size smaller, reveals the underlines.

**Comment by splace** [comment] 2019-02-20 23:42
i also restarted with top panel in place, it worked, (showed overline) with both size 39 and size 32.

**Comment by LulzFTW** [comment] 2019-02-21 01:15
If you remove the Budgie Menu applet from your bottom panel, do the underlines appear after a restart?

**Comment by splace** [comment] 2019-02-21 01:50
may be getting somewhere,

i presume you meant remove and then re-add, when i did that, adding the menu CAUSED the underlines to disappear.

but, in case you did want me to remove and restart, i did, lines were fine, but i was stuck with no way to put it back, until i googled and found ALT F2, i then re-added the menu and we were back as before.

**Comment by LulzFTW** [comment] 2019-02-21 02:47
Hah, I forget that settings isn't accessible from the sidebar by default anymore.

I think I know the cause of this issue, except for why the lines on the Workspace Switcher would disappear. Did this bug appear in the Workspace Switcher after the last update?

**Comment by splace** [comment] 2019-02-21 14:42
well today, i no longer have the issue!

i can only guess that all the adding and removing did something, no updates. 

so currently i can't reproduce it.

but, and i maybe imagining it, the menu icon, the 3x3 grid, looks smaller than yesterday, i don't remember it having a clear gap all round like it does now, and i think it was bigger than the other icons where now it is much the same size.

**Comment by splace** [comment] 2019-02-21 14:55
i just realised i did a screen-shot a few days ago, so i have a record of how the menu icon size has changed.
yesterday (underlines are present only because i touched the size setting)
![menu1](https://user-images.githubusercontent.com/1234848/53177643-4eaa9e00-35e8-11e9-8349-9e3c61371ff8.png)

today
![menu2](https://user-images.githubusercontent.com/1234848/53177660-54a07f00-35e8-11e9-9a1e-9a2848c3dc77.png)

**Comment by splace** [comment] 2019-02-21 15:30
i also removed and re-adding the menu icon, that now works correctly.

**Comment by LulzFTW** [comment] 2019-02-21 23:47
Per my understanding, this particular issue (Budgie Menu applet ignoring size updates) should only occur with panel size exactly 32.

**Comment by splace** [comment] 2019-02-22 01:39
> Per my understanding, this particular issue (Budgie Menu applet ignoring size updates) should only occur with panel size exactly 32.

also only after an update?

**Comment by LulzFTW** [comment] 2019-02-22 02:02
> > Per my understanding, this particular issue (Budgie Menu applet ignoring size updates) should only occur with panel size exactly 32.
> 
> also only after an update?

The bug is that the Budgie Menu ignores the initial size update on startup for panel size 32, causing it to be too large and overflow the panel off the screen, taking the IconTaskList indicators with it.

This should be fixed by the patch above.

**Closed** 2019-02-22 10:57 UTC

**Comment by splace** [comment] 2019-02-22 17:57
> > also only after an update?

>The bug is that the Budgie Menu ignores the initial size update on startup for panel size 32, causing it to be too large and overflow the panel off the screen, taking the IconTaskList indicators with it.

what i was looking to do was pin down test conditions, but this does seem straight forward.
