### ISSUE TITLE
Bottom panel - menu appears at the top

### ISSUE THREAD

**Issue by Solarunit** [solus-project/budgie-desktop#612] opened 2016-09-20 19:22 UTC
Bottom panel - menu appears at the top

![Alt Text](http://i.imgur.com/QhsFf0E.gif)   

![Alt Text](http://i.imgur.com/geRRaVd.gif)

**Operating System**:  Solus 1.2.0.5
**Budgie version**: Budgie 10.2.7

**Comment by fossfreedom** [comment] 2016-09-20 19:26
duplicate of this https://github.com/solus-project/budgie-desktop/issues/292

**Comment by ikeydoherty** [comment] 2016-09-20 19:55
Please check existing issues before opening a new one.

**Closed by ikeydoherty** 2016-09-20 19:55 UTC
