### ISSUE TITLE
System tray applet doesn't show up when added

### ISSUE THREAD

**Issue by bsucker98** [solus-project/budgie-desktop#1420] opened 2018-05-05 06:56 UTC
**Operating System**: Solus 3
**Budgie version**: budgie-desktop v10.4-70-g15c960cc

**The issue encountered**
not a big deal though, when ever I add the system tray applet(only had to add once tbh, & then tested) it doesn't show up(more accurately icon doesn't appear, cause it takes space) and have to log-out or restart..
 
**Steps to reproduce the issue**

add a system tray applet to the panel, see what happens..

**Comment by bsucker98** [comment] 2018-05-08 05:28
once this applet right next to time, went wrong, just once as in the screenshot below, felt kind a related..
![screenshot from 2018-05-08 10 24 21](https://user-images.githubusercontent.com/38057676/39739327-f27ed1dc-52ad-11e8-8c73-f0ad922cfa5c.png)
_that wasn't the icon though, I changed the icon theme, hoping it might fix and then changed to default again, didn't fix & that's what happened_     
login out fixed the issue

**Comment by fossfreedom** [comment] 2018-05-08 09:28
@bsucker98 hmm - the mixed up icon was this issue but unfortunately looks like a regression has crept back in in the latest updates.

 - https://github.com/budgie-desktop/budgie-desktop/issues/1249

**Comment by bsucker98** [comment] 2018-05-08 12:33
oh! I see.. :o

**Comment by JoshStrobl** [comment] 2020-07-06 09:34
May be resolved with #1998

**Closed** 2020-10-09 20:26 UTC
