### ISSUE TITLE
Implement Options for 'Status' Applet

### ISSUE THREAD

**Issue by hadron43** [solus-project/budgie-desktop#2055] opened 2020-11-09 18:26 UTC
### Current Budgie version

10.5.1

### Use-cases

Implement options for the 'Status' applet. Right now, we don't have any customization options for the status applet. I'm using some other applet for Bluetooth indication. Thus, I would like to turn off the bluetooth indicator of the 'Status' Applet.

**Comment by JoshStrobl** [comment] 2020-11-10 13:38
Basically a duplicate of #455

**Closed by JoshStrobl** 2020-11-10 13:38 UTC
