### ISSUE TITLE
Nautilus doesn't open new window on middle click

### ISSUE THREAD

**Issue by drakovyrn** [solus-project/budgie-desktop#1629] opened 2018-11-25 20:24 UTC
**Operating System**: Solus 3.9999
**Budgie version**: Budgie 10.4

**Description**

I've already submitted a bug report to the GNOME team, but they said that it's an issue with how the desktop handles the new window, described here: https://bugzilla.gnome.org/show_bug.cgi?id=766808

The relevant commit that fixed and solved the issue of Nautilus opening on Middle-Click in GNOME-shell version 3.30 is: https://gitlab.gnome.org/GNOME/gnome-shell/commit/3efd296fc322c7ddf3f544595c2d31e467ecd393

I hope that can be of help, to solve how Budgie handles new window on middle-click.

**The issue encountered**

When there is a Nautilus window that's in the default directory, a new Nautilus window is unable to open with middle-click

**Steps to reproduce the issue**

Left-click Nautilus icon to open new window.
Without changing directories in first window, middle-click Nautilus icon.
The Icon should time-out, and a new window never opens.

If you change directories from your default startup folder before middle-clicking, then Nautilus will open a new window just fine.

**Comment by Juankz** [comment] 2018-11-27 17:51
I can't reproduce this issue. It works as expected on my machine which was updated 2 days ago. Can you confirm if this is still happening for you?

**Comment by TheSIlentLink** [comment] 2018-11-27 21:15
I can reproduce the issue too on Ubuntu Budgie 18.10

**Comment by drakovyrn** [comment] 2018-11-27 22:56
I update every day, still happens.

You have to make sure that you haven't changed directories in the first window. If you move to a different directory, then you can open another window as expected.

**Comment by Juankz** [comment] 2018-11-28 01:04
Righ. My fault. Didn't read properly

**Comment by pushqrdx** [comment] 2018-12-02 17:51
Same here, steps to reproduce

1. Open Nautilus (Don't change directories)
2. Middle click

Waiting cursor will show but Nautilus will fail to load.

**Comment by drakovyrn** [comment] 2018-12-02 18:34
@Alexander88207 Wrong place bud.

We're talking about middle-clicking on Budgie's Icon Tasklist, not middle-clicking inside of Nautilus.

**Comment by Alexander88207** [comment] 2018-12-02 18:52
> @Alexander88207 Wrong place bud.
> 
> We're talking about middle-clicking on Budgie's Icon Tasklist, not middle-clicking inside of Nautilus.
 
updated thx :)

**Comment by drakovyrn** [comment] 2018-12-02 18:57
@Alexander88207 Are you following the steps mentioned above? It still looks like you're not following the instructions to reproduce the bug.

**Comment by Alexander88207** [comment] 2018-12-02 19:52
> @Alexander88207 Are you following the steps mentioned above? It still looks like you're not following the instructions to reproduce the bug.

ups... sry didn't read properly.

**Comment by maxmbed** [comment] 2018-12-06 21:44
Yep, I also confirm this issue here (on Debian (sid)).

**Comment by JoshStrobl** [comment] 2018-12-07 23:08
Closing this issue, since we have a new Popover system for the IconTasklist. To launch a new instance with the new popover, use the Quick Actions "Launch New Instance" button at the bottom of the popover.

**Closed by JoshStrobl** 2018-12-07 23:08 UTC

**Comment by drakovyrn** [comment] 2018-12-08 16:18
> Closing this issue, since we have a new Popover system for the IconTasklist. To launch a new instance with the new popover, use the Quick Actions "Launch New Instance" button at the bottom of the popover.

It's already possible to launch a new instance of Nautilus just fine from the current quick actions menu using the 'New Window' option. However, this is specific to opening new instance using middle-click, which will still be broken in the coming update if not fixed. While it's only reported to not work with Nautilus at the moment, there is potential to affect other programs that work similarly to Nautilus, as described about in the links I put in the OP.

If this problem needs to wait before getting fixed, fine. If you want to mark 'wontfix', fine. But the issue isn't closed, and will still be there in the next update, unless you deprecate the middle-click action (something I use quite heavily) for some reason.
