### ISSUE TITLE
Side panel inserts blank spaces in certain conditions.

### ISSUE THREAD

**Issue by nelsontkq** [solus-project/budgie-desktop#1970] opened 2020-05-12 21:21 UTC
## Description
Opening and closing non-favorite apps cause the panel to expand.

## Budgie version

budgie-desktop 10.5.1 (git-6f60f10bb03b4779379d9e8ce3681d93a3f17e48)

## Operating system

Solus 4.1
Kernel 5.6.4-152.current

## Steps to reproduce the issue

  1. open budgie desktop settings
  2. add new panel
  3. set `window grouping` and `only show favorited` to on
  4. under the `Settings` tab set Position to left or right
  5. open a non-favorite app, for e.g. Archive Manager, then close it

## Actual result

A blank space is added to the end of the panel. It is unclickable.

![image](https://user-images.githubusercontent.com/19982338/81746340-290eec00-945b-11ea-8bde-71598a6eba38.png)

## Expected result

No blank space is added.

## Additional information

It is not broken if Position is bottom or top. Only left or right.

A workaround is to disable `Only show favorited`, and toggle `Window grouping` to resize the panel again.

**Comment by JoshStrobl** [comment] 2020-10-10 00:00
Duplicate of #1775

**Closed by JoshStrobl** 2020-10-10 00:00 UTC
