### ISSUE TITLE
[request] Task Bar on left & right of screen

### ISSUE THREAD

**Issue by Gibbz** [solus-project/budgie-desktop#672] opened 2016-10-22 04:59 UTC
A feature request.
The ability to move the menu bar to the left/right of the screen with a icon view layout.
Heres an image I found showing what I mean:
http://www.simpletechietips.com/wp-content/uploads/2015/11/Simple-Techie-Tips-SimpleTechieTips.com-2.png

**Comment by ikeydoherty** [comment] 2016-10-22 05:11
Currently Raven opens on the right of the screen, what would be the plan there.. ?

**Comment by ikeydoherty** [comment] 2016-10-26 03:52
Closing as dupe of #541

**Closed by ikeydoherty** 2016-10-26 03:52 UTC
