### ISSUE TITLE
Problem with KeePass Tray Icon

### ISSUE THREAD

**Issue by thumos333** [solus-project/budgie-desktop#1955] opened 2020-04-02 19:50 UTC
Hi,

I recently installed the password manager KeePass from the official repository, and there seems to be a problem with its tray icon. Here are two screenshots, with KeePass running and closed:

![Screenshot from 2020-04-02 22-42-47](https://user-images.githubusercontent.com/29035180/78294988-04f2ed80-7534-11ea-83d0-ac844bc89012.png)

![Screenshot from 2020-04-02 22-43-01](https://user-images.githubusercontent.com/29035180/78294992-06241a80-7534-11ea-8ebf-5ef5051e124b.png)

The icon is displayed as the active input language, for some reason.

**Comment by JoshStrobl** [comment] 2020-04-05 09:04
Duplicate of #1249

**Closed by JoshStrobl** 2020-04-05 09:04 UTC
