### ISSUE TITLE
Separators in the panel randomly placed incorrectly.

### ISSUE THREAD

**Issue by hosttry** [solus-project/budgie-desktop#2051] opened 2020-10-30 02:37 UTC
## Description
Hello, I have an issue with separators in the panel on Budgie, some times they are in different position were they should be, it happens in random boots, some times they are in the correct place but most of the time not, usually fixes itself with a reboot or logging in again, and some times the issue persist, it's a bit random.

## Budgie version

budgie-desktop 10.5.1 (git-210608988ec9b2edb8a3a433a065240382a95eb5)

## Operating system

Solus 4.1 Budgie

## Steps to reproduce the issue

Just booting the system and locking the desktop panel, as I said, It happens randomly on boots, some time appears correctly, some times not.

## Actual result

The separators appears in a different place. They only move here curiously.
![Captura de pantalla de 2020-09-11 08-26-36](https://user-images.githubusercontent.com/29271247/97651463-bd790500-1a21-11eb-8ba5-815e1ff25785.png)

## Expected result
The panel showing things correctly, the image is tiny but everything else is the same
![normal](https://user-images.githubusercontent.com/29271247/97651602-2c565e00-1a22-11eb-84a1-6a674cfc26b7.png)

## Additional information
I waited some updates for a possible fix, apparently the problem persist, Solus is up to date.
And sorry for my English, isn't my main language.

**Comment by JoshStrobl** [comment] 2020-10-30 11:29
Duplicate of #1030

**Closed by JoshStrobl** 2020-10-30 11:29 UTC
