### ISSUE TITLE
Raven sound applet inactive for Firefox

### ISSUE THREAD

**Issue by JonnyCodewalker** [solus-project/budgie-desktop#1675] opened 2018-12-20 11:55 UTC
**Operating System**: Solus 3.9999
**Budgie version**: version: 10.5, release: 180
**Firefox version**: version: 64.0, release: 146

**The issue encountered**
Raven sound applet does not work on Firefox before interacting with it. 

**Steps to reproduce the issue**
- Open Firefox on any webpage that plays sound (eg. youtube)
- Drag Firefox specific volume control to the absolute left in raven
- Close Firefox
- Open Firefox and observe the sound playing

Only when interacting with the slider or the mute button in Raven does the Firefox applet activate, resulting in being able to mute Firefox to stop the sound and then un-muting it but still no sound playing (since the slider is on 0).

**Expected Behaviour**
Upon reopening Firefox it should still be muted.
 
**Other apps tested**
- MPV (works as expected)
- Rhythmbox (works as expected)

**Comment by JoshStrobl** [comment] 2018-12-20 19:53
Duplicate of #1676

**Closed by JoshStrobl** 2018-12-20 19:53 UTC
