### ISSUE TITLE
Keyboard layouts aren't switching

### ISSUE THREAD

**Issue by daisybrain** [solus-project/budgie-desktop#1882] opened 2019-10-08 18:35 UTC
When I'm on the login screen or open the start menu and try to switch a language layout with shortcut nothing happens. In other places such as browser, folders, terminal, etc. it works correctly. 
I'm using the last version of Solus 4 Budgie.

**Comment by JoshStrobl** [comment] 2019-10-08 19:04
Keyboard switching at login is not the responsibility of Budgie, but is provided by slick-greeter and LightDM. Not being able to switch when the Budgie Menu is open is completely normal, as BudgiePopovers take input / exclusive grab. This is a duplicate of numerous "issues" reported in this development tracker and will not be fixed, as Budgie Menu and other BudgiePopovers are working as expected. Just close the menu.

**Closed by JoshStrobl** 2019-10-08 19:04 UTC
