### ISSUE TITLE
comparison between new icon-tasklist icons vs plank

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#1095] opened 2017-08-07 19:47 UTC
**Operating System**: ubuntu 16.04
**Budgie version**: i.e. git master as of 07 Aug

**The issue encountered**

quick comparison screenshot of icon sizes at 101 px between plank and the new icontask-list

![workspace 1_070](https://user-images.githubusercontent.com/996240/29042986-2b4e8f5e-7bb1-11e7-9a6f-a16844987fdb.jpg)

 ...

new icontask list is on the right hand edge.  plank on the left hand side.

Whilst plank grows the icon sizes incrementally, icontask list appears to jump.  Note the large blank areas around the icontask list compared to plank

At 100px:

![workspace 1_071](https://user-images.githubusercontent.com/996240/29043078-86c6f664-7bb1-11e7-94b3-523cccaf30df.jpg)

 ...

**Comment by popout3d** [comment] 2017-08-30 12:34
They are generally too small compared with the width of the panel, and applet icons are mostly tiny.
![image](https://user-images.githubusercontent.com/30693254/29872551-011f4258-8d88-11e7-946a-689041ced93e.png)

**Comment by niyasc** [comment] 2017-08-31 05:48
I think it is same as the issue with icontask-list in 10.2.8 release
#701

**Comment by JoshStrobl** [comment] 2018-09-27 07:34
This is indeed a duplicate of #701.

**Closed by JoshStrobl** 2018-09-27 07:34 UTC
