### ISSUE TITLE
Many unread notifications causes poor performance of Raven sidebar

### ISSUE THREAD

**Issue by arcooke** [solus-project/budgie-desktop#1934] opened 2020-02-02 07:26 UTC
## Description

Raven sidebar animation gets _very_ choppy when there are many unread notifications.

## Budgie version

10.5.1

## Operating system

Solus 4

## Steps to reproduce the issue

Let notifications pile up for weeks and never check them.  Raven sidebar starts performing very poorly.  Clear notifications, problem instantly fixed

## Actual result

Slow/choppy animation when there are many notifications

## Expected result
Not slow/choppy animation when there are many notifications

## Additional information
AMD Vega 64 - Mesa 19.3.2-135

**Comment by JoshStrobl** [comment] 2020-02-03 05:48
Duplicate of #1802

**Closed by JoshStrobl** 2020-02-03 05:48 UTC

**Comment by MatthewScholefield** [comment] 2020-02-04 21:59
@JoshStrobl Why mark as a duplicate of a closed issue? Seems like this presents a real world use case.

**Comment by EbonJaeger** [comment] 2020-02-04 22:03
...Because it's a duplicate of the issue (i.e., the same issue)?

**Comment by MatthewScholefield** [comment] 2020-02-04 22:05
True, lol. I guess I mean why close after marking as a duplicate if it presents new info.

**Comment by EbonJaeger** [comment] 2020-02-04 22:06
Because it should be posted in the original issue, in order to keep everything together and organized.
