### ISSUE TITLE
Do-not disturb icon is bigger

### ISSUE THREAD

**Issue by bsucker98** [solus-project/budgie-desktop#1684] opened 2018-12-27 12:16 UTC
**Operating System**: Solus 3.9999
**Budgie version**: Budgie 10.5

**The issue encountered**

do-not disturb icon which is on raven notification is noticeably few pixels larger.

**Steps to reproduce the issue**

go to raven notification and click on the bell icon & see it's getting bigger.

**Comment by JoshStrobl** [comment] 2018-12-28 10:21
Duplicate of #1470

**Closed by JoshStrobl** 2018-12-28 10:21 UTC
