### ISSUE TITLE
Spacer applet: spacer size (horizontal) affects all applets' vertical size - they get smaller

### ISSUE THREAD

**Issue by abetkin** [solus-project/budgie-desktop#1528] opened 2018-08-07 14:41 UTC
Solus 3.9999
budgie-desktop v10.4-85-g36667bcb

![spacer_size](https://user-images.githubusercontent.com/2223279/43782963-359cde70-9a69-11e8-812b-28f5649de1ad.png)

In the picture below spacer size is set to 60

![spacer_size2](https://user-images.githubusercontent.com/2223279/43783028-60163e58-9a69-11e8-967c-6fb4ad08ffb2.png)

**Comment by Coeur-Noir** [comment] 2018-08-13 21:09
See also https://github.com/solus-project/budgie-desktop/issues/1245 or https://github.com/solus-project/budgie-desktop/issues/1241#issuecomment-394124189

**Comment by JoshStrobl** [comment] 2018-08-14 03:44
Duplicate of #1245

**Closed by JoshStrobl** 2018-08-14 03:44 UTC
