### ISSUE TITLE
Panel hides windows when second display is much larger and higher

### ISSUE THREAD

**Issue by stobbsm** [solus-project/budgie-desktop#1772] opened 2019-03-18 23:44 UTC
## Description

Have a new monitor that is configured vertically. If the top of the second monitor is positioned higher then the primary monitor, maximized windows will have their window buttons and titles hidden by the panel (when it's at the top).

## Budgie version
Budge 10.5

## Operating system
Solus 4

## Steps to reproduce the issue
Set a monitor to vertical, with the top being higher then the panel, and move the panel to the top. Maximize a window, and the buttons and title are hidden.

## Actual result
![Screenshot from 2019-03-18 17-41-14](https://user-images.githubusercontent.com/4227473/54570721-2d4d8f80-49a5-11e9-88b8-e5d33fba9ecb.png)

## Expected result
Windows are maximized properly, without being hidden.

## Additional information
I've work around it by setting the top of each monitor to 0, meaning this is probably a virtual desktop sizing bug, as it works as expected when this is set, as per: 
![Screenshot from 2019-03-18 17-41-42](https://user-images.githubusercontent.com/4227473/54570768-6554d280-49a5-11e9-83b7-337043c65324.png)

**Comment by BryceBeagle** [comment] 2019-03-19 04:34
I have the exact same issue, but only with the panel at the bottom of the window. It works fine for me when it's at the top.

**Comment by JoshStrobl** [comment] 2019-03-19 05:11
Duplicate of #1099

**Closed by JoshStrobl** 2019-03-19 05:11 UTC
