### ISSUE TITLE
Systray icons on 4k resolution

### ISSUE THREAD

**Issue by timojuonoja** [solus-project/budgie-desktop#1230] opened 2017-10-30 13:46 UTC
**Operating System**: Solus 3.26.1
**Budgie version**: 10.4

Systray icons are using too much space when using resolution 3840x2160 and 200% scaling level.

![kuvakaappaus 2017-10-30 15 34 46](https://user-images.githubusercontent.com/7699788/32174011-5ec823e4-bd89-11e7-8add-59421094a6e5.png)

**Comment by JoshStrobl** [comment] 2018-12-10 21:54
Duplicate of #685

**Closed by JoshStrobl** 2018-12-10 21:54 UTC
