### ISSUE TITLE
Meta key app launch/focus

### ISSUE THREAD

**Issue by leonbohn** [solus-project/budgie-desktop#1781] opened 2019-03-23 20:09 UTC
### Current Budgie version
The current version of budgie, i.e. 10.5

### Use-cases
This is a feature available in Windows 10 and Unity as well as many GNOME extensions like DashToDock and DashToPanel. It makes app switching a lot more convenient, especially if it also works across different desktops.

### Proposal
I would actually like to try implementing this myself if somebody would be so kind as to provide some starting points, since the project is pretty large for a newcomer and I have never really contributed to a big open source project like this before. I would think that this is something to be implemented in the icon-tasklist applet.

### References
Somebody already tackled this [issue](https://forum.manjaro.org/t/budgie-desktop-shortcut-for-super-1-to-navigate-to-window-1/59237) with a nodejs [script](https://www.npmjs.com/package/budgie-launcher-super), but I personally think that it might be better to make this available as a built-in option for the plugin.

Let me know what you think about the proposal and thank you for your great work!

**Comment by JoshStrobl** [comment] 2019-03-24 08:33
Duplicate of #1015

**Closed by JoshStrobl** 2019-03-24 08:33 UTC
