### ISSUE TITLE
Weird panel-behavior when alt-tabbing out of fullscreen wine-application

### ISSUE THREAD

**Issue by krissel** [solus-project/budgie-desktop#681] opened 2016-10-25 23:08 UTC
**Operating System**:  Solus 1.2.1
**Budgie version**:  Budgie 10.2.8

When running the game Hearthstone with wine and alt-tabbing out of it several times, the panel shows weird behavior.

I've set the panel to be at the bottom of the screen, but as can be seen in the first screenshot, after leaving Hearthstone, the panel sits nearly at the top of the screen. I am still able to click icons, but menus open on top of the panel, so they aren't visible anymore.

Another time the panel completely vanished, as can be seen in the second screenshot. Windows still think it is there, but it's not just a visual glitch, since i am no longer able to click any (maybe invisible) icons there.

**Steps to reproduce the issue**
1) Run Hearthstone through wine
2) alt-tab out of it several times
3) leave Hearthstone

 ...
![panel1](https://cloud.githubusercontent.com/assets/6059523/19707483/2304c8ba-9b18-11e6-934c-bb8993c93204.png)
![panel2](https://cloud.githubusercontent.com/assets/6059523/19707493/27e1dc10-9b18-11e6-97c7-bba817fd5dd1.png)

**Comment by ikeydoherty** [comment] 2016-10-25 23:32
I'm gonna close this as a duplicate of #634 and #612 - these issues are being resolved in my own rewrite of the panel over @ https://github.com/ikeydoherty/budgie-next

They're know, they're weird, but a solution is on the horizon. Stay tuned!

**Closed by ikeydoherty** 2016-10-25 23:32 UTC
