### ISSUE TITLE
Broken WiFi Tray Icon

### ISSUE THREAD

**Issue by alecbcs** [solus-project/budgie-desktop#1662] opened 2018-12-10 01:12 UTC
**Operating System**: Solus 3.9999
**Budgie version**: i.e. Budgie 10.5 (From unstable Solus Repo )

Before submitting ANY issue, please run the following command to
verify that you have, at minimum, Budgie 10.2.7, to provide the
exact version of your Budgie installation:

budgie-desktop v10.4-160-g596f0a90

**The issue encountered**
After computer resumes from sleep, the WiFi Icon appears much smaller and does not scale correctly. Shown below.
![screenshot from 2018-12-09 17-55-57](https://user-images.githubusercontent.com/19558067/49705717-9458ec80-fbdd-11e8-925a-0f435b05016c.png)

**Steps to reproduce the issue**
Install Budgie 10.5 from the Solus unstable repository. Then change your screen scaling factor to anything else. Next, change it back to original and wake the computer from sleep.

**Comment by JoshStrobl** [comment] 2018-12-10 17:19
As this is using the System Tray applet (and thus the XEmbed support), with it being under the purview of nm-applet rather than being a native Budgie applet, closing this as a duplicate of #610. This isn't "broken" but rather "XEmbed-based icons are not scaling properly".

**Closed by JoshStrobl** 2018-12-10 17:19 UTC
