### ISSUE TITLE
Task manager items uses all panel space

### ISSUE THREAD

**Issue by feskyde** [solus-project/budgie-desktop#267] opened 2015-12-30 04:28 UTC
A bug present since the old Budgie, explained better with this image:

![captura de pantalla de 2015-12-30 01-24-54](https://cloud.githubusercontent.com/assets/12128317/12046272/8898b900-ae94-11e5-9414-9719e89e2323.png)

**Comment by fastrizwaan** [comment] 2016-01-01 10:42
The icon tasks are also has the same issue: please observe the *clock* and icons behind
![screenshot from 2016-01-01 16-09-38](https://cloud.githubusercontent.com/assets/1161682/12070560/3967555c-b0a2-11e5-9cb0-e6e1ba0637b5.png)

**Comment by ikeydoherty** [comment] 2016-01-01 16:00
This will require a bit of work to get it fixed, it means swapping our 3 GtkBox's for a GtkFixed with a cusom layout manager.. Ongoing

**Comment by ikeydoherty** [comment] 2016-01-25 20:15
Closing as dupe of #83

**Closed by ikeydoherty** 2016-01-25 20:15 UTC
Labels: bug
