### ISSUE TITLE
Pinning budgie-desktop-settings leaves a blank icon in the icon-task-list

### ISSUE THREAD

**Issue by fossfreedom** [solus-project/budgie-desktop#2041] opened 2020-10-15 21:09 UTC
## Description
After pinning budgie-desktop-settings and closing an empty icon is left saying budgie-panel

![image](https://user-images.githubusercontent.com/996240/96185979-acfd6080-0f32-11eb-8db4-fb36be180483.png)

## Budgie version
git master https://github.com/solus-project/budgie-desktop/commit/f114c60c0fc381af5da20f75e584cb505dd3a191

## Operating system
Ubuntu Budgie 20.10

## Steps to reproduce the issue
As per the description

## Actual result
see screenshot above

## Expected result
The budgie-desktop-settings "settings" icon

The correct settings icon is visible on launch of budgie-desktop-settings - the icon is replaced with the blank icon in the picture

## Additional information
In addition lots of wnck messages are displayed in the terminal when budgie-desktop-settings is closed (after pinning)

**Comment by JoshStrobl** [comment] 2020-10-16 04:19
Considering this a duplicate of #1697

**Closed by JoshStrobl** 2020-10-16 04:19 UTC
