### ISSUE TITLE
Ibus not working properly

### ISSUE THREAD

**Issue by ndtoan96** [solus-project/budgie-desktop#1356] opened 2018-03-16 14:37 UTC
**Operating System**: Ubuntu Budgie 18.04
**Budgie version**: Budgie 10.4

**The issue encountered**

After installing an input method in `Region & Language` --> `Input Sources`, the input method icon wouldn't appear unless I add the applet `Keyboard Layout Indicator`. But in my case this won't help because the input method I use which is `ibus-unikey` has its own configuration and I cant access them via `Keyboard Layout Indicator`.

And one more thing, the option **Allow different sources for each window** doesn't work for me. The applet `Keyboard AutoSwitch` does similar job but I have to add it in the top panel without the need to touch it once and it won't help me use different input methods in different windows of the same app.

**Steps to reproduce the issue**

1. Go to `Setting` -> `Region and Language` -> `Manage Installed Language` -> `Install/Remove Languages`
1. Check `Vietnamese`, apply and wait for the installation to complete
1. Open `terminal`, type `ibus restart`
1. Re-open `Setting` -> `Region and Language`, click the plus sign and choose **Vietnamese** -> **Vietnamese (Unikey)**

After that, in other Desktop Environments (such as Unity, GNOME, Cinamon), there would be an icon like this: 
![unity](http://2.bp.blogspot.com/-n_blnCYePd4/VzNzI3OdpCI/AAAAAAAAA1A/Tw7mC70z2BcQyD9SGSrLr5noIyZLc6oNACK4B/s1600/Screenshot%2Bfrom%2B2016-05-12%2B00-59-37.png)

But you won't see anything, you can still change input method by shortcut `super`+`space` though. Normally, you just need to install `Keyboard Layout Indcator` applet and that's it. However, I need to configure my input method via the options in the drop-down, like type of key combinations, encoding, macro and stuffs. The `Keyboard Layout Indicator` applet only gives me this:
<img src="https://i.imgur.com/dPM35rT.jpg" width="200">

**Comment by baimafeima** [comment] 2018-09-10 21:14
Related to #729

**Comment by JoshStrobl** [comment] 2020-10-09 16:21
Marking as resolved duplicate of #1785

**Closed by JoshStrobl** 2020-10-09 16:21 UTC
