### ISSUE TITLE
KeyboardLayoutApplet: does not show all layouts

### ISSUE THREAD

**Issue by baraclese** [solus-project/budgie-desktop#1785] opened 2019-03-29 13:39 UTC
With the latest gnome stack on arch linux the keyboard layout applet does not show the layout "Japanese (Kana Kanji)" but I can still switch to it and use it via win+space. 

## Budgie version
budgie-desktop 10.5 (git-38b69f05619f0b1a681276dc258929f2fcb7a750)

## Operating system
Arch Linux

## Description
Adding the language "Japanese (Kana Kanji)" in the Gnome Control Panel (Region & Language) results in these messages:

budgie-panel[2007]: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
budgie-panel[2007]: KeyboardLayoutApplet.vala:428: Error adding source ibus|kkc: Unknown input method: id
budgie-wm[6379]: Couldn't upload new XKB keyboard description

Selecting the language via the keyboard shortcut results in:
budgie-panel[2007]: KeyboardLayoutApplet.vala:486: WARNING: Missing child in layout!!

**Comment by tista500** [comment] 2019-04-13 23:10
Same issue +1 (Ubuntu Disco, IBus 1.5.19 built with Vala 0.44.x).

This may or may not be related to IBus change? : https://github.com/ibus/ibus/commit/4d7c1e00e15921a0448947961183c1c124b6b49f

On my environments, these seem to revive IBus engine entries in KeyboardLayoutApplet:
```diff
diff --git a/src/applets/keyboard-layout/KeyboardLayoutApplet.vala b/src/applets
/keyboard-layout/KeyboardLayoutApplet.vala
index 3edc13bb..95213021 100644
--- a/src/applets/keyboard-layout/KeyboardLayoutApplet.vala
+++ b/src/applets/keyboard-layout/KeyboardLayoutApplet.vala
@@ -125,7 +125,7 @@ class AppletIBusManager : GLib.Object
      * Attempt to grab the ibus engine for the given name if it
      * exists, or returns null
      */
-    public weak IBus.EngineDesc? get_engine(string name)
+    public IBus.EngineDesc? get_engine(string name)
     {
         return this.engines.lookup(name);
     }
```
```diff
diff --git a/src/wm/keyboard.vala b/src/wm/keyboard.vala
index 5a496f73..59f674f9 100644
--- a/src/wm/keyboard.vala
+++ b/src/wm/keyboard.vala
@@ -36,7 +36,7 @@ class InputSource
         this.layout = layout;
         this.variant = variant;
         this.xkb = xkb;
-        weak IBus.EngineDesc? engine = null;
+        IBus.EngineDesc? engine = null;
 
         /* Attempt to fetch engine in the ibus daemon engine list */
         if (iman != null) {
```

And some `weak` strings in `src/wm/keyboard.vala` HashTables might be better switching to `unowned` as well (weak pointers give ton of deprecated warnings when build)? But anyway I'm not the Vala specialist, so those might not make any sense for devs though (memory managements, ...etc)... ;P

@fossfreedom,

I know you're extremely busy for testing Disco Budgie currently, but if you had time to check IBus in Disco, please concern the Vala and IBus upstream changes, too...

Regards.

**Comment by tista500** [comment] 2019-04-13 23:41
I'm sorry I was wrong... :(
Reverting to IBus packages build with legacy Vala was the way as an only workaround?

**Comment by tista500** [comment] 2019-04-14 01:00
These diffs make sense? : https://paste.ubuntu.com/p/fbM69vznkf/

**Comment by fossfreedom** [comment] 2019-04-14 13:50
How do you reproduce this?  ... I have added English US to my English GB
via Language & Region settings on 19.04 and I see both layouts to be
selected in the keyboard layout applet.

**Comment by tista500** [comment] 2019-04-14 15:16
> I have added English US to my English GB via Language & Region settings on 19.04 and I see both layouts to be selected in the keyboard layout applet.

Original reporter and me are talking about IM engine instead of keyboard layout, then Original reporter uses IBus-kkc engine:

* Install Japanese IBus-kkc engine: `sudo apt install ibus-kkc`
* Logout and logback in to restart IBus daemon (or simply run `ibus-daemon -rd`?)
* Add ibus-kkc engine via G-C-C like this ("Japanese (Kana Kanji)" is ibus-kkc engine) :
![Screenshot from 2019-04-15 00-04-49](https://user-images.githubusercontent.com/6073622/56094880-47ca4880-5f12-11e9-80fd-a43aa2c21160.png)
And gsettings key `org.gnome.desktop.input-sources sources` should be like this: `[('xkb', 'us'), ('ibus', 'kkc')]`
* Check and verify the ibus-kkc was shown in KeyboardLayoutApplet popover's layout list and applet tuned to "JA" from "US" when switched input-sources to ibus-kkc:
![Screenshot from 2019-04-15 00-14-09](https://user-images.githubusercontent.com/6073622/56095025-91676300-5f13-11e9-84bf-7b27a2ab91a0.png)

Regards.

**Comment by fossfreedom** [comment] 2019-04-15 12:56
ack - can reproduce - it also crashed budgie-wm ibus_engine_desc_get_layout_variant.

will try to have a look at your patch and also the above to see why the crash happens - busy with 19.04 release matters though....

**Comment by fossfreedom** [comment] 2019-04-18 12:07
ok - I don't fully understand the valac changes that is causing this - but it appears to be variable scope changes.

attached is a diff for the mutter330reduxII branch (i.e. you can apply it on the source for 19.04 UB) that at first glance seems to resolve this matter + fixes the crash in budgie-wm when creating non xkb layouts.

Really need to understand why the scope changes causes this issue and if there is a cleaner way to resolve before doing a formal PR

Note - I've slightly rejigged the src/wm/ibus.vala to be consistent with src/applets/keyboard-layout/KeyboardLayoutApplet.vala - there is comments in the code from Ikey that the code is naughtily copy-pasted between the two modules ... but seems to have got out of sync at some-point.


[output.diff.txt](https://github.com/solus-project/budgie-desktop/files/3094294/output.diff.txt)

**Comment by tista500** [comment] 2019-04-18 13:26
> attached is a diff for the mutter330reduxII branch (i.e. you can apply it on the source for 19.04 UB) that at first glance seems to resolve this matter + fixes the crash in budgie-wm when creating non xkb layouts.

Worked for me (Vala 0.44.3, IBus 1.5.19). Thanks.

**Comment by quycao** [comment] 2019-10-05 04:19
> > attached is a diff for the mutter330reduxII branch (i.e. you can apply it on the source for 19.04 UB) that at first glance seems to resolve this matter + fixes the crash in budgie-wm when creating non xkb layouts.
> 
> Worked for me (Vala 0.44.3, IBus 1.5.19). Thanks.

How can you fixed it, please guide me in detail. Many people get same problem.
https://github.com/solus-project/budgie-desktop/issues/1823
https://github.com/solus-project/budgie-desktop/issues/1850
Many thanks.

**Comment by patrickdark** [comment] 2019-10-27 00:09
I have a similar problem in Solus 4 Budgie; Chewing (ibus-chewing) and New Zhuyin (ibus-libzhuyin), two traditional Chinese input methods, aren't listed in the Keyboard Layout applet after installation making Chinese character input methods unusable. I filed an issue on that--probably in the wrong place--at https://dev.getsol.us/T8445.

One can cycle to these Input Sources using the Meta (Windows) + Spacebar keys, at least; ibus-chewing displays a blue icon indicating that it's selected whereas ibus-libzhuyin displays nothing to indicate that it's selected. The wrong Input Source indicator displays in the applet in both cases because neither Input Source is listed.

Unfortunately, the Input Sources are nevertheless unusable because the character selection overlay can't be made to appear, so there's no way to select the desired characters

**Comment by quycao** [comment] 2020-04-26 14:35
It's seem that nobody in budgie development team take care that problem. I regretted budgie is a good desktop but unuseable because small issue like that :(

**Comment by shedaniel** [comment] 2020-05-29 12:37
Any updates on this? The patch worked for me but would like to know why it is not merged into the project itself? Thanks.

**Closed** 2020-06-30 21:29 UTC
