### ISSUE TITLE
Applet icons, system tray icons, and task list icons are undersized/deshaped

### ISSUE THREAD

**Issue by haoyet** [solus-project/budgie-desktop#1808] opened 2019-05-01 13:03 UTC
My screen has 1080p resolution
All of the icons are extraordinarily small especially the dock

![image](https://user-images.githubusercontent.com/28365438/57017946-5a6d9e80-6bef-11e9-9517-b826c39f6a1e.png)

I have to set dock size to 101 in order to use 48x48 icons
The Trash and Show Desktop applet icons are even smaller in comparison.

The top bar, too, has deshaped and undersized icons

![image](https://user-images.githubusercontent.com/28365438/57018060-db2c9a80-6bef-11e9-979e-14abd7680f9c.png)

Any workarounds? Or ways to make it bigger through changing code?

**Comment by JoshStrobl** [comment] 2019-05-01 13:10
Duplicate of #701. Please search in the future.

**Closed by JoshStrobl** 2019-05-01 13:10 UTC
