### ISSUE TITLE
Rotating Wallpapers no longer working in 10.2.8

### ISSUE THREAD

**Issue by asonix** [solus-project/budgie-desktop#686] opened 2016-10-26 22:20 UTC
**Operating System**: Solus 1.2.1, Arch Linux
**Budgie version**: Budgie 10.2.8

**The issue encountered**
Rotating wallpapers no longer work, the background is just black.

**Steps to reproduce the issue**
1. Have Budgie 10.2.8
2. Set a rotation wallpaper via .xml file (gnome standard)

**Comment by ikeydoherty** [comment] 2016-10-27 02:52
"no longer working" ? They've never been supported in Budgie. This is a duplicate of #261 

Also note just because something is a "gnome standard" doesn't instantly make it applicable to Budgie :)

**Closed by ikeydoherty** 2016-10-27 02:52 UTC
